"use client";
import type { ColumnDef } from "@tanstack/react-table";
import { DataTable } from "@/components/ui/data-table";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
type Action = (data: FormData) => Promise<void>;
type Option = { id: string; name: string };
export type AccountRow = { id: string; name: string; email: string; role: "ADMIN" | "DIETITIAN" | "NURSE" | "KITCHEN"; roleLabel: string; departmentId: string; department: string; status: "ACTIVE" | "INACTIVE"; statusLabel: string };
const roleLabels = { ADMIN: "Quản trị", DIETITIAN: "Dinh dưỡng", NURSE: "Điều dưỡng", KITCHEN: "Nhà bếp" } as const;
export function AccountTable({ data, departments, saveAction, statusAction }: { data: AccountRow[]; departments: Option[]; saveAction: Action; statusAction: Action }) {
 const columns: ColumnDef<AccountRow, unknown>[] = [
  { accessorKey: "name", header: "Họ tên", cell: ({ row }) => <strong>{row.original.name}</strong> }, { accessorKey: "email", header: "Email" }, { accessorKey: "roleLabel", header: "Vai trò" }, { accessorKey: "department", header: "Khoa" }, { accessorKey: "statusLabel", header: "Trạng thái" },
  { id: "actions", header: "Thao tác", enableSorting: false, cell: ({ row }) => { const account = row.original; return <Dialog><DialogTrigger asChild><button type="button" className="secondary-button">Sửa</button></DialogTrigger><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>Sửa tài khoản {account.name}</DialogTitle><DialogDescription>Cập nhật thông tin hoặc đổi trạng thái. Mọi thay đổi vẫn được ghi nhật ký.</DialogDescription></DialogHeader><div className="admin-detail"><form action={saveAction} className="admin-grid"><input type="hidden" name="userId" value={account.id}/><label>Họ tên<input name="displayName" defaultValue={account.name} required/></label><label>Email<input name="email" type="email" defaultValue={account.email} required/></label><label>Vai trò<select name="role" defaultValue={account.role}>{Object.entries(roleLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Khoa<select name="departmentId" defaultValue={account.departmentId}><option value="">—</option>{departments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Mật khẩu mới (để trống nếu giữ nguyên)<input name="password" type="password" minLength={10} maxLength={256} autoComplete="new-password"/></label><button className="secondary-button">Lưu sửa đổi</button></form><form action={statusAction} className="status-form"><input type="hidden" name="userId" value={account.id}/><input type="hidden" name="status" value={account.status === "ACTIVE" ? "INACTIVE" : "ACTIVE"}/><input name="reason" minLength={3} maxLength={500} required placeholder="Lý do bắt buộc"/><button className={account.status === "ACTIVE" ? "danger-button" : "secondary-button"}>{account.status === "ACTIVE" ? "Vô hiệu hóa" : "Kích hoạt lại"}</button></form></div></DialogContent></Dialog>; } },
 ];
 return <DataTable columns={columns} data={data} getRowId={(row) => row.id} filterPlaceholder="Lọc họ tên, email, khoa…" emptyMessage="Chưa có tài khoản."/>;
}
