"use client";
import { startTransition, useTransition } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm, useWatch } from "react-hook-form";
import { z } from "zod";

const error = (id: string, message?: string) => message ? <span id={id} role="alert" className="field-error">{message}</span> : null;
const settingsSchema = z.object({ advanceEntryDays: z.number().int().min(1, "Tối thiểu 1 ngày.").max(60, "Tối đa 60 ngày."), serviceCompletionMinutes: z.number().int().min(15, "Tối thiểu 15 phút.").max(240, "Tối đa 240 phút."), publicMenuImages: z.boolean(), publicViewCountVisible: z.boolean(), sondeEnabled: z.boolean(), warehouseMode: z.enum(["A", "B"]), warehouseApprovalRole: z.enum(["ADMIN", "DIETITIAN", "KITCHEN"]), reason: z.string().trim().min(3, "Nêu lý do với ít nhất 3 ký tự.").max(500) });
const operationalSettingsSchema = settingsSchema.extend({ dataStartDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Chọn ngày bắt đầu dữ liệu.") });
type SettingsFields = z.infer<typeof operationalSettingsSchema>;
type MealType = { id: string; name: string; cutoffTime: string; serviceTime: string; feedingRoute: "NORMAL" | "SONDE" };
export function SettingsForm({ settings, mealTypes, action }: { settings: Omit<SettingsFields, "reason">; mealTypes: MealType[]; action: (data: FormData) => Promise<void> }) {
 const [pending, run] = useTransition(); const { register, handleSubmit, control, formState: { errors } } = useForm<SettingsFields>({ resolver: zodResolver(operationalSettingsSchema), shouldFocusError: true, defaultValues: { ...settings, reason: "" } });
 const sondeEnabled = useWatch({ control, name: "sondeEnabled" });
 return <form onSubmit={handleSubmit((values, event) => { const form = event?.currentTarget; if (form instanceof HTMLFormElement) { const data = new FormData(form); for (const key of ["sondeEnabled", "publicMenuImages", "publicViewCountVisible"] as const) data.set(key, values[key] ? "true" : "false"); startTransition(() => run(() => action(data))); } })} noValidate className="admin-form settings-form"><div className="admin-grid settings-primary-grid">
  <label htmlFor="dataStartDate">Ngày bắt đầu dữ liệu<input id="dataStartDate" type="date" {...register("dataStartDate")}/><small>Lịch và báo cáo không thể chọn trước mốc này.</small></label>
  <label htmlFor="advanceEntryDays">Số ngày được nhập trước<input id="advanceEntryDays" type="number" min="1" max="60" {...register("advanceEntryDays", { valueAsNumber: true })} aria-invalid={!!errors.advanceEntryDays} aria-describedby={errors.advanceEntryDays ? "advanceEntryDays-error" : undefined}/>{error("advanceEntryDays-error", errors.advanceEntryDays?.message)}</label>
  <label htmlFor="serviceCompletionMinutes">Phút chuyển sang bữa kế<input id="serviceCompletionMinutes" type="number" min="15" max="240" step="5" {...register("serviceCompletionMinutes", { valueAsNumber: true })} aria-invalid={!!errors.serviceCompletionMinutes}/></label>
  <label className="check-field sonde-setting-control"><input type="checkbox" {...register("sondeEnabled")}/><span>Bật đường nuôi Sonde<small className={sondeEnabled ? "sonde-inline-state is-on" : "sonde-inline-state is-off"}>{sondeEnabled ? "Đang bật · lịch Sonde sẽ được áp dụng" : "Đang tắt · các màn nghiệp vụ sẽ ẩn Sonde"}</small></span></label>
  <label className="check-field"><input type="checkbox" {...register("publicMenuImages")}/><span>Hiện ảnh món ăn cho bệnh nhân</span></label>
  <label className="check-field"><input type="checkbox" {...register("publicViewCountVisible")}/><span>Hiện lượt xem trên trang chủ</span></label>
  <label htmlFor="warehouseMode">Mode kho<select id="warehouseMode" {...register("warehouseMode")}><option value="A">Mode A · một kho tổng</option><option value="B">Mode B · kho bếp + kho sonde</option></select></label>
  <label htmlFor="warehouseApprovalRole">Role duyệt kho<select id="warehouseApprovalRole" {...register("warehouseApprovalRole")}><option value="ADMIN">Quản trị</option><option value="DIETITIAN">Dinh dưỡng</option><option value="KITCHEN">Nhà bếp</option></select></label>
 </div><div className="meal-time-grid">{(["NORMAL", ...(sondeEnabled ? ["SONDE" as const] : [])] as const).map((route) => <section className="meal-schedule-settings" key={route}><header><strong>{route === "SONDE" ? "Lịch cữ Sonde" : "Lịch suất ăn thường"}</strong><span>{mealTypes.filter((meal) => meal.feedingRoute === route).length} bữa/cữ</span></header><table><thead><tr><th>Tên bữa/cữ</th><th>Giờ chốt</th><th>Giờ phục vụ</th></tr></thead><tbody>{mealTypes.filter((meal) => meal.feedingRoute === route).map((meal) => <tr key={meal.id}><th>{meal.name}<input type="hidden" name="mealTypeId" value={meal.id}/></th><td><input aria-label={`Giờ chốt ${meal.name}`} name="cutoffTime" type="time" defaultValue={meal.cutoffTime} required/></td><td><input aria-label={`Giờ phục vụ ${meal.name}`} name="serviceTime" type="time" defaultValue={meal.serviceTime} required/></td></tr>)}</tbody></table></section>)}</div>
 <div className="admin-submit"><label htmlFor="settings-reason">Lý do thay đổi<input id="settings-reason" {...register("reason")} autoComplete="off" aria-invalid={!!errors.reason} aria-describedby={errors.reason ? "settings-reason-error" : undefined} placeholder="Nêu lý do để lưu AuditLog…"/>{error("settings-reason-error", errors.reason?.message)}</label><button className="primary-action" disabled={pending}>{pending ? "Đang áp dụng…" : "Áp dụng cấu hình"}</button></div></form>;
}

const accountSchema = z.object({ displayName: z.string().trim().min(2, "Họ tên cần ít nhất 2 ký tự.").max(100), email: z.string().trim().email("Nhập email hợp lệ."), role: z.enum(["ADMIN", "DIETITIAN", "NURSE", "KITCHEN"]), departmentId: z.string(), password: z.string().min(10, "Mật khẩu cần ít nhất 10 ký tự.").max(256) }).superRefine((value, context) => { if (value.role === "NURSE" && !value.departmentId) context.addIssue({ code: "custom", path: ["departmentId"], message: "Chọn khoa cho điều dưỡng." }); });
const scopedAccountSchema = accountSchema.and(z.object({ kitchenRoute: z.string() })).superRefine((value, context) => { if (value.role === "KITCHEN" && !["NORMAL", "SONDE"].includes(value.kitchenRoute)) context.addIssue({ code: "custom", path: ["kitchenRoute"], message: "Chọn phạm vi bếp." }); });
type AccountFields = z.infer<typeof scopedAccountSchema>;
export function AccountCreateForm({ departments, action }: { departments: { id: string; name: string }[]; action: (data: FormData) => Promise<void> }) {
 const [pending, run] = useTransition(); const { register, handleSubmit, formState: { errors } } = useForm<AccountFields>({ resolver: zodResolver(scopedAccountSchema), shouldFocusError: true, defaultValues: { displayName: "", email: "", role: "NURSE", departmentId: "", kitchenRoute: "", password: "" } });
 return <form onSubmit={handleSubmit((_values, event) => { const form = event?.currentTarget; if (form instanceof HTMLFormElement) { const data = new FormData(form); startTransition(() => run(() => action(data))); } })} noValidate className="admin-grid account-create">
  <label>Họ tên<input {...register("displayName")} autoComplete="name" aria-invalid={!!errors.displayName} aria-describedby={errors.displayName ? "account-name-error" : undefined}/>{error("account-name-error", errors.displayName?.message)}</label>
  <label>Email<input type="email" {...register("email")} autoComplete="email" spellCheck={false} aria-invalid={!!errors.email} aria-describedby={errors.email ? "account-email-error" : undefined}/>{error("account-email-error", errors.email?.message)}</label>
  <label>Vai trò<select {...register("role")}><option value="ADMIN">Quản trị</option><option value="DIETITIAN">Dinh dưỡng</option><option value="NURSE">Điều dưỡng</option><option value="KITCHEN">Nhà bếp</option></select></label>
  <label>Khoa cho điều dưỡng<select {...register("departmentId")} aria-invalid={!!errors.departmentId} aria-describedby={errors.departmentId ? "account-department-error" : undefined}><option value="">—</option>{departments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>{error("account-department-error", errors.departmentId?.message)}</label>
  <label>Phạm vi cho tài khoản bếp<select {...register("kitchenRoute")} aria-invalid={!!errors.kitchenRoute}><option value="">—</option><option value="NORMAL">Bếp ăn thường</option><option value="SONDE">Bếp Sonde</option></select>{error("account-kitchen-route-error", errors.kitchenRoute?.message)}</label>
  <label>Mật khẩu ban đầu<input type="password" {...register("password")} autoComplete="new-password" aria-invalid={!!errors.password} aria-describedby={errors.password ? "account-password-error" : undefined}/>{error("account-password-error", errors.password?.message)}</label>
  <button className="primary-action" disabled={pending}>{pending ? "Đang tạo…" : "Tạo tài khoản"}</button>
 </form>;
}
