"use client";
import type { ColumnDef } from "@tanstack/react-table";
import { DataTable } from "@/components/ui/data-table";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
type Action = (data: FormData) => Promise<void>;
type DietCode = { id: string; code: string; name: string };
export type DietTypeRow = { id: string; code: string; name: string; feedingRoute: "NORMAL" | "SONDE"; routeLabel: string; dietCodeRefId: string; dietCode: string; sortOrder: number; status: "ACTIVE" | "INACTIVE"; statusLabel: string };
export function DietTypeTable({ data, dietCodes, saveAction, statusAction }: { data: DietTypeRow[]; dietCodes: DietCode[]; saveAction: Action; statusAction: Action }) {
 const columns: ColumnDef<DietTypeRow, unknown>[] = [
  { accessorKey: "code", header: "Mã", cell: ({ row }) => <strong>{row.original.code}</strong> }, { accessorKey: "name", header: "Tên chế độ" }, { accessorKey: "routeLabel", header: "Đường nuôi" }, { accessorKey: "dietCode", header: "Quy định" }, { accessorKey: "sortOrder", header: "Thứ tự", meta: { numeric: true } }, { accessorKey: "statusLabel", header: "Trạng thái" },
  { id: "actions", header: "Thao tác", enableSorting: false, cell: ({ row }) => { const diet = row.original; return <Dialog><DialogTrigger asChild><button type="button" className="secondary-button">Sửa</button></DialogTrigger><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>Sửa mã {diet.code}</DialogTitle><DialogDescription>Cập nhật danh mục hoặc đổi trạng thái mà không xóa lịch sử.</DialogDescription></DialogHeader><div className="admin-detail"><form action={saveAction} className="admin-grid"><input type="hidden" name="dietTypeId" value={diet.id}/><label>Mã<input name="code" defaultValue={diet.code} required/></label><label>Tên<input name="name" defaultValue={diet.name} required/></label><label>Đường nuôi<select name="feedingRoute" defaultValue={diet.feedingRoute}><option value="NORMAL">Ăn thường</option><option value="SONDE">Sonde</option></select></label><label>Quy định<select name="dietCodeRefId" defaultValue={diet.dietCodeRefId}><option value="">—</option>{dietCodes.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>Thứ tự<input name="sortOrder" type="number" min="0" max="999" defaultValue={diet.sortOrder}/></label><button className="secondary-button">Lưu sửa đổi</button></form><form action={statusAction} className="status-form"><input type="hidden" name="dietTypeId" value={diet.id}/><input type="hidden" name="active" value={diet.status === "ACTIVE" ? "false" : "true"}/><input name="reason" minLength={3} maxLength={500} required placeholder="Lý do bắt buộc"/><button className={diet.status === "ACTIVE" ? "danger-button" : "secondary-button"}>{diet.status === "ACTIVE" ? "Vô hiệu hóa" : "Kích hoạt lại"}</button></form></div></DialogContent></Dialog>; } },
 ];
 return <DataTable columns={columns} data={data} getRowId={(row) => row.id} filterPlaceholder="Lọc mã, tên, đường nuôi…" emptyMessage="Chưa có mã chế độ ăn."/>;
}
