import { Separator } from "@/components/ui/separator";
import { redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/presentation";
import { getSessionUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { buildPublicPatientUrl, readOperationalSettings, visibleOperationalItems } from "@/lib/settings";
import { readBrandingSettings } from "@/lib/branding";
import { readPublicViewStats } from "@/lib/public-page-views";
import { accountStatusAction, departmentStatusAction, dietTypeStatusAction, mealTypeStatusAction, previewOfficialDataAction, queueOfficialDataAction, retryOfficialDataAction, saveAccountAction, saveBrandingAction, saveDepartmentAction, saveDietTypeAction, saveMealTypeAction, saveSettingsAction } from "./actions";
import { AccountCreateForm, SettingsForm } from "./admin-forms";
import { BrandingForm } from "./branding-form";
import { AccountTable } from "./account-table";
import { DietTypeTable } from "./diet-type-table";
import { MealTypeTable } from "./meal-type-table";
import { DepartmentTable } from "./department-table";
import { OfficialSyncStatus } from "./official-sync-status";
import { readSetupCompletion } from "@/lib/first-time-setup";
import { adminText } from "./i18n";

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ updated?: string; sync?: string; syncJob?: string }> }) {
  const user = await getSessionUser();
  if (!user) redirect("/");
  if (user.role !== "ADMIN") redirect("/");
  if (!await readSetupCompletion()) redirect("/thiet-lap-ban-dau");
  const [{ updated, sync, syncJob }, branding, settings, viewStats, mealTypes, users, departments, dietTypes, dietCodes] = await Promise.all([
    searchParams, readBrandingSettings(), readOperationalSettings(), readPublicViewStats(),
    prisma.mealType.findMany({ orderBy: [{ status: "asc" }, { sortOrder: "asc" }] }),
    prisma.user.findMany({ orderBy: [{ status: "asc" }, { displayName: "asc" }], include: { memberships: { include: { department: true } } } }),
    prisma.department.findMany({ orderBy: [{ status: "asc" }, { code: "asc" }] }),
    prisma.dietType.findMany({ orderBy: [{ status: "asc" }, { sortOrder: "asc" }], include: { dietCodeRef: true } }),
    prisma.dietCode.findMany({ orderBy: { code: "asc" }, select: { id: true, code: true, name: true } }),
  ]);
  const [syncPreview, syncJobs, activeSyncJob] = await Promise.all([
    sync ? prisma.dataSyncJob.findFirst({ where: { id: sync, requestedById: user.id, status: "PREVIEW" } }) : null,
    prisma.dataSyncJob.findMany({ orderBy: { createdAt: "desc" }, take: 8, include: { requestedBy: { select: { displayName: true } } } }),
    syncJob ? prisma.dataSyncJob.findFirst({ where: { id: syncJob, requestedById: user.id } }) : prisma.dataSyncJob.findFirst({ where: { requestedById: user.id, status: { in: ["QUEUED", "RUNNING"] } }, orderBy: { createdAt: "desc" } }),
  ]);
  const activeUsers = users.filter((account) => account.status === "ACTIVE").length;
  const activeDiets = dietTypes.filter((diet) => diet.status === "ACTIVE").length;
  const activeDepartments = departments.filter((department) => department.status === "ACTIVE");
  const operationalMealTypes = visibleOperationalItems(mealTypes, settings.sondeEnabled);
  const t = (text: string) => adminText(user.language, text);
  const roleLabel = { ADMIN: t("Quản trị"), DIETITIAN: t("Dinh dưỡng"), NURSE: t("Điều dưỡng"), KITCHEN: t("Nhà bếp") } as const;
  const accountRoleLabel = roleLabel;
  return <AppShell user={user}><main className="workspace admin-page admin-workspace"><Separator className="page-separator" aria-hidden="true"/>
    <PageHeader eyebrow={t("Trung tâm quản trị")} title={t("Thiết lập để hệ thống vận hành đúng")} description={t("Theo dõi cấu hình đang áp dụng, quản lý nhân sự và danh mục từ một nơi.")} actions={<div className="admin-header-actions"><a className="secondary-button" href="/api/setup/handoff/docx">{t("Hồ sơ bàn giao DOCX")}</a><a className="secondary-button" href="/api/setup/handoff/xlsx">{t("Danh sách IT XLSX")}</a><p className="scope-note">{t("Chỉ ADMIN · mọi thay đổi đều được truy vết")}</p></div>}/>
    {updated && adminText(user.language, updated) && <p className="success-banner" role="status">{adminText(user.language, updated)}</p>}
    <section className="admin-status-strip" aria-label={t("Trạng thái cấu hình")}><div><span>{t("Tài khoản hoạt động")}</span><strong className="tabular">{activeUsers}<small> / {users.length}</small></strong></div><div><span>{t("Khoa đang dùng")}</span><strong className="tabular">{activeDepartments.length}<small> / {departments.length}</small></strong></div><div><span>{t("Mã chế độ hoạt động")}</span><strong className="tabular">{activeDiets}<small> / {dietTypes.length}</small></strong></div><div><span>{t("Lượt xem hôm nay")}</span><strong className="tabular">{viewStats.today}</strong></div><div><span>{t("Tổng lượt xem")}</span><strong className="tabular">{viewStats.total}</strong></div><div><span>{t("Cửa sổ nhập liệu")}</span><strong className="tabular">{settings.advanceEntryDays}<small> {t("ngày")}</small></strong></div><div><span>{t("Đường nuôi Sonde")}</span><strong className={settings.sondeEnabled ? "status-on" : "status-off"}>{settings.sondeEnabled ? t("Đang bật") : t("Đang tắt")}</strong></div><div><span>{t("Mô hình kho")}</span><strong>{settings.warehouseMode === "A" ? t("Mode A") : t("Mode B")}</strong></div></section>
    <div className="admin-command-layout"><aside className="admin-context-rail"><p>{t("Đi tới")}</p><nav className="admin-section-nav" aria-label={t("Cài đặt vận hành")}><a href="#branding"><strong>{t("Nhận diện bệnh viện")}</strong><span>{t("Tên · logo · màu · ảnh nền bệnh nhân")}</span></a><a href="#settings"><strong>{t("Cài đặt vận hành")}</strong><span>{t("Giờ chốt, Sonde, kho")}</span></a><a href="#official-data"><strong>{t("Dữ liệu dinh dưỡng chính thức")}</strong><span>{t("VDD · RNI chính thức")}</span></a><a href="#departments"><strong>{t("Khoa điều trị")}</strong><span>{activeDepartments.length} {t("khoa")} {t("đang dùng")}</span></a><a href="#accounts"><strong>{t("Nhân sự")}</strong><span>{activeUsers} {t("tài khoản")} {t("hoạt động")}</span></a><a href="#diet-types"><strong>{t("Mã chế độ")}</strong><span>{activeDiets} {t("mã")} {t("đang dùng")}</span></a></nav><div className="admin-rail-links"><a href="/quan-ly">{t("Mở bàn điều phối")}</a><a href="/quan-tri/audit">{t("Xem nhật ký thay đổi")}</a></div></aside><div className="admin-command-content">
    <section id="branding" className="admin-panel branding-panel"><div className="section-heading"><div><p className="eyebrow">{t("Nhận diện bệnh viện")}</p><h2>{t("Thương hiệu và trang chủ công khai")}</h2></div><span>{t("Tên · logo · màu · ảnh nền bệnh nhân")}</span></div><BrandingForm branding={branding} action={saveBrandingAction}/></section>
    <section id="official-data" className="admin-panel official-data-panel"><div className="section-heading"><div><p className="eyebrow">{t("Dữ liệu dinh dưỡng chính thức")}</p><h2>{t("Cập nhật trực tiếp từ nguồn công bố")}</h2></div><span>{t("Xem trước · xác nhận · tác vụ nền · AuditLog")}</span></div>
      <div className="official-source-actions">{([["VDD_FOOD", t("Thực phẩm VDD")], ["VDD_DISH", t("Món ăn VDD")], ["RNI_DISH", t("Món dùng sẵn / RNI")]] as const).map(([source, label]) => <form action={previewOfficialDataAction} key={source}><input type="hidden" name="source" value={source}/><strong>{label}</strong><small>{t("Nguồn công bố chính thức")}</small><button className="secondary-button">{t("Kiểm tra nguồn & xem trước")}</button></form>)}</div>
      {syncPreview ? <div className="official-sync-preview"><div><strong>{t("Bản xem trước từ nguồn")}</strong><p>{t("Tổng số phía nguồn")}: {typeof syncPreview.previewJson === "object" && syncPreview.previewJson && "total" in syncPreview.previewJson ? String(syncPreview.previewJson.total) : "—"}</p><small>{t("Chưa có dữ liệu nào được ghi vào hệ thống.")}</small></div><form action={queueOfficialDataAction}><input type="hidden" name="jobId" value={syncPreview.id}/><label>{t("Lý do cập nhật")}<input name="reason" minLength={5} maxLength={500} required placeholder={t("Nêu lý do để lưu AuditLog…")}/></label><button className="primary-action">{t("Xác nhận đưa vào hàng đợi")}</button></form></div> : null}
      <OfficialSyncStatus job={activeSyncJob ? (() => { const preview = activeSyncJob.previewJson && typeof activeSyncJob.previewJson === "object" && !Array.isArray(activeSyncJob.previewJson) ? activeSyncJob.previewJson as { total?: unknown; samples?: unknown } : {}; return { id: activeSyncJob.id, source: activeSyncJob.source, status: activeSyncJob.status, processedCount: activeSyncJob.processedCount, createdCount: activeSyncJob.createdCount, updatedCount: activeSyncJob.updatedCount, errorMessage: activeSyncJob.errorMessage, total: typeof preview.total === "number" ? preview.total : null, samples: Array.isArray(preview.samples) ? preview.samples.filter((item): item is { code?: string; name?: string; energyKcal?: number | null } => Boolean(item) && typeof item === "object") : [] }; })() : null}/>
      <details className="official-sync-jobs"><summary>{t("Tác vụ gần đây")}</summary>{syncJobs.length ? <table><thead><tr><th>{t("Nguồn")}</th><th>{t("Trạng thái")}</th><th>{t("Đã xử lý")}</th><th>{t("Tạo mới / cập nhật")}</th><th>{t("Người yêu cầu")}</th><th>{t("Thao tác")}</th></tr></thead><tbody>{syncJobs.map((job) => <tr key={job.id}><td>{job.source}</td><td>{job.status}</td><td>{job.processedCount || "—"}</td><td>{job.createdCount || "—"} / {job.updatedCount || "—"}</td><td>{job.requestedBy.displayName}</td><td>{job.status === "FAILED" ? <form action={retryOfficialDataAction}><input type="hidden" name="jobId" value={job.id}/><button className="secondary-button">{t("Chạy lại")}</button></form> : "—"}</td></tr>)}</tbody></table> : <p>— · {t("Chưa có tác vụ đồng bộ.")}</p>}</details>
    </section>
    <section id="settings" className="admin-panel"><div className="section-heading"><div><p className="eyebrow">{t("Cài đặt vận hành")}</p><h2>{t("Áp dụng cho các luồng nghiệp vụ")}</h2></div><span>{t("Giờ chốt, Sonde, kho")}</span></div><SettingsForm settings={{ dataStartDate: settings.dataStartDate, advanceEntryDays: settings.advanceEntryDays, serviceCompletionMinutes: settings.serviceCompletionMinutes, publicMenuImages: settings.publicMenuImages, publicMenuDishes: settings.publicMenuDishes, publicMenuIngredients: settings.publicMenuIngredients, publicViewCountVisible: settings.publicViewCountVisible, foodRetention24hRequired: settings.foodRetention24hRequired, publicBaseUrl: settings.publicBaseUrl, feedbackDietitian: settings.patientSubmissionRecipients.feedback.dietitian, feedbackNurse: settings.patientSubmissionRecipients.feedback.nurse, kitchenNoteDietitian: settings.patientSubmissionRecipients.kitchenNote.dietitian, kitchenNoteNurse: settings.patientSubmissionRecipients.kitchenNote.nurse, sondeEnabled: settings.sondeEnabled, warehouseMode: settings.warehouseMode, warehouseApprovalRole: settings.warehouseApprovalRole as "ADMIN" | "DIETITIAN" | "KITCHEN" }} mealTypes={operationalMealTypes.filter((meal) => meal.status === "ACTIVE")} action={saveSettingsAction}/>
      <div className="admin-inline-create"><div><strong>{t("Thêm bữa ăn hoặc cữ Sonde")}</strong><small>{t("Mỗi đường nuôi có lịch và giờ nghiệp vụ riêng.")}</small></div><form action={saveMealTypeAction} className="admin-grid"><label>{t("Loại lịch")}<select name="feedingRoute"><option value="NORMAL">{t("Suất ăn thường")}</option><option value="SONDE">{t("Cữ Sonde")}</option></select></label><label>{t("Mã")}<input name="code" pattern="[A-Za-z0-9_-]{2,20}" autoComplete="off" spellCheck={false} required/></label><label>{t("Tên bữa/cữ")}<input name="name" autoComplete="off" required/></label><label>{t("Giờ chốt")}<input name="cutoffTime" type="time" required/></label><label>{t("Giờ phục vụ")}<input name="serviceTime" type="time" required/></label><label>{t("Thứ tự")}<input name="sortOrder" type="number" min="0" max="999" defaultValue={0} required/></label><button className="primary-action">{t("Thêm vào lịch")}</button></form></div>
      <MealTypeTable saveAction={saveMealTypeAction} statusAction={mealTypeStatusAction} data={operationalMealTypes.map((meal) => ({ id: meal.id, code: meal.code, name: meal.name, cutoffTime: meal.cutoffTime, serviceTime: meal.serviceTime, feedingRoute: meal.feedingRoute, routeLabel: meal.feedingRoute === "SONDE" ? t("Cữ Sonde") : t("Suất ăn thường"), sortOrder: meal.sortOrder, status: meal.status, statusLabel: meal.status === "ACTIVE" ? t("Đang dùng") : t("Đã vô hiệu") }))}/>
    </section>
    <section id="departments" className="admin-panel"><div className="section-heading"><div><p className="eyebrow">{t("Khoa điều trị")}</p><h2>{t("Danh mục khoa của bệnh viện")}</h2></div><span>{activeDepartments.length} {t("đang dùng")} · {departments.length - activeDepartments.length} {t("Đã vô hiệu")}</span></div>
      <div className="admin-inline-create"><div><strong>{t("Thêm khoa điều trị")}</strong><small>{t("Tạo đủ khoa thực tế của bệnh viện; không giới hạn ở Nội và Ngoại.")}</small></div><form action={saveDepartmentAction} className="admin-grid department-create"><label>{t("Mã khoa")}<input name="code" pattern="[A-Za-z0-9_-]{2,20}" autoComplete="off" spellCheck={false} required/></label><label>{t("Tên khoa")}<input name="name" autoComplete="off" required/></label><button className="primary-action">{t("Thêm khoa")}</button></form></div>
      <DepartmentTable saveAction={saveDepartmentAction} statusAction={departmentStatusAction} data={departments.map((department) => ({ id: department.id, code: department.code, name: department.name, status: department.status, statusLabel: department.status === "ACTIVE" ? t("Đang dùng") : t("Đã vô hiệu"), publicUrl: department.status === "ACTIVE" ? buildPublicPatientUrl(settings.publicBaseUrl, department.publicToken) : null }))}/>
    </section>
    <section id="accounts" className="admin-panel"><div className="section-heading"><div><p className="eyebrow">{t("Nhân sự & tài khoản")}</p><h2>{t("Danh sách người dùng")}</h2></div><span>{activeUsers} {t("hoạt động")} · {users.length - activeUsers} {t("Đã vô hiệu")}</span></div>
      <details className="admin-create-drawer"><summary><span><strong>{t("Tạo tài khoản mới")}</strong><small>{t("Chỉ mở biểu mẫu khi cần thêm nhân sự")}</small></span><em>{t("Mở biểu mẫu")}</em></summary><div className="admin-create-body"><AccountCreateForm departments={activeDepartments} action={saveAccountAction}/></div></details>
      <AccountTable language={user.language} departments={activeDepartments} saveAction={saveAccountAction} statusAction={accountStatusAction} data={users.map((account) => ({ id: account.id, name: account.displayName, email: account.email, role: account.role, roleLabel: user.language === "en" ? (accountRoleLabel[account.role]) : roleLabel[account.role], departmentId: account.memberships[0]?.departmentId ?? "", department: account.memberships[0]?.department.name ?? "—", kitchenRoute: account.kitchenRoute ?? "", kitchenScope: account.role === "KITCHEN" ? account.kitchenRoute === "SONDE" ? (user.language === "en" ? "Tube-feeding kitchen" : "Bếp Sonde") : (user.language === "en" ? "Regular-meal kitchen" : "Bếp ăn thường") : "—", status: account.status, statusLabel: account.status === "ACTIVE" ? (user.language === "en" ? "Active" : t("Đang hoạt động")) : (user.language === "en" ? "Inactive" : t("Đã vô hiệu")) }))}/>
    </section>
    <section id="diet-types" className="admin-panel"><div className="section-heading"><div><p className="eyebrow">{t("Mã chế độ / quy định")}</p><h2>{t("Danh mục chế độ ăn")}</h2></div><span>{t("Vô hiệu hóa, không xóa lịch sử")}</span></div>
      <details className="admin-create-drawer"><summary><span><strong>{t("Tạo mã chế độ mới")}</strong><small>{t("Thêm khi bệnh viện bắt đầu áp dụng một chế độ mới")}</small></span><em>{t("Mở biểu mẫu")}</em></summary><div className="admin-create-body"><form action={saveDietTypeAction} className="admin-grid diet-create"><label>{t("Mã")}<input name="code" pattern="[A-Za-z0-9_-]{2,20}" autoComplete="off" spellCheck={false} required/></label><label>{t("Tên chế độ")}<input name="name" autoComplete="off" required/></label><label>{t("Đường nuôi")}<select name="feedingRoute"><option value="NORMAL">{t("Ăn thường")}</option><option value="SONDE">{t("Sonde")}</option></select></label><label>{t("Quy định dinh dưỡng")}<select name="dietCodeRefId"><option value="">—</option>{dietCodes.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>{t("Thứ tự")}<input name="sortOrder" type="number" min="0" max="999" defaultValue={0} required/></label><button className="primary-action">{t("Tạo mã chế độ")}</button></form></div></details>
      <DietTypeTable dietCodes={dietCodes} saveAction={saveDietTypeAction} statusAction={dietTypeStatusAction} data={dietTypes.map((diet) => ({ id: diet.id, code: diet.code, name: diet.name, feedingRoute: diet.feedingRoute, routeLabel: diet.feedingRoute === "SONDE" ? t("Sonde") : t("Ăn thường"), dietCodeRefId: diet.dietCodeRefId ?? "", dietCode: diet.dietCodeRef?.code ?? "—", sortOrder: diet.sortOrder, status: diet.status, statusLabel: diet.status === "ACTIVE" ? t("Đang dùng") : t("Đã vô hiệu") }))}/>
    </section></div></div>
  </main></AppShell>;
}
