import { Separator } from "@/components/ui/separator";
import { redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/presentation";
import { getSessionUser } from "@/lib/auth";
import { getTranslations } from "@/lib/locale";
import { readLocale } from "@/lib/locale-server";
import { prisma } from "@/lib/prisma";
import { readOperationalSettings } from "@/lib/settings";
import { readBrandingSettings } from "@/lib/branding";
import { readPublicViewStats } from "@/lib/public-page-views";
import { accountStatusAction, departmentStatusAction, dietTypeStatusAction, mealTypeStatusAction, previewOfficialDataAction, queueOfficialDataAction, retryOfficialDataAction, saveAccountAction, saveBrandingAction, saveDepartmentAction, saveDietTypeAction, saveMealTypeAction, saveSettingsAction } from "./actions";
import { AccountCreateForm, SettingsForm } from "./admin-forms";
import { BrandingForm } from "./branding-form";
import { AccountTable } from "./account-table";
import { DietTypeTable } from "./diet-type-table";
import { MealTypeTable } from "./meal-type-table";
import { DepartmentTable } from "./department-table";
import { OfficialSyncStatus } from "./official-sync-status";

const dash = "-";

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ updated?: string; sync?: string; syncJob?: string }> }) {
  const user = await getSessionUser();
  if (!user) redirect("/");
  if (user.role !== "ADMIN") redirect("/");
  const locale = await readLocale();
  const t = getTranslations(locale).management.adminPage;
  const roleLabel = getTranslations(locale).role;
  const [{ updated, sync, syncJob }, branding, settings, viewStats, mealTypes, users, departments, dietTypes, dietCodes] = await Promise.all([
    searchParams, readBrandingSettings(), readOperationalSettings(), readPublicViewStats(),
    prisma.mealType.findMany({ orderBy: [{ status: "asc" }, { sortOrder: "asc" }] }),
    prisma.user.findMany({ orderBy: [{ status: "asc" }, { displayName: "asc" }], include: { memberships: { include: { department: true } } } }),
    prisma.department.findMany({ orderBy: [{ status: "asc" }, { code: "asc" }] }),
    prisma.dietType.findMany({ orderBy: [{ status: "asc" }, { sortOrder: "asc" }], include: { dietCodeRef: true } }),
    prisma.dietCode.findMany({ orderBy: { code: "asc" }, select: { id: true, code: true, name: true } }),
  ]);
  const [syncPreview, syncJobs, activeSyncJob] = await Promise.all([
    sync ? prisma.dataSyncJob.findFirst({ where: { id: sync, requestedById: user.id, status: "PREVIEW" } }) : null,
    prisma.dataSyncJob.findMany({ orderBy: { createdAt: "desc" }, take: 8, include: { requestedBy: { select: { displayName: true } } } }),
    syncJob ? prisma.dataSyncJob.findFirst({ where: { id: syncJob, requestedById: user.id } }) : prisma.dataSyncJob.findFirst({ where: { requestedById: user.id, status: { in: ["QUEUED", "RUNNING"] } }, orderBy: { createdAt: "desc" } }),
  ]);
  const activeUsers = users.filter((account) => account.status === "ACTIVE").length;
  const activeDiets = dietTypes.filter((diet) => diet.status === "ACTIVE").length;
  const activeDepartments = departments.filter((department) => department.status === "ACTIVE");
  const message = updated ? t.messages[updated as keyof typeof t.messages] : null;
  const statusLabel = (active: boolean) => active ? t.active : t.inactive;
  const activeStatus = (active: boolean) => active ? t.activeAccount : t.inactiveAccount;

  return <AppShell user={user}><main className="workspace admin-page admin-workspace"><Separator className="page-separator" aria-hidden="true"/>
    <PageHeader eyebrow={t.eyebrow} title={t.title} description={t.description} actions={<p className="scope-note">{t.adminOnly}</p>}/>
    {message ? <p className="success-banner" role="status">{message}</p> : null}
    <section className="admin-status-strip" aria-label={t.configStatusAria}><div><span>{t.activeAccounts}</span><strong className="tabular">{activeUsers}<small> / {users.length}</small></strong></div><div><span>{t.activeDepartments}</span><strong className="tabular">{activeDepartments.length}<small> / {departments.length}</small></strong></div><div><span>{t.activeDietCodes}</span><strong className="tabular">{activeDiets}<small> / {dietTypes.length}</small></strong></div><div><span>{t.viewsToday}</span><strong className="tabular">{viewStats.today}</strong></div><div><span>{t.viewsTotal}</span><strong className="tabular">{viewStats.total}</strong></div><div><span>{t.entryWindow}</span><strong className="tabular">{settings.advanceEntryDays}<small> {t.days}</small></strong></div><div><span>{t.sondeRoute}</span><strong className={settings.sondeEnabled ? "status-on" : "status-off"}>{settings.sondeEnabled ? t.on : t.off}</strong></div><div><span>{t.warehouseModel}</span><strong>Mode {settings.warehouseMode}</strong></div></section>
    <div className="admin-command-layout"><aside className="admin-context-rail"><p>{t.goTo}</p><nav className="admin-section-nav" aria-label={t.adminSectionsAria}><a href="#branding"><strong>{t.brandingNav}</strong><span>{t.brandingNavHelp}</span></a><a href="#settings"><strong>{t.settingsNav}</strong><span>{t.settingsNavHelp}</span></a><a href="#official-data"><strong>{t.officialDataNav}</strong><span>{t.officialDataNavHelp}</span></a><a href="#departments"><strong>{t.departmentsNav}</strong><span>{t.activeDepartmentCount.replace("{count}", String(activeDepartments.length))}</span></a><a href="#accounts"><strong>{t.staffNav}</strong><span>{t.activeAccountCount.replace("{count}", String(activeUsers))}</span></a><a href="#diet-types"><strong>{t.dietCodesNav}</strong><span>{t.activeDietCount.replace("{count}", String(activeDiets))}</span></a></nav><div className="admin-rail-links"><a href="/quan-ly">{t.openOperations}</a><a href="/quan-tri/audit">{t.viewAudit}</a></div></aside><div className="admin-command-content">
    <section id="branding" className="admin-panel branding-panel"><div className="section-heading"><div><p className="eyebrow">{t.brandingEyebrow}</p><h2>{t.brandingTitle}</h2></div><span>{t.brandingMeta}</span></div><BrandingForm branding={branding} action={saveBrandingAction}/></section>
    <section id="official-data" className="admin-panel official-data-panel"><div className="section-heading"><div><p className="eyebrow">{t.officialEyebrow}</p><h2>{t.officialTitle}</h2></div><span>{t.officialMeta}</span></div><div className="official-source-actions">{(["VDD_FOOD", "VDD_DISH", "RNI_DISH"] as const).map((source) => <form action={previewOfficialDataAction} key={source}><input type="hidden" name="source" value={source}/><strong>{t.source[source]}</strong><small>{t.officialSourceHelp}</small><button className="secondary-button">{t.previewSource}</button></form>)}</div>{syncPreview ? <div className="official-sync-preview"><div><strong>{t.previewTitle}</strong><p>{t.sourceTotal.replace("{total}", typeof syncPreview.previewJson === "object" && syncPreview.previewJson && "total" in syncPreview.previewJson ? String(syncPreview.previewJson.total) : dash)}</p><small>{t.previewSafe}</small></div><form action={queueOfficialDataAction}><input type="hidden" name="jobId" value={syncPreview.id}/><label>{t.updateReason}<input name="reason" minLength={5} maxLength={500} required placeholder={t.updateReasonPlaceholder}/></label><button className="primary-action">{t.queueSync}</button></form></div> : null}<OfficialSyncStatus job={activeSyncJob ? (() => { const preview = activeSyncJob.previewJson && typeof activeSyncJob.previewJson === "object" && !Array.isArray(activeSyncJob.previewJson) ? activeSyncJob.previewJson as { total?: unknown; samples?: unknown } : {}; return { id: activeSyncJob.id, source: activeSyncJob.source, status: activeSyncJob.status, processedCount: activeSyncJob.processedCount, createdCount: activeSyncJob.createdCount, updatedCount: activeSyncJob.updatedCount, errorMessage: activeSyncJob.errorMessage, total: typeof preview.total === "number" ? preview.total : null, samples: Array.isArray(preview.samples) ? preview.samples.filter((item): item is { code?: string; name?: string; energyKcal?: number | null } => Boolean(item) && typeof item === "object") : [] }; })() : null}/><details className="official-sync-jobs"><summary>{t.recentJobs}</summary>{syncJobs.length ? <table><thead><tr><th>{t.sourceHeader}</th><th>{t.statusHeader}</th><th>{t.processedHeader}</th><th>{t.createdUpdatedHeader}</th><th>{t.requestedByHeader}</th><th>{t.actionsHeader}</th></tr></thead><tbody>{syncJobs.map((job) => <tr key={job.id}><td>{job.source}</td><td>{job.status}</td><td>{job.processedCount || dash}</td><td>{job.createdCount || dash} / {job.updatedCount || dash}</td><td>{job.requestedBy.displayName}</td><td>{job.status === "FAILED" ? <form action={retryOfficialDataAction}><input type="hidden" name="jobId" value={job.id}/><button className="secondary-button">{t.retry}</button></form> : dash}</td></tr>)}</tbody></table> : <p>{t.noSyncJobs}</p>}</details></section>
    <section id="settings" className="admin-panel"><div className="section-heading"><div><p className="eyebrow">{t.settingsEyebrow}</p><h2>{t.settingsTitle}</h2></div><span>{t.settingsMeta}</span></div><SettingsForm settings={{ dataStartDate: settings.dataStartDate, advanceEntryDays: settings.advanceEntryDays, serviceCompletionMinutes: settings.serviceCompletionMinutes, publicMenuImages: settings.publicMenuImages, publicViewCountVisible: settings.publicViewCountVisible, foodRetention24hRequired: settings.foodRetention24hRequired, sondeEnabled: settings.sondeEnabled, warehouseMode: settings.warehouseMode, warehouseApprovalRole: settings.warehouseApprovalRole as "ADMIN" | "DIETITIAN" | "KITCHEN" }} mealTypes={mealTypes.filter((meal) => meal.status === "ACTIVE")} action={saveSettingsAction}/><div className="admin-inline-create"><div><strong>{t.addMealTitle}</strong><small>{t.addMealHelp}</small></div><form action={saveMealTypeAction} className="admin-grid"><label>{t.scheduleType}<select name="feedingRoute"><option value="NORMAL">{t.normalMeal}</option><option value="SONDE">{t.sondeMeal}</option></select></label><label>{t.code}<input name="code" pattern="[A-Za-z0-9_-]{2,20}" autoComplete="off" spellCheck={false} required/></label><label>{t.mealName}<input name="name" autoComplete="off" required/></label><label>{t.cutoffTime}<input name="cutoffTime" type="time" required/></label><label>{t.serviceTime}<input name="serviceTime" type="time" required/></label><label>{t.sortOrder}<input name="sortOrder" type="number" min="0" max="999" defaultValue="0" required/></label><button className="primary-action">{t.addToSchedule}</button></form></div><MealTypeTable saveAction={saveMealTypeAction} statusAction={mealTypeStatusAction} data={mealTypes.map((meal) => ({ id: meal.id, code: meal.code, name: meal.name, cutoffTime: meal.cutoffTime, serviceTime: meal.serviceTime, feedingRoute: meal.feedingRoute, routeLabel: meal.feedingRoute === "SONDE" ? t.sondeMeal : t.normalMeal, sortOrder: meal.sortOrder, status: meal.status, statusLabel: statusLabel(meal.status === "ACTIVE") }))}/></section>
    <section id="departments" className="admin-panel"><div className="section-heading"><div><p className="eyebrow">{t.departmentsEyebrow}</p><h2>{t.departmentsTitle}</h2></div><span>{t.activeInactive.replace("{active}", String(activeDepartments.length)).replace("{inactive}", String(departments.length - activeDepartments.length))}</span></div><div className="admin-inline-create"><div><strong>{t.addDepartmentTitle}</strong><small>{t.addDepartmentHelp}</small></div><form action={saveDepartmentAction} className="admin-grid department-create"><label>{t.departmentCode}<input name="code" pattern="[A-Za-z0-9_-]{2,20}" autoComplete="off" spellCheck={false} required/></label><label>{t.departmentName}<input name="name" autoComplete="off" required/></label><button className="primary-action">{t.addDepartment}</button></form></div><DepartmentTable saveAction={saveDepartmentAction} statusAction={departmentStatusAction} data={departments.map((department) => ({ id: department.id, code: department.code, name: department.name, status: department.status, statusLabel: statusLabel(department.status === "ACTIVE") }))}/></section>
    <section id="accounts" className="admin-panel"><div className="section-heading"><div><p className="eyebrow">{t.accountsEyebrow}</p><h2>{t.accountsTitle}</h2></div><span>{t.activeInactive.replace("{active}", String(activeUsers)).replace("{inactive}", String(users.length - activeUsers))}</span></div><details className="admin-create-drawer"><summary><span><strong>{t.createAccountTitle}</strong><small>{t.createAccountHelp}</small></span><em>{t.openForm}</em></summary><div className="admin-create-body"><AccountCreateForm departments={activeDepartments} action={saveAccountAction}/></div></details><AccountTable departments={activeDepartments} saveAction={saveAccountAction} statusAction={accountStatusAction} data={users.map((account) => ({ id: account.id, name: account.displayName, email: account.email, role: account.role, roleLabel: roleLabel[account.role], departmentId: account.memberships[0]?.departmentId ?? "", department: account.memberships[0]?.department.name ?? dash, kitchenRoute: account.kitchenRoute ?? "", kitchenScope: account.role === "KITCHEN" ? account.kitchenRoute === "SONDE" ? t.sondeKitchen : t.normalKitchen : dash, status: account.status, statusLabel: activeStatus(account.status === "ACTIVE") }))}/></section>
    <section id="diet-types" className="admin-panel"><div className="section-heading"><div><p className="eyebrow">{t.dietTypesEyebrow}</p><h2>{t.dietTypesTitle}</h2></div><span>{t.disableNoDelete}</span></div><details className="admin-create-drawer"><summary><span><strong>{t.createDietTitle}</strong><small>{t.createDietHelp}</small></span><em>{t.openForm}</em></summary><div className="admin-create-body"><form action={saveDietTypeAction} className="admin-grid diet-create"><label>{t.code}<input name="code" pattern="[A-Za-z0-9_-]{2,20}" autoComplete="off" spellCheck={false} required/></label><label>{t.dietName}<input name="name" autoComplete="off" required/></label><label>{t.feedingRoute}<select name="feedingRoute"><option value="NORMAL">{t.normalRoute}</option><option value="SONDE">Sonde</option></select></label><label>{t.nutritionRegulation}<select name="dietCodeRefId"><option value="">-</option>{dietCodes.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>{t.sortOrder}<input name="sortOrder" type="number" min="0" max="999" defaultValue="0" required/></label><button className="primary-action">{t.createDiet}</button></form></div></details><DietTypeTable dietCodes={dietCodes} saveAction={saveDietTypeAction} statusAction={dietTypeStatusAction} data={dietTypes.map((diet) => ({ id: diet.id, code: diet.code, name: diet.name, feedingRoute: diet.feedingRoute, routeLabel: diet.feedingRoute === "SONDE" ? "Sonde" : t.normalRoute, dietCodeRefId: diet.dietCodeRefId ?? "", dietCode: diet.dietCodeRef?.code ?? dash, sortOrder: diet.sortOrder, status: diet.status, statusLabel: statusLabel(diet.status === "ACTIVE") }))}/></section>
    </div></div>
  </main></AppShell>;
}
