"use client";

import { useEffect, useMemo, useState } from "react";
import { ChevronRight, Copy, EllipsisVertical, FolderOpen, Plus, Search, Trash2 } from "lucide-react";
import type { DietCodeThresholds } from "@suat-an/nutrition-engine";
import { ConfirmSubmitButton } from "./confirm-submit-button";
import { DietEvaluation } from "./diet-evaluation";
import { calculateMenuTotals, evaluateMenu, type MenuItemInput } from "@/lib/menu-logic";
import { MenuFoodSearch } from "./nutrition-2598/MenuFoodSearch";
import { dishToMenuItems, foodToMenuItem, type DishResult, type FoodResult } from "./nutrition-2598/types";

type Nutrients = MenuItemInput["nutrients"];
type SourceItem = { foodId: string | null; itemName: string; dishName?: string; category?: string; note?: string; grams: number; wastePercent: number | null; nutrients?: Nutrients };
type Source = { id: string; label: string; items: SourceItem[] };
type Context = { date: string; mealName: string; dietCode: string; dietName: string; servings: number };
const EMPTY_NUTRIENTS: Nutrients = { energyKcal: null, proteinG: null, lipidG: null, glucidG: null, sodiumMg: null, potassiumMg: null, waterG: null };
const number = new Intl.NumberFormat("vi-VN", { maximumFractionDigits: 1 });

function metric(value: number | null, unit: string) { return value === null ? "—" : `${number.format(value)} ${unit}`; }
function iconFor(name: string) { const value = name.toLowerCase(); if (value.includes("canh") || value.includes("súp")) return "🥣"; if (value.includes("rau")) return "🥬"; if (value.includes("cá")) return "🐟"; if (value.includes("cơm")) return "🍚"; if (value.includes("trứng")) return "🍳"; return "🍽️"; }

export function MenuEditor({ dietMeal, context, thresholds, templates, copies, approveAction, saveTemplateAction }: { dietMeal: { id: string; dietTypeId: string; feedingRoute: "NORMAL" | "SONDE"; approved?: boolean; existing: SourceItem[] }; context: Context; thresholds: DietCodeThresholds | null; templates: Source[]; copies: Source[]; approveAction: (data: FormData) => void; saveTemplateAction: (data: FormData) => void }) {
  const hydrate = (rows: SourceItem[]): MenuItemInput[] => rows.map((row) => ({ ...row, dishName: row.dishName || "Món 1", nutrients: row.nutrients ? { ...row.nutrients } : { ...EMPTY_NUTRIENTS } }));
  const [items, setItems] = useState<MenuItemInput[]>(() => hydrate(dietMeal.existing));
  const [activeDish, setActiveDish] = useState(() => dietMeal.existing[0]?.dishName || "Món 1");
  const [dishOrder, setDishOrder] = useState<string[]>(() => [...new Set(dietMeal.existing.map((item) => item.dishName || "Món 1"))]);
  const [searchKind, setSearchKind] = useState<"food" | "dish">("food");
  const [showManual, setShowManual] = useState(false);
  const [manualName, setManualName] = useState("");
  const [manualKcal, setManualKcal] = useState("");
  const [sourceTemplateId, setSourceTemplateId] = useState("");
  const [hydrated, setHydrated] = useState(false);
  const storageKey = `suat-an:menu-draft:${dietMeal.id}`;
  const dishes = useMemo(() => [...dishOrder, ...items.map((item) => item.dishName || "Món 1").filter((dish) => !dishOrder.includes(dish))], [dishOrder, items]);
  const totals = useMemo(() => calculateMenuTotals(items), [items]);
  const evaluation = useMemo(() => evaluateMenu(items, thresholds), [items, thresholds]);
  const activeItems = items.map((item, index) => ({ item, index })).filter(({ item }) => (item.dishName || "Món 1") === activeDish);
  const activeTotals = calculateMenuTotals(activeItems.map(({ item }) => item));
  const gramTotal = activeItems.reduce((sum, { item }) => sum + item.grams, 0);
  const counts = evaluation.criteria.reduce((result, criterion) => ({ ...result, [criterion.status]: result[criterion.status] + 1 }), { OK: 0, LOW: 0, HIGH: 0, MISSING: 0 });
  const encoded = JSON.stringify(items);

  useEffect(() => {
    if (dietMeal.approved) return;
    const timer = window.setTimeout(() => { try { const saved = window.localStorage.getItem(storageKey); if (saved) { const rows = JSON.parse(saved) as MenuItemInput[]; setItems(rows); setDishOrder([...new Set(rows.map((item) => item.dishName || "Món 1"))]); setActiveDish(rows[0]?.dishName || "Món 1"); } } catch { /* Bản nháp lỗi không làm sập editor. */ } setHydrated(true); }, 0);
    return () => window.clearTimeout(timer);
  }, [dietMeal.approved, storageKey]);
  useEffect(() => { if (hydrated && !dietMeal.approved) window.localStorage.setItem(storageKey, JSON.stringify(items)); }, [dietMeal.approved, hydrated, items, storageKey]);

  function loadSource(source: Source | undefined, template = false) { if (!source || dietMeal.approved) return; const next = hydrate(source.items); setItems(next); setDishOrder([...new Set(next.map((item) => item.dishName || "Món 1"))]); setActiveDish(next[0]?.dishName || "Món 1"); setSourceTemplateId(template ? source.id : ""); }
  function addDish(name = `Món ${dishes.length + 1}`) { if (dietMeal.approved) return; const unique = dishes.includes(name) ? `${name} (bản sao)` : name; setDishOrder((rows) => [...rows, unique]); setActiveDish(unique); }
  function renameDish(name: string) { const value = name.trim(); if (!value || value === activeDish || dietMeal.approved) return; setItems((rows) => rows.map((item) => (item.dishName || "Món 1") === activeDish ? { ...item, dishName: value } : item)); setDishOrder((rows) => rows.map((dish) => dish === activeDish ? value : dish)); setActiveDish(value); }
  function removeDish(name: string) { if (dietMeal.approved) return; setItems((rows) => rows.filter((item) => (item.dishName || "Món 1") !== name)); setDishOrder((rows) => rows.filter((dish) => dish !== name)); setActiveDish(dishes.find((dish) => dish !== name) || "Món 1"); }
  function duplicateDish(name: string) { const nextName = `${name} (bản sao)`; const rows = items.filter((item) => (item.dishName || "Món 1") === name).map((item) => ({ ...item, dishName: nextName, nutrients: { ...item.nutrients } })); setItems((current) => [...current, ...rows]); setDishOrder((current) => [...current, nextName]); setActiveDish(nextName); }
  function moveDish(direction: -1 | 1) { const index = dishes.indexOf(activeDish); const target = index + direction; if (index < 0 || target < 0 || target >= dishes.length) return; setDishOrder((current) => { const next = [...current]; [next[index], next[target]] = [next[target], next[index]]; return next; }); }
  function addFood(food: FoodResult) { if (!dietMeal.approved) setItems((rows) => [...rows, foodToMenuItem(food, activeDish || "Món 1")]); }
  function addDishRecipe(dish: DishResult) { if (dietMeal.approved) return; const recipeRows = dishToMenuItems(dish).map((item) => ({ ...item, note: item.note ?? `Từ công thức: ${dish.name}` })); setItems((rows) => [...rows.filter((row) => (row.dishName || "Món 1") !== dish.name), ...recipeRows]); setDishOrder((rows) => rows.includes(dish.name) ? rows : [...rows, dish.name]); setActiveDish(dish.name); }
  function addManualFood() { const name = manualName.trim(); const kcalValue = manualKcal.trim() === "" ? null : Number(manualKcal); if (!name || (kcalValue !== null && (!Number.isFinite(kcalValue) || kcalValue < 0))) return; setItems((rows) => [...rows, { foodId: null, itemName: name, dishName: activeDish || "Món 1", grams: 100, wastePercent: null, nutrients: { ...EMPTY_NUTRIENTS, energyKcal: kcalValue } }]); setManualName(""); setManualKcal(""); setShowManual(false); }

  return <form className="single-menu-workspace"><input type="hidden" name="dietMealId" value={dietMeal.id}/><input type="hidden" name="dietTypeId" value={dietMeal.dietTypeId}/><input type="hidden" name="feedingRoute" value={dietMeal.feedingRoute}/><input type="hidden" name="sourceTemplateId" value={sourceTemplateId}/><input type="hidden" name="items" value={encoded}/>
    <header className="single-context-workspace"><strong>{context.date} · {context.mealName} · {dietMeal.feedingRoute === "SONDE" ? "Nuôi qua sonde" : "Ăn đường miệng"} · <span>{context.dietCode}</span></strong><b>{dietMeal.approved ? "Đã khóa" : "Còn chỉnh sửa"}</b></header>
    {dietMeal.approved && <p className="snapshot-notice">Snapshot đã được đóng băng. Copy sang một bữa chưa khóa nếu cần chỉnh sửa.</p>}
    <div className="single-tools-workspace"><button type="button" className="active">Lập thực đơn</button><details><summary>Thông tin khuyến nghị ✓</summary><DietEvaluation criteria={evaluation.criteria}/></details><label><FolderOpen/> Thực đơn đã lưu<select defaultValue="" onChange={(event) => loadSource(templates.find((item) => item.id === event.target.value), true)} disabled={dietMeal.approved}><option value="">Chọn mẫu…</option>{templates.map((source) => <option key={source.id} value={source.id}>{source.label}</option>)}</select></label><button type="button" onClick={() => addDish()} disabled={dietMeal.approved}><Plus/> Món / Đồ ăn nhanh</button><button type="button" onClick={() => setShowManual(true)} disabled={dietMeal.approved}><Plus/> Thực phẩm mới</button><span>① Nhập thực đơn ── ② Phân tích &amp; báo cáo</span></div>
    <div className="single-layout-workspace"><aside className="dish-tree-workspace"><header><div><strong>{context.mealName} · {context.servings > 0 ? context.servings : "—"} suất</strong><small>{dishes.length || "—"} món</small></div><div><button type="button" aria-label="Đưa món lên" onClick={() => moveDish(-1)}>↑</button><button type="button" aria-label="Đưa món xuống" onClick={() => moveDish(1)}>↓</button><button type="button" onClick={() => addDish()} disabled={dietMeal.approved}>+ Thêm món</button><button type="button" aria-label="Nhân bản món" onClick={() => duplicateDish(activeDish)} disabled={dietMeal.approved}><Copy/></button><button type="button" aria-label="Xóa món" className="danger" onClick={() => removeDish(activeDish)} disabled={dietMeal.approved}><Trash2/></button></div></header><nav aria-label="Danh sách món">{dishes.map((dish) => { const dishItems = items.filter((item) => (item.dishName || "Món 1") === dish); const energy = calculateMenuTotals(dishItems).energyKcal; return <button type="button" key={dish} className={activeDish === dish ? "active" : ""} onClick={() => setActiveDish(dish)}><span>{iconFor(dish)}</span><strong>{dish}</strong><b>{energy === null ? "—" : number.format(energy)}</b><EllipsisVertical aria-hidden="true"/></button>; })}</nav>{!dishes.length && <p>Chưa có món — chọn “+ Thêm món” để bắt đầu.</p>}<label className="copy-source-workspace">Copy từ bữa khác<select defaultValue="" onChange={(event) => loadSource(copies.find((item) => item.id === event.target.value))} disabled={dietMeal.approved}><option value="">Chọn bữa…</option>{copies.map((source) => <option key={source.id} value={source.id}>{source.label}</option>)}</select></label></aside>
      <section className="ingredient-work-workspace"><header><div><p>{context.mealName} <ChevronRight/> {activeDish}</p><strong>{metric(activeTotals.energyKcal, "kcal")} · Đạm {metric(activeTotals.proteinG, "g")} · Béo {metric(activeTotals.lipidG, "g")} · Bột đường {metric(activeTotals.glucidG, "g")}</strong></div><div><b className="ok">Đạt {counts.OK}</b><b className="low">Thiếu {counts.LOW}</b><b className="high">Vượt {counts.HIGH}</b></div></header><div className="dish-name-workspace"><input aria-label="Tên món" value={activeDish} disabled={dietMeal.approved} onChange={(event) => { const value = event.target.value; setItems((rows) => rows.map((item) => (item.dishName || "Món 1") === activeDish ? { ...item, dishName: value } : item)); setDishOrder((rows) => rows.map((dish) => dish === activeDish ? value : dish)); setActiveDish(value); }} onBlur={(event) => renameDish(event.target.value)}/><span>Σ món <strong>{number.format(gramTotal)}</strong> g</span></div><div className="ingredient-table-workspace"><div className="ingredient-head-workspace"><span>Thực phẩm</span><span>Sống sạch (g)</span><span>Mua / kho (g)</span><span>Thải bỏ</span><span>Ghi chú</span><span/></div>{activeItems.map(({ item, index }) => <div className="ingredient-row-workspace" key={`${item.foodId ?? "manual"}-${index}`}><div><strong>{item.itemName}</strong><small>Tỷ lệ thải bỏ: {item.wastePercent === null ? "—" : `${number.format(item.wastePercent)}%`}</small></div><input aria-label={`Sống sạch ${item.itemName}`} type="number" min=".1" step=".1" value={item.grams} disabled={dietMeal.approved} onChange={(event) => setItems((rows) => rows.map((row, rowIndex) => rowIndex === index ? { ...row, grams: Number(event.target.value) } : row))}/><b>{item.wastePercent === null ? "—" : number.format(item.grams / (1 - item.wastePercent / 100))}</b><span>{item.wastePercent === null ? "—" : `${number.format(item.wastePercent)}%`}</span><input aria-label={`Ghi chú ${item.itemName}`} value={item.note ?? ""} placeholder="Ghi chú" disabled={dietMeal.approved} onChange={(event) => setItems((rows) => rows.map((row, rowIndex) => rowIndex === index ? { ...row, note: event.target.value } : row))}/><button type="button" aria-label={`Xóa ${item.itemName}`} disabled={dietMeal.approved} onClick={() => setItems((rows) => rows.filter((_, rowIndex) => rowIndex !== index))}>×</button></div>)}{!activeItems.length && <p className="empty-ingredient-workspace">Chưa có thực phẩm trong món này — dùng thanh tìm kiếm phía dưới để thêm.</p>}</div></section></div>
    <div className="single-command-workspace"><p>Đang thêm vào: <strong>{context.mealName} › {activeDish}</strong></p>{showManual && <div className="manual-workspace"><label>Tên thực phẩm<input value={manualName} onChange={(event) => setManualName(event.target.value)} autoFocus/></label><label>kcal / 100 g<input type="number" min="0" step=".1" value={manualKcal} onChange={(event) => setManualKcal(event.target.value)}/></label><button type="button" onClick={addManualFood}>Dùng một lần</button><button type="button" onClick={() => setShowManual(false)}>Đóng</button><small>Các chất không nhập sẽ giữ “—”; không ghi vào bảng Food.</small></div>}<div><button type="button">Bộ lọc</button><button type="button" className={searchKind === "food" ? "active" : ""} onClick={() => setSearchKind("food")}>Thực phẩm</button><button type="button" className={searchKind === "dish" ? "active" : ""} onClick={() => setSearchKind("dish")}>Món ăn</button><span className="single-search-workspace"><Search/><MenuFoodSearch kind={searchKind} onPickFood={addFood} onPickDish={addDishRecipe} placeholder="VD: cá chép, sữa chua; gõ không dấu được"/></span><button type="button" onClick={() => setShowManual((value) => !value)}>✏ Nhập tay</button><button type="button" disabled title="Sẽ kết nối sau">✨ AI · Dán mô tả / ảnh</button><a href="#single-analysis">Sang phân tích ›</a></div><small>Thực đơn đã lưu sẽ chuyển đến Báo suất · Bếp · Kho</small></div>
    <section id="single-analysis" className="single-analysis-workspace"><header><div><p className="eyebrow">Bước ②</p><h2>Phân tích &amp; báo cáo</h2></div><dl><div><dt>Năng lượng</dt><dd>{metric(totals.energyKcal, "kcal")}</dd></div><div><dt>Đạm</dt><dd>{metric(totals.proteinG, "g")}</dd></div><div><dt>Béo</dt><dd>{metric(totals.lipidG, "g")}</dd></div><div><dt>Bột đường</dt><dd>{metric(totals.glucidG, "g")}</dd></div></dl></header><DietEvaluation criteria={evaluation.criteria}/><div className="menu-actions"><div className="template-save"><input name="templateName" aria-label="Tên mẫu" placeholder="Tên mẫu cá nhân"/><button className="secondary-button" formAction={saveTemplateAction} disabled={dietMeal.approved || items.length === 0}>Lưu làm mẫu</button></div><ConfirmSubmitButton formAction={approveAction} title="Lưu thực đơn?" description="Có thể tiếp tục chỉnh sửa tới giờ hệ thống tự khóa." disabled={dietMeal.approved || items.length === 0}>Lưu thực đơn</ConfirmSubmitButton></div></section>
  </form>;
}
