"use client";

import { useEffect, useMemo, useState, type DragEvent } from "react";
import { BookOpen, Check, ClipboardCopy, FileDown, GripVertical, MoreVertical, Plus, Save, Search, Trash2 } from "lucide-react";
import type { DietCodeThresholds } from "@suat-an/nutrition-engine";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { MenuFoodSearch } from "./nutrition-2598/MenuFoodSearch";
import { dishToMenuItems, foodToMenuItem, type DishResult, type FoodResult } from "./nutrition-2598/types";
import { calculateMenuTotals, type MenuItemInput, type MenuNutrientKey } from "@/lib/menu-logic";
import { MenuExcelImportDialog } from "./menu-excel-import-dialog";

type Meal = { id: string; dietTypeId: string; code: string; name: string; approved: boolean; thresholds: DietCodeThresholds | null; items: MenuItemInput[] };
type Template = { id: string; name: string; dietTypeId: string | null; items: MenuItemInput[] };
type Context = { eventId: string; date: string; mealName: string; feedingRoute: "NORMAL" | "SONDE" };
type ActiveDish = { mealId: string; name: string };
const number = new Intl.NumberFormat("vi-VN", { maximumFractionDigits: 1 });
const nutrients: Array<{ key: MenuNutrientKey; label: string; unit: string; min: keyof DietCodeThresholds; max: keyof DietCodeThresholds }> = [
  { key: "proteinG", label: "Đạm", unit: "g", min: "proteinGMin", max: "proteinGMax" },
  { key: "lipidG", label: "Béo", unit: "g", min: "lipidGMin", max: "lipidGMax" },
  { key: "glucidG", label: "Bột đường", unit: "g", min: "glucidGMin", max: "glucidGMax" },
  { key: "sodiumMg", label: "Natri", unit: "mg", min: "sodiumMgMin", max: "sodiumMgMax" },
  { key: "potassiumMg", label: "Kali", unit: "mg", min: "potassiumMgMin", max: "potassiumMgMax" },
  { key: "waterG", label: "Nước", unit: "g", min: "waterGMin", max: "waterGMax" },
];
const emptyNutrients = { energyKcal: null, proteinG: null, lipidG: null, glucidG: null, sodiumMg: null, potassiumMg: null, waterG: null };

function clone(items: MenuItemInput[]) { return items.map((item) => ({ ...item, nutrients: { ...item.nutrients } })); }
function dishes(items: MenuItemInput[]) { return [...new Set(items.map((item) => item.dishName?.trim() || "Món 1"))]; }
function kcal(items: MenuItemInput[]) { if (!items.length) return "—"; const value = calculateMenuTotals(items).energyKcal; return value === null ? "—" : number.format(value); }
function portionNutrient(item: MenuItemInput, key: MenuNutrientKey) { const value = item.nutrients[key]; return value === null || !Number.isFinite(value) || !Number.isFinite(item.grams) ? "—" : number.format(value * item.grams / 100); }
function targetOf(thresholds: DietCodeThresholds | null, min: keyof DietCodeThresholds, max: keyof DietCodeThresholds) { if (!thresholds) return null; const high = thresholds[max]; const low = thresholds[min]; return typeof high === "number" ? high : typeof low === "number" ? low : null; }

function CodeActions({ meal, onChoose, onRecommendation, onClear, onSave }: { meal: Meal; onChoose: () => void; onRecommendation: () => void; onClear: () => void; onSave: () => void }) {
  return <DropdownMenu><DropdownMenuTrigger asChild><button type="button" className="nutrition-code-actions"><strong translate="no">{meal.code}</strong><span>{meal.name}</span><small>{meal.thresholds ? "Bấm để chọn hoặc xem khuyến nghị" : "Chưa gắn khuyến nghị"}</small></button></DropdownMenuTrigger><DropdownMenuContent align="start" className="nutrition-code-action-menu"><DropdownMenuItem onSelect={onChoose}><Search/> Chọn mã này để tìm kiếm</DropdownMenuItem><DropdownMenuItem onSelect={onRecommendation}><BookOpen/> Thông tin khuyến nghị</DropdownMenuItem><DropdownMenuItem disabled={meal.approved} onSelect={() => { if (window.confirm(`Xóa tất cả món của mã ${meal.code}?`)) onClear(); }}><Trash2/> Xóa tất cả món</DropdownMenuItem><DropdownMenuItem disabled={meal.approved} onSelect={onSave}><Save/> Lưu mã này</DropdownMenuItem></DropdownMenuContent></DropdownMenu>;
}

export function MultiCodeMenuBoard({ meals, templates, context, approveAction, saveTemplateAction }: { meals: Meal[]; templates: Template[]; context: Context; approveAction: (data: FormData) => void; saveTemplateAction: (data: FormData) => void }) {
  const legacyStorageKey = `suat-an:menu-drafts:${context.eventId}:${context.feedingRoute}`;
  const storageKey = `suat-an:menu-drafts:v2:${context.eventId}:${context.feedingRoute}`;
  const targetKey = `${storageKey}:kcal-targets`;
  const [step, setStep] = useState<"entry" | "analysis">("entry");
  const [menus, setMenus] = useState<Record<string, MenuItemInput[]>>(() => Object.fromEntries(meals.map((meal) => [meal.id, clone(meal.items)])));
  const [kcalTargets, setKcalTargets] = useState<Record<string, string>>({});
  const [activeId, setActiveId] = useState(meals.find((meal) => !meal.approved)?.id ?? meals[0]?.id ?? "");
  const [activeDish, setActiveDish] = useState<ActiveDish | null>(null);
  const [recommendationId, setRecommendationId] = useState<string | null>(null);
  const [searchKind, setSearchKind] = useState<"food" | "dish">("dish");
  const [dragged, setDragged] = useState<ActiveDish | null>(null);
  const [hydrated, setHydrated] = useState(false);
  const [importMessage, setImportMessage] = useState("");
  const active = meals.find((meal) => meal.id === activeId) ?? meals[0];
  const recommendationMeal = meals.find((meal) => meal.id === recommendationId) ?? null;

  useEffect(() => { const timer = window.setTimeout(() => { try { const saved = window.localStorage.getItem(storageKey); const targets = window.localStorage.getItem(targetKey); if (saved) setMenus((current) => ({ ...current, ...(JSON.parse(saved) as Record<string, MenuItemInput[]>) })); if (targets) setKcalTargets(JSON.parse(targets) as Record<string, string>); window.localStorage.removeItem(legacyStorageKey); window.localStorage.removeItem(`${legacyStorageKey}:kcal-targets`); } catch { window.localStorage.removeItem(storageKey); window.localStorage.removeItem(targetKey); } setHydrated(true); }, 0); return () => window.clearTimeout(timer); }, [legacyStorageKey, storageKey, targetKey]);
  useEffect(() => { if (hydrated) { window.localStorage.setItem(storageKey, JSON.stringify(menus)); window.localStorage.setItem(targetKey, JSON.stringify(kcalTargets)); } }, [hydrated, kcalTargets, menus, storageKey, targetKey]);

  const payload = JSON.stringify(meals.filter((meal) => !meal.approved && (menus[meal.id] ?? []).length).map((meal) => ({ dietMealId: meal.id, items: menus[meal.id] })));
  const ingredientMatrix = useMemo(() => {
    const rows = new Map<string, { name: string; values: Record<string, number> }>();
    for (const meal of meals) for (const item of menus[meal.id] ?? []) { const key = item.foodId ?? `name:${item.itemName.toLocaleLowerCase("vi")}`; const row = rows.get(key) ?? { name: item.itemName, values: {} }; row.values[meal.id] = (row.values[meal.id] ?? 0) + item.grams; rows.set(key, row); }
    return [...rows.values()].sort((a, b) => a.name.localeCompare(b.name, "vi"));
  }, [meals, menus]);

  function selectCode(meal: Meal) { setActiveId(meal.id); setSearchKind("dish"); }
  function addFood(food: FoodResult, target = activeDish) { const mealId = target?.mealId ?? active?.id; if (!mealId) return; const meal = meals.find((item) => item.id === mealId); if (meal?.approved) return; const dishName = target?.name ?? "Món mới"; setMenus((current) => ({ ...current, [mealId]: [...(current[mealId] ?? []), foodToMenuItem(food, dishName)] })); }
  function addDish(dish: DishResult) { if (!active || active.approved) return; const rows = dishToMenuItems(dish); setMenus((current) => ({ ...current, [active.id]: [...(current[active.id] ?? []), ...rows] })); setImportMessage(`Đã thêm món ${dish.name} vào mã ${active.code}.`); }
  function patchItem(mealId: string, index: number, patch: Partial<MenuItemInput>) { setMenus((current) => ({ ...current, [mealId]: (current[mealId] ?? []).map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) })); }
  function removeDish(mealId: string, dish: string) { setMenus((current) => ({ ...current, [mealId]: (current[mealId] ?? []).filter((item) => (item.dishName?.trim() || "Món 1") !== dish) })); setActiveDish(null); }
  function duplicateDish(mealId: string, dish: string) { const items = menus[mealId] ?? []; const base = `${dish} · bản sao`; let name = base; let suffix = 2; while (items.some((item) => item.dishName === name)) name = `${base} ${suffix++}`; const copies = items.filter((item) => (item.dishName?.trim() || "Món 1") === dish).map((item) => ({ ...item, dishName: name, nutrients: { ...item.nutrients } })); setMenus((current) => ({ ...current, [mealId]: [...(current[mealId] ?? []), ...copies] })); }
  function dropDish(targetMealId: string, targetDish?: string) { if (!dragged) return; setMenus((current) => { const sourceRows = (current[dragged.mealId] ?? []).filter((item) => (item.dishName?.trim() || "Món 1") === dragged.name); if (!sourceRows.length) return current; const next = { ...current }; if (dragged.mealId === targetMealId) next[dragged.mealId] = (current[dragged.mealId] ?? []).filter((item) => (item.dishName?.trim() || "Món 1") !== dragged.name); const target = [...(next[targetMealId] ?? [])]; const insertAt = targetDish ? target.findIndex((item) => (item.dishName?.trim() || "Món 1") === targetDish) : -1; const moved = sourceRows.map((item) => ({ ...item, nutrients: { ...item.nutrients } })); if (insertAt < 0) target.push(...moved); else target.splice(insertAt, 0, ...moved); next[targetMealId] = target; return next; }); setDragged(null); }
  function newDish() { if (!active || active.approved) return; const names = dishes(menus[active.id] ?? []); let name = "Món mới"; let index = 2; while (names.includes(name)) name = `Món mới ${index++}`; setActiveDish({ mealId: active.id, name }); setSearchKind("food"); }
  function applyTemplate(template: Template) { if (!active || active.approved) return; setMenus((current) => ({ ...current, [active.id]: clone(template.items) })); }
  function applyImportedRows(rows: Array<{ mealId: string; item: MenuItemInput }>) { setMenus((current) => { const next = { ...current }; for (const row of rows) next[row.mealId] = [...(next[row.mealId] ?? []), row.item]; return next; }); setImportMessage(`Đã thêm ${rows.length} hàng từ Excel vào bản nháp. Thực phẩm chưa liên kết giữ dinh dưỡng theo tệp hoặc “—”.`); }

  async function exportExcel() { const ExcelJS = await import("exceljs"); const workbook = new ExcelJS.Workbook(); const sheet = workbook.addWorksheet("Thực đơn"); sheet.addRow(["Ngày", "Bữa", "Mã", "Tên chế độ", "Món", "Thực phẩm", "Gram/suất"]); for (const meal of meals) for (const item of menus[meal.id] ?? []) sheet.addRow([context.date, context.mealName, meal.code, meal.name, item.dishName ?? "Món 1", item.itemName, item.grams]); sheet.columns.forEach((column) => { column.width = 22; }); const data = await workbook.xlsx.writeBuffer(); const url = URL.createObjectURL(new Blob([new Uint8Array(data)], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" })); const link = document.createElement("a"); link.href = url; link.download = `thuc-don-${context.date.replaceAll("/", "-")}-${context.mealName}.xlsx`; link.click(); URL.revokeObjectURL(url); }
  return <section className="nutrition-menu-workbench">
    <header className="nutrition-menu-context">
      <div className="nutrition-step-switch" role="tablist" aria-label="Hai bước nghiệp vụ"><button type="button" role="tab" aria-selected={step === "entry"} className={step === "entry" ? "active" : ""} onClick={() => setStep("entry")}>1 · Lên thực đơn</button><button type="button" role="tab" aria-selected={step === "analysis"} className={step === "analysis" ? "active" : ""} onClick={() => setStep("analysis")}>2 · Phân tích</button></div>
      <dl><div><dt>Ngày</dt><dd>{context.date}</dd></div><div><dt>Bữa</dt><dd>{context.mealName}</dd></div><div><dt>Số mã</dt><dd>{meals.length}</dd></div></dl>
      <div className="nutrition-context-tools"><MenuExcelImportDialog mealName={context.mealName} meals={meals.map(({ id, code, approved }) => ({ id, code, approved }))} onApply={applyImportedRows}/>
      <div className="nutrition-context-actions"><Dialog><DialogTrigger asChild><button type="button"><BookOpen/>Mẫu đã lưu</button></DialogTrigger><DialogContent className="max-h-[80vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>Mẫu thực đơn đã lưu</DialogTitle><DialogDescription>Chọn mẫu để áp dụng cho mã đang chỉnh: {active?.code ?? "—"}.</DialogDescription></DialogHeader><div className="nutrition-template-list">{templates.length ? templates.map((template) => <button type="button" key={template.id} onClick={() => applyTemplate(template)}><strong>{template.name}</strong><span>{template.items.length} thực phẩm</span></button>) : <p>— · Chưa có mẫu.</p>}</div></DialogContent></Dialog><Dialog><DialogTrigger asChild><button type="button"><Save/>Lưu mẫu bữa này</button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Lưu mã đang chỉnh làm mẫu</DialogTitle><DialogDescription>Mẫu lấy từ {active?.code ?? "—"}; dữ liệu nguồn không bị thay đổi.</DialogDescription></DialogHeader>{active ? <form action={saveTemplateAction} className="nutrition-save-template"><input type="hidden" name="dietMealId" value={active.id}/><input type="hidden" name="dietTypeId" value={active.dietTypeId}/><input type="hidden" name="feedingRoute" value={context.feedingRoute}/><input type="hidden" name="items" value={JSON.stringify(menus[active.id] ?? [])}/><label>Tên mẫu<input name="templateName" required minLength={2} maxLength={100}/></label><button className="primary-action">Lưu mẫu</button></form> : null}</DialogContent></Dialog></div></div>
    </header>

    {step === "entry" ? <div className="nutrition-code-canvas">{meals.map((meal) => { const items = menus[meal.id] ?? []; const dishNames = dishes(items); return <article className={`nutrition-code-row ${activeId === meal.id ? "active" : ""}`} key={meal.id} onDragOver={(event) => event.preventDefault()} onDrop={() => dropDish(meal.id)}><CodeActions meal={meal} onChoose={() => { selectCode(meal); window.setTimeout(() => document.querySelector<HTMLInputElement>(".nutrition-menu-command input")?.focus(), 0); }} onRecommendation={() => setRecommendationId(meal.id)} onClear={() => setMenus((current) => ({ ...current, [meal.id]: [] }))} onSave={() => { selectCode(meal); setImportMessage(`Đã lưu bản nháp mã ${meal.code} trên máy này.`); }}/>
      <header onClick={() => selectCode(meal)}><button type="button" className="nutrition-code-name" onClick={() => { selectCode(meal); setRecommendationId(meal.id); }}><strong translate="no">{meal.code}</strong><span>{meal.name}</span><small>{meal.thresholds ? "Xem khuyến nghị" : "Chưa gắn khuyến nghị"}</small></button><button type="button" className="icon-action" aria-label={`Sao chép toàn bộ mã ${meal.code}`} disabled={!items.length || meal.approved} onClick={(event) => { event.stopPropagation(); if (active && active.id !== meal.id) setMenus((current) => ({ ...current, [active.id]: clone(items) })); }}><ClipboardCopy/></button><label className="nutrition-kcal-target">kcal/suất<input type="number" min="1" step="1" placeholder="—" value={kcalTargets[meal.id] ?? ""} disabled={meal.approved} onClick={(event) => event.stopPropagation()} onChange={(event) => setKcalTargets((current) => ({ ...current, [meal.id]: event.target.value }))}/></label><span className="nutrition-kcal-actual">Thực tế {kcal(items)} kcal</span>{meal.approved ? <b className="approved"><Check/>Đã duyệt</b> : null}</header>
      <div className="nutrition-dish-strip">{dishNames.map((dish) => { const rows = items.filter((item) => (item.dishName?.trim() || "Món 1") === dish); return <article className="nutrition-dish-card" key={dish} draggable={!meal.approved} onDragStart={(event: DragEvent<HTMLElement>) => { event.dataTransfer.effectAllowed = dragged?.mealId === meal.id ? "move" : "copy"; setDragged({ mealId: meal.id, name: dish }); }} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.stopPropagation(); dropDish(meal.id, dish); }}><button type="button" className="nutrition-dish-main" onClick={() => { selectCode(meal); setActiveDish({ mealId: meal.id, name: dish }); setSearchKind("food"); }}><GripVertical/><strong>{dish}</strong><span>{kcal(rows)} kcal</span><small>{rows.length ? rows.map((item) => `${item.itemName} ${number.format(item.grams)}g`).join(" · ") : "Chưa có thực phẩm"}</small></button><DropdownMenu><DropdownMenuTrigger asChild><button type="button" className="dish-more" aria-label={`Thao tác món ${dish}`}><MoreVertical/></button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem onSelect={() => duplicateDish(meal.id, dish)}>Nhân đôi bên cạnh</DropdownMenuItem><DropdownMenuItem onSelect={() => removeDish(meal.id, dish)} disabled={meal.approved}>Xóa món</DropdownMenuItem></DropdownMenuContent></DropdownMenu></article>; })}<DropdownMenu><DropdownMenuTrigger asChild><button type="button" className="nutrition-add-dish" disabled={meal.approved} onClick={() => selectCode(meal)}><Plus/>Thêm món</button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem onSelect={newDish}>Tạo món trống rồi thêm thực phẩm</DropdownMenuItem><DropdownMenuItem onSelect={() => { setSearchKind("dish"); document.querySelector<HTMLInputElement>(".nutrition-menu-command input")?.focus(); }}>Tìm món có sẵn</DropdownMenuItem>{dishNames.length ? <DropdownMenuItem onSelect={() => duplicateDish(meal.id, dishNames[dishNames.length - 1])}>Nhân đôi món cuối</DropdownMenuItem> : null}</DropdownMenuContent></DropdownMenu></div>
    </article>; })}</div> : <div className="nutrition-analysis-panel">
      <header><div><h2>Phân tích bữa ăn theo một suất</h2><p>Không nhân số suất; dữ liệu thiếu giữ “—”.</p></div><div><button type="button" onClick={exportExcel}><FileDown/>Xuất Excel</button><button type="button" onClick={() => window.print()}><FileDown/>Xuất PDF</button></div></header>{importMessage ? <p className="nutrition-import-message" role="status">{importMessage}</p> : null}
      <section><h3>Nguyên liệu có trong bữa ăn · gram/1 suất</h3><div className="nutrition-matrix-scroll"><table><thead><tr><th>Thực phẩm</th>{meals.map((meal) => <th key={meal.id}>{meal.code}</th>)}<th>Tổng</th></tr></thead><tbody>{ingredientMatrix.map((row) => <tr key={row.name}><th>{row.name}</th>{meals.map((meal) => <td key={meal.id}>{row.values[meal.id] === undefined ? "—" : number.format(row.values[meal.id])}</td>)}<td>{number.format(Object.values(row.values).reduce((sum, value) => sum + value, 0))}</td></tr>)}</tbody></table></div></section>
      <section><h3>Mức đáp ứng khuyến nghị một ngày</h3><div className="nutrition-matrix-scroll"><table><thead><tr><th>Mã</th><th>Năng lượng thực tế</th><th>Mục tiêu NVDD</th><th>Đáp ứng</th>{nutrients.map((item) => <th key={item.key}>{item.label}</th>)}</tr></thead><tbody>{meals.map((meal) => { const mealItems = menus[meal.id] ?? []; const totals = mealItems.length ? calculateMenuTotals(mealItems) : null; const energyTarget = Number(kcalTargets[meal.id]) || null; return <tr key={meal.id}><th>{meal.code}</th><td>{totals?.energyKcal === null || totals?.energyKcal === undefined ? "—" : `${number.format(totals.energyKcal)} kcal`}</td><td>{energyTarget === null ? "—" : `${number.format(energyTarget)} kcal`}</td><td>{totals?.energyKcal === null || totals?.energyKcal === undefined || energyTarget === null ? "—" : `${number.format(totals.energyKcal / energyTarget * 100)}%`}</td>{nutrients.map((item) => { const actual = totals?.[item.key] ?? null; const target = targetOf(meal.thresholds, item.min, item.max); return <td key={item.key}>{actual === null || target === null ? "—" : `${number.format(actual / target * 100)}%`}</td>; })}</tr>; })}</tbody></table></div></section>
      <form action={approveAction} className="nutrition-analysis-actions"><input type="hidden" name="menus" value={payload}/><span>{meals.filter((meal) => !meal.approved && (menus[meal.id] ?? []).length).length} mã sẵn sàng gửi duyệt</span><button className="primary-action" disabled={payload === "[]"}>Duyệt thực đơn và chuyển bếp</button></form>
    </div>}

    {step === "entry" ? <footer className="nutrition-menu-command"><strong>Đang chỉnh: {active?.code ?? "—"}</strong><button type="button" className={searchKind === "dish" ? "active" : ""} onClick={() => setSearchKind("dish")}>Món ăn</button><button type="button" className={searchKind === "food" ? "active" : ""} onClick={() => setSearchKind("food")}>Thực phẩm</button><div className="nutrition-command-search"><Search/><MenuFoodSearch kind={searchKind} filterIconOnly onPickFood={(food) => addFood(food, null)} onPickDish={addDish} placeholder={searchKind === "dish" ? "Tìm món ăn cho mã đang chọn…" : "Tìm thực phẩm để thêm vào món…"}/></div><button type="button" className="primary-action" onClick={() => setStep("analysis")}>Chuyển sang phân tích</button></footer> : null}

    <Dialog open={Boolean(activeDish)} onOpenChange={(open) => { if (!open) setActiveDish(null); }}>{activeDish ? <DialogContent className="nutrition-dish-dialog max-h-[88vh] max-w-[min(96vw,1280px)] overflow-hidden"><DialogHeader><DialogTitle>{activeDish.name}</DialogTitle><DialogDescription>Thành phần và dinh dưỡng theo đúng gram của một suất; dữ liệu thiếu giữ “—”.</DialogDescription></DialogHeader><div className="nutrition-dish-table"><table><thead><tr><th>Thực phẩm</th><th>Gram sạch/suất</th><th>kcal</th><th>Đạm (g)</th><th>Béo (g)</th><th>Bột đường (g)</th><th>Thải bỏ</th><th>Ghi chú</th><th/></tr></thead><tbody>{(menus[activeDish.mealId] ?? []).map((item, index) => (item.dishName?.trim() || "Món 1") === activeDish.name ? <tr key={`${item.itemName}-${index}`}><td>{item.itemName}</td><td><input type="number" min="0.1" step="0.1" value={item.grams} onChange={(event) => patchItem(activeDish.mealId, index, { grams: Number(event.target.value) })}/></td><td>{portionNutrient(item, "energyKcal")}</td><td>{portionNutrient(item, "proteinG")}</td><td>{portionNutrient(item, "lipidG")}</td><td>{portionNutrient(item, "glucidG")}</td><td>{item.wastePercent === null ? "—" : `${number.format(item.wastePercent)}%`}</td><td><input value={item.note ?? ""} onChange={(event) => patchItem(activeDish.mealId, index, { note: event.target.value })}/></td><td><button type="button" aria-label={`Xóa ${item.itemName}`} onClick={() => setMenus((current) => ({ ...current, [activeDish.mealId]: (current[activeDish.mealId] ?? []).filter((_, itemIndex) => itemIndex !== index) }))}><Trash2/></button></td></tr> : null)}</tbody></table></div><div className="nutrition-dialog-search"><Search/><MenuFoodSearch kind="food" filterIconOnly onPickFood={(food) => addFood(food, activeDish)} placeholder="Tìm thực phẩm để thêm vào món này…"/></div></DialogContent> : null}</Dialog>
    <Dialog open={Boolean(recommendationMeal)} onOpenChange={(open) => { if (!open) setRecommendationId(null); }}>{recommendationMeal ? <DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>Khuyến nghị · {recommendationMeal.code}</DialogTitle><DialogDescription>Ngưỡng chuyên môn do Admin liên kết từ danh mục mã chế độ ăn; năng lượng do dinh dưỡng viên nhập tại hàng mã.</DialogDescription></DialogHeader><div className="nutrition-recommendation-grid"><div><span>Năng lượng NVDD</span><strong>{kcalTargets[recommendationMeal.id] ? `${kcalTargets[recommendationMeal.id]} kcal/suất` : "—"}</strong></div>{nutrients.map((item) => { const low = recommendationMeal.thresholds?.[item.min]; const high = recommendationMeal.thresholds?.[item.max]; return <div key={item.key}><span>{item.label}</span><strong>{typeof low !== "number" && typeof high !== "number" ? "—" : `${typeof low === "number" ? number.format(low) : "—"}–${typeof high === "number" ? number.format(high) : "—"} ${item.unit}`}</strong></div>; })}</div></DialogContent> : null}</Dialog>
  </section>;
}
