export type RecommendationRow = { id: string; ageGroup: string; gender: string; physicalActivity: string | null; [key: string]: unknown };
export type RecommendationInput = { gender: "Nam" | "Nữ"; physiology: "normal" | "pregnant_1" | "pregnant_2" | "pregnant_3" | "lactating_1" | "lactating_2"; ageYr: number; ageMonth: number; activityLevel: "sedentary" | "light" | "moderate" | "heavy" | "very_heavy" };
function ageRange(text: string) { const normalized = text.toLowerCase(); const values = normalized.match(/\d+(?:\.\d+)?/g)?.map(Number); if (!values?.length) return null; return { min: values[0]!, max: /\+|>=|trở lên/.test(normalized) ? 999 : values[1] ?? values[0]!, months: normalized.includes("tháng") }; }
export function findRecommendation(rows: RecommendationRow[], input: RecommendationInput): RecommendationRow | null {
  if (input.gender === "Nữ" && input.physiology !== "normal") { const term = input.physiology.startsWith("pregnant") ? "Phụ nữ có thai" : "Phụ nữ cho con bú"; return rows.find(row => row.ageGroup.startsWith(term)) ?? null; }
  const candidates = rows.filter(row => { if (row.gender !== input.gender || row.ageGroup.startsWith("Phụ nữ")) return false; const range = ageRange(row.ageGroup); const age = range?.months ? input.ageMonth : input.ageYr; return !!range && age >= range.min && age <= range.max; });
  const activity = input.activityLevel === "moderate" ? "Trung bình" : input.activityLevel === "heavy" || input.activityLevel === "very_heavy" ? "Nặng" : "Nhẹ";
  return candidates.find(row => row.physicalActivity === activity) ?? candidates[0] ?? null;
}
export function resolveRecommendationTarget(recommendation: RecommendationRow | null, base: RecommendationRow | null, field: string) { const raw = recommendation?.[field]; const value = typeof raw === "number" && Number.isFinite(raw) ? raw : null; const type = typeof recommendation?.[`${field}Type`] === "string" ? recommendation[`${field}Type`] as string : null; const isDelta = /\(\s*delta\s*\)/i.test(type ?? ""); const baseRaw = base?.[field]; const baseValue = typeof baseRaw === "number" && Number.isFinite(baseRaw) ? baseRaw : null; return { value: isDelta && value !== null && baseValue !== null ? value + baseValue : value, type, isDelta, baseValue: isDelta ? baseValue : null, deltaValue: isDelta ? value : null }; }
