import { redirect } from "next/navigation";
import { AccountCreateForm } from "../quan-tri/admin-forms";
import { AccountTable } from "../quan-tri/account-table";
import { DepartmentTable } from "../quan-tri/department-table";
import { DietTypeTable } from "../quan-tri/diet-type-table";
import { MealTypeTable } from "../quan-tri/meal-type-table";
import { readBootstrapState } from "@/lib/bootstrap-setup";
import { readBrandingSettings } from "@/lib/branding";
import { readSetupCompletion, readSetupInventory, validateSetupInventory } from "@/lib/first-time-setup";
import { prisma } from "@/lib/prisma";
import { readOperationalSettings } from "@/lib/settings";
import { confirmAdminAction, setupAccountAction, setupAccountStatusAction, setupBrandingAction, setupDepartmentAction, setupDepartmentStatusAction, setupDietTypeAction, setupDietTypeStatusAction, setupMealTypeAction, setupMealTypeStatusAction, setupRouteAction, unlockBootstrapAction } from "./actions";
import { CompleteSetupButton } from "./complete-setup-button";

export const dynamic = "force-dynamic";

const STEPS = ["Bệnh viện", "Admin đầu tiên", "Khoa/phòng", "Tài khoản", "Đường nuôi", "Chế độ ăn", "Bữa/cữ", "Kiểm tra"];
const roleLabel = { ADMIN: "Quản trị", DIETITIAN: "Dinh dưỡng", NURSE: "Điều dưỡng", KITCHEN: "Nhà bếp" } as const;

function Navigation({ step }: { step: number }) {
  return <div className="setup-navigation">{step > 1 ? <a className="secondary-button" href={`/thiet-lap-ban-dau?step=${step - 1}`}>← Quay lại</a> : <span/>}{step < 8 ? <a className="primary-action" href={`/thiet-lap-ban-dau?step=${step + 1}`}>Tiếp tục →</a> : null}</div>;
}

export default async function FirstTimeSetupPage({ searchParams }: { searchParams: Promise<{ step?: string; error?: string }> }) {
  if (await readSetupCompletion()) redirect("/");
  const query = await searchParams;
  const bootstrap = await readBootstrapState();
  if (!bootstrap) return <main className="setup-page"><section className="setup-card setup-unlock"><header><p>Khởi tạo server mới</p><h1>Khởi tạo hệ thống suất ăn bệnh viện</h1><span>Nhập mã khởi tạo do IT đặt trong biến môi trường máy chủ. Cổng này tự khóa sau khi hoàn tất.</span></header>{query.error ? <div className="setup-error" role="alert"><strong>Chưa thể bắt đầu</strong><span>{query.error}</span></div> : null}<form action={unlockBootstrapAction} className="setup-form"><label>Mã khởi tạo server<input name="setupToken" type="password" autoComplete="one-time-code" minLength={16} required/></label><button className="primary-action">Bắt đầu khởi tạo →</button></form></section></main>;
  const step = Math.min(8, Math.max(1, Number(query.step) || 1));
  if (step > 2 && !bootstrap.adminId) redirect("/thiet-lap-ban-dau?step=2");
  const [branding, settings, departments, users, dietTypes, dietCodes, mealTypes, inventory] = await Promise.all([
    readBrandingSettings(), readOperationalSettings(), prisma.department.findMany({ orderBy: { code: "asc" } }),
    prisma.user.findMany({ orderBy: { displayName: "asc" }, include: { memberships: { include: { department: true } } } }),
    prisma.dietType.findMany({ orderBy: [{ feedingRoute: "asc" }, { sortOrder: "asc" }], include: { dietCodeRef: { select: { id: true, code: true, name: true } } } }),
    prisma.dietCode.findMany({ orderBy: { code: "asc" }, select: { id: true, code: true, name: true } }),
    prisma.mealType.findMany({ orderBy: [{ feedingRoute: "asc" }, { sortOrder: "asc" }] }), readSetupInventory(bootstrap.adminId),
  ]);
  const issues = validateSetupInventory(inventory);
  const activeDepartments = departments.filter((item) => item.status === "ACTIVE");
  return <main className="setup-page">
    <header className="setup-header"><div className="setup-brand-mark">{branding.shortName}</div><div><p>Khởi tạo hệ thống</p><h1>{branding.organizationName}</h1><span>Hoàn thiện cấu hình trước khi mở hệ thống cho nhân viên và người bệnh.</span></div></header>
    <nav className="setup-stepper" aria-label="Các bước thiết lập">{STEPS.map((label, index) => <a key={label} href={`/thiet-lap-ban-dau?step=${index + 1}`} className={index + 1 === step ? "is-active" : index + 1 < step ? "is-done" : ""}><b>{index + 1}</b><span>{label}</span></a>)}</nav>
    {query.error ? <div className="setup-error" role="alert"><strong>Chưa thể lưu</strong><span>{query.error}</span></div> : null}
    <section className="setup-card">
      {step === 1 && <><header><p>Bước 1</p><h2>Thông tin bệnh viện</h2><span>Xác nhận tên và nhận diện dùng chung.</span></header><form action={setupBrandingAction} className="setup-form setup-branding-form"><label>Tên đơn vị/bệnh viện<input name="organizationName" defaultValue={branding.organizationName} minLength={2} maxLength={100} required/></label><label>Tên viết tắt<input name="shortName" defaultValue={branding.shortName} minLength={1} maxLength={5} required/></label><label>Màu nhận diện<input name="primaryColor" type="color" defaultValue={branding.primaryColor}/></label><button className="primary-action">Lưu và tiếp tục</button></form></>}
      {step === 2 && <><header><p>Bước 2</p><h2>Xác nhận Admin đầu tiên</h2><span>Dùng tài khoản bootstrap trên server; mật khẩu không đi vào hồ sơ bàn giao.</span></header>{bootstrap.adminId ? <div className="setup-checklist is-valid"><strong>✓ Đã xác nhận Admin</strong></div> : <form action={confirmAdminAction} className="setup-form"><label>Email Admin<input name="email" type="email" autoComplete="username" required/></label><label>Mật khẩu bootstrap<input name="password" type="password" autoComplete="current-password" minLength={10} required/></label><button className="primary-action">Xác nhận Admin →</button></form>}<Navigation step={step}/></>}
      {step === 3 && <><header><p>Bước 3</p><h2>Khoa/phòng</h2><span>Dữ liệu seed chỉ là gợi ý; Admin phải xác nhận danh mục thực tế.</span></header><form action={setupDepartmentAction} className="admin-grid department-create"><label>Mã khoa<input name="code" pattern="[A-Za-z0-9_-]{2,20}" required/></label><label>Tên khoa<input name="name" required/></label><button className="primary-action">Thêm khoa</button></form><DepartmentTable saveAction={setupDepartmentAction} statusAction={setupDepartmentStatusAction} data={departments.map((item) => ({ ...item, statusLabel: item.status === "ACTIVE" ? "Đang dùng" : "Đã vô hiệu" }))}/><Navigation step={step}/></>}
      {step === 4 && <><header><p>Bước 4</p><h2>Tài khoản và phân quyền</h2><span>Điều dưỡng gắn khoa; Bếp chọn đúng NORMAL hoặc Sonde. Mật khẩu tạm phải đổi ở lần đăng nhập đầu.</span></header><AccountCreateForm departments={activeDepartments} action={setupAccountAction}/><AccountTable departments={activeDepartments} saveAction={setupAccountAction} statusAction={setupAccountStatusAction} data={users.map((a) => ({ id: a.id, name: a.displayName, email: a.email, role: a.role, roleLabel: roleLabel[a.role], departmentId: a.memberships[0]?.departmentId ?? "", department: a.memberships[0]?.department.name ?? "—", kitchenRoute: a.kitchenRoute ?? "", kitchenScope: a.role === "KITCHEN" ? a.kitchenRoute === "SONDE" ? "Bếp Sonde" : "Bếp ăn thường" : "—", status: a.status, statusLabel: a.status === "ACTIVE" ? "Đang hoạt động" : "Đã vô hiệu" }))}/><Navigation step={step}/></>}
      {step === 5 && <><header><p>Bước 5</p><h2>Đường nuôi</h2><span>NORMAL luôn bật. Sonde có danh mục và lịch độc lập.</span></header><form action={setupRouteAction} className="setup-route-form"><div className="setup-route is-required"><strong>✓ Ăn thường (NORMAL)</strong><span>Luôn bật</span></div><label className="setup-route"><input type="checkbox" name="sondeEnabled" defaultChecked={settings.sondeEnabled}/><span><strong>Đường nuôi Sonde</strong><small>Bật khi bệnh viện vận hành Sonde.</small></span></label><button className="primary-action">Lưu và tiếp tục</button></form></>}
      {step === 6 && <><header><p>Bước 6</p><h2>Mã chế độ ăn</h2></header><form action={setupDietTypeAction} className="admin-grid diet-create"><label>Mã<input name="code" pattern="[A-Za-z0-9_-]{2,20}" required/></label><label>Tên chế độ<input name="name" required/></label><label>Đường nuôi<select name="feedingRoute"><option value="NORMAL">Ăn thường</option><option value="SONDE">Sonde</option></select></label><label>Quy định<select name="dietCodeRefId"><option value="">—</option>{dietCodes.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>Thứ tự<input name="sortOrder" type="number" min="0" max="999" defaultValue="0" required/></label><button className="primary-action">Thêm mã</button></form><DietTypeTable dietCodes={dietCodes} saveAction={setupDietTypeAction} statusAction={setupDietTypeStatusAction} data={dietTypes.map((item) => ({ id: item.id, code: item.code, name: item.name, feedingRoute: item.feedingRoute, routeLabel: item.feedingRoute === "SONDE" ? "Sonde" : "Ăn thường", dietCodeRefId: item.dietCodeRefId ?? "", dietCode: item.dietCodeRef?.code ?? "—", sortOrder: item.sortOrder, status: item.status, statusLabel: item.status === "ACTIVE" ? "Đang dùng" : "Đã vô hiệu" }))}/><Navigation step={step}/></>}
      {step === 7 && <><header><p>Bước 7</p><h2>Bữa ăn và cữ ăn</h2><span>Không hard-code số bữa; mỗi bữa phải có giờ chốt trước giờ phục vụ.</span></header><form action={setupMealTypeAction} className="admin-grid"><label>Đường nuôi<select name="feedingRoute"><option value="NORMAL">Ăn thường</option><option value="SONDE">Sonde</option></select></label><label>Mã<input name="code" pattern="[A-Za-z0-9_-]{2,20}" required/></label><label>Tên bữa/cữ<input name="name" required/></label><label>Giờ chốt<input name="cutoffTime" type="time" required/></label><label>Giờ phục vụ<input name="serviceTime" type="time" required/></label><label>Thứ tự<input name="sortOrder" type="number" min="0" max="999" defaultValue="0" required/></label><button className="primary-action">Thêm bữa/cữ</button></form><MealTypeTable saveAction={setupMealTypeAction} statusAction={setupMealTypeStatusAction} data={mealTypes.map((item) => ({ ...item, routeLabel: item.feedingRoute === "SONDE" ? "Cữ Sonde" : "Ăn thường", statusLabel: item.status === "ACTIVE" ? "Đang dùng" : "Đã vô hiệu" }))}/><Navigation step={step}/></>}
      {step === 8 && <><header><p>Bước 8</p><h2>Kiểm tra và hoàn tất</h2></header><div className="setup-summary"><article><span>Bệnh viện</span><strong>{branding.organizationName}</strong></article><article><span>Khoa</span><strong>{inventory.activeDepartments}</strong></article><article><span>Điều dưỡng có khoa</span><strong>{inventory.activeNursesWithDepartment}</strong></article><article><span>Bếp NORMAL / Sonde</span><strong>{inventory.activeKitchenByRoute.NORMAL} / {inventory.activeKitchenByRoute.SONDE}</strong></article><article><span>Mã ăn NORMAL / Sonde</span><strong>{inventory.activeDietTypesByRoute.NORMAL} / {inventory.activeDietTypesByRoute.SONDE}</strong></article><article><span>Bữa NORMAL / Sonde</span><strong>{inventory.activeMealTypesByRoute.NORMAL} / {inventory.activeMealTypesByRoute.SONDE}</strong></article></div>{issues.length ? <div className="setup-checklist is-invalid"><strong>Cần hoàn thiện {issues.length} mục</strong><ul>{issues.map((item) => <li key={item.code}>{item.message}</li>)}</ul></div> : <div className="setup-checklist is-valid"><strong>✓ Đủ điều kiện vận hành</strong><span>Hệ thống sẽ tạo lịch hiện tại và tải file mật khẩu tạm một lần. Hãy lưu file ở nơi an toàn.</span></div>}<div className="setup-navigation"><a className="secondary-button" href="/thiet-lap-ban-dau?step=7">← Quay lại</a><CompleteSetupButton disabled={issues.length > 0}/></div></>}
    </section>
  </main>;
}
