import { redirect } from "next/navigation";
import { AccountCreateForm } from "../quan-tri/admin-forms";
import { AccountTable } from "../quan-tri/account-table";
import { DepartmentTable } from "../quan-tri/department-table";
import { DietTypeTable } from "../quan-tri/diet-type-table";
import { MealTypeTable } from "../quan-tri/meal-type-table";
import { readBootstrapState } from "@/lib/bootstrap-setup";
import { readBrandingSettings } from "@/lib/branding";
import { readSetupCompletion, readSetupInventory, validateSetupInventory } from "@/lib/first-time-setup";
import { normalizeLanguage } from "@/lib/i18n";
import { prisma } from "@/lib/prisma";
import { readOperationalSettings } from "@/lib/settings";
import { confirmAdminAction, setupAccountAction, setupAccountCreateAction, setupAccountStatusAction, setupBrandingAction, setupDepartmentAction, setupDepartmentStatusAction, setupDietTypeAction, setupDietTypeStatusAction, setupMealTypeAction, setupMealTypeStatusAction, setupRouteAction, unlockBootstrapAction } from "./actions";
import { CompleteSetupButton } from "./complete-setup-button";

export const dynamic = "force-dynamic";

function HiddenLanguage({ language }: { language: "vi" | "en" }) { return <input type="hidden" name="language" value={language}/>; }
function Navigation({ step, language, back, next }: { step: number; language: "vi" | "en"; back: string; next: string }) {
  return <div className="setup-navigation">{step > 1 ? <a className="secondary-button" href={`/thiet-lap-ban-dau?step=${step - 1}&lang=${language}`}>← {back}</a> : <span/>}{step < 8 ? <a className="primary-action" href={`/thiet-lap-ban-dau?step=${step + 1}&lang=${language}`}>{next} →</a> : null}</div>;
}

export default async function FirstTimeSetupPage({ searchParams }: { searchParams: Promise<{ step?: string; error?: string; lang?: string }> }) {
  if (await readSetupCompletion()) redirect("/");
  const query = await searchParams;
  const language = normalizeLanguage(query.lang);
  const en = language === "en";
  const l = (vi: string, english: string) => en ? english : vi;
  const steps = en ? ["Hospital", "First admin", "Departments", "Accounts", "Feeding routes", "Diet codes", "Meals", "Review"] : ["Bệnh viện", "Admin đầu tiên", "Khoa/phòng", "Tài khoản", "Đường nuôi", "Chế độ ăn", "Bữa/cữ", "Kiểm tra"];
  const roleLabel = en ? { ADMIN: "Admin", DIETITIAN: "Dietitian", NURSE: "Nurse", KITCHEN: "Kitchen" } as const : { ADMIN: "Quản trị", DIETITIAN: "Dinh dưỡng", NURSE: "Điều dưỡng", KITCHEN: "Nhà bếp" } as const;
  const navigation = (step: number) => <Navigation step={step} language={language} back={l("Quay lại", "Back")} next={l("Tiếp tục", "Continue")}/>;
  const bootstrap = await readBootstrapState();
  if (!bootstrap) return <main className="setup-page"><section className="setup-card setup-unlock"><div className="setup-navigation"><span/><a className="secondary-button" href={`/thiet-lap-ban-dau?lang=${en ? "vi" : "en"}`}>{en ? "Tiếng Việt" : "English"}</a></div><header><p>{l("Khởi tạo server mới", "New server setup")}</p><h1>{l("Khởi tạo hệ thống suất ăn bệnh viện", "Set up the hospital meal service")}</h1><span>{l("Nhập mã khởi tạo do IT đặt trong biến môi trường máy chủ. Cổng này tự khóa sau khi hoàn tất.", "Enter the setup code configured by IT in the server environment. This portal locks automatically when setup is complete.")}</span></header>{query.error ? <div className="setup-error" role="alert"><strong>{l("Chưa thể bắt đầu", "Unable to start")}</strong><span>{query.error}</span></div> : null}<form action={unlockBootstrapAction} className="setup-form"><HiddenLanguage language={language}/><label>{l("Mã khởi tạo server", "Server setup code")}<input name="setupToken" type="password" autoComplete="one-time-code" minLength={16} required/></label><button className="primary-action">{l("Bắt đầu khởi tạo", "Start setup")} →</button></form></section></main>;
  const step = Math.min(8, Math.max(1, Number(query.step) || 1));
  if (step > 2 && !bootstrap.adminId) redirect(`/thiet-lap-ban-dau?step=2&lang=${language}`);
  const [branding, settings, departments, users, dietTypes, dietCodes, mealTypes, inventory] = await Promise.all([
    readBrandingSettings(), readOperationalSettings(), prisma.department.findMany({ orderBy: { code: "asc" } }),
    prisma.user.findMany({ orderBy: { displayName: "asc" }, include: { memberships: { include: { department: true } } } }),
    prisma.dietType.findMany({ orderBy: [{ feedingRoute: "asc" }, { sortOrder: "asc" }], include: { dietCodeRef: { select: { id: true, code: true, name: true } } } }),
    prisma.dietCode.findMany({ orderBy: { code: "asc" }, select: { id: true, code: true, name: true } }),
    prisma.mealType.findMany({ orderBy: [{ feedingRoute: "asc" }, { sortOrder: "asc" }] }), readSetupInventory(bootstrap.adminId),
  ]);
  const issues = validateSetupInventory(inventory);
  const activeDepartments = departments.filter((item) => item.status === "ACTIVE");
  const accountFeedbackAction = setupAccountCreateAction.bind(null, language);
  return <main className="setup-page">
    <header className="setup-header"><div className="setup-brand-mark">{branding.shortName}</div><div><p>{l("Khởi tạo hệ thống", "System setup")}</p><h1>{branding.organizationName}</h1><span>{l("Hoàn thiện cấu hình trước khi mở hệ thống cho nhân viên và người bệnh.", "Complete configuration before opening the system to staff and patients.")}</span></div><a className="secondary-button" href={`/thiet-lap-ban-dau?step=${step}&lang=${en ? "vi" : "en"}`}>{en ? "Tiếng Việt" : "English"}</a></header>
    <nav className="setup-stepper" aria-label={l("Các bước thiết lập", "Setup steps")}>{steps.map((label, index) => <a key={label} href={`/thiet-lap-ban-dau?step=${index + 1}&lang=${language}`} className={index + 1 === step ? "is-active" : index + 1 < step ? "is-done" : ""}><b>{index + 1}</b><span>{label}</span></a>)}</nav>
    {query.error ? <div className="setup-error" role="alert"><strong>{l("Chưa thể lưu", "Unable to save")}</strong><span>{query.error}</span></div> : null}
    <section className="setup-card">
      {step === 1 && <><header><p>{l("Bước 1", "Step 1")}</p><h2>{l("Thông tin bệnh viện", "Hospital information")}</h2><span>{l("Xác nhận tên và nhận diện dùng chung.", "Confirm the shared name and visual identity.")}</span></header><form action={setupBrandingAction} className="setup-form setup-branding-form"><HiddenLanguage language={language}/><label>{l("Tên đơn vị/bệnh viện", "Organization/hospital name")}<input name="organizationName" defaultValue={branding.organizationName} minLength={2} maxLength={100} required/></label><label>{l("Tên viết tắt", "Short name")}<input name="shortName" defaultValue={branding.shortName} minLength={1} maxLength={5} required/></label><label>{l("Màu nhận diện", "Brand color")}<input name="primaryColor" type="color" defaultValue={branding.primaryColor}/></label><button className="primary-action">{l("Lưu và tiếp tục", "Save and continue")}</button></form></>}
      {step === 2 && <><header><p>{l("Bước 2", "Step 2")}</p><h2>{l("Xác nhận Admin đầu tiên", "Confirm the first admin")}</h2><span>{l("Dùng tài khoản bootstrap trên server; mật khẩu không đi vào hồ sơ bàn giao.", "Use the server bootstrap account; its password is not included in handoff files.")}</span></header>{bootstrap.adminId ? <div className="setup-checklist is-valid"><strong>✓ {l("Đã xác nhận Admin", "Admin confirmed")}</strong></div> : <form action={confirmAdminAction} className="setup-form"><HiddenLanguage language={language}/><label>{l("Email Admin", "Admin email")}<input name="email" type="email" autoComplete="username" required/></label><label>{l("Mật khẩu bootstrap", "Bootstrap password")}<input name="password" type="password" autoComplete="current-password" minLength={10} required/></label><button className="primary-action">{l("Xác nhận Admin", "Confirm admin")} →</button></form>}{navigation(step)}</>}
      {step === 3 && <><header><p>{l("Bước 3", "Step 3")}</p><h2>{l("Khoa/phòng", "Departments")}</h2><span>{l("Dữ liệu seed chỉ là gợi ý; Admin phải xác nhận danh mục thực tế.", "Seed data is only a suggestion; the admin must confirm the actual list.")}</span></header><form action={setupDepartmentAction} className="admin-grid department-create"><HiddenLanguage language={language}/><label>{l("Mã khoa", "Department code")}<input name="code" pattern="[A-Za-z0-9_-]{2,20}" required/></label><label>{l("Tên khoa", "Department name")}<input name="name" required/></label><button className="primary-action">{l("Thêm khoa", "Add department")}</button></form><DepartmentTable saveAction={setupDepartmentAction} statusAction={setupDepartmentStatusAction} data={departments.map((item) => ({ ...item, statusLabel: item.status === "ACTIVE" ? l("Đang dùng", "Active") : l("Đã vô hiệu", "Inactive"), publicUrl: null }))}/>{navigation(step)}</>}
      {step === 4 && <><header><p>{l("Bước 4", "Step 4")}</p><h2>{l("Tài khoản và phân quyền", "Accounts and permissions")}</h2><span>{l("Điều dưỡng gắn khoa; Bếp chọn đúng NORMAL hoặc Sonde. Mật khẩu tạm phải đổi ở lần đăng nhập đầu.", "Assign nurses to departments and kitchen users to NORMAL or Sonde. Temporary passwords must be changed at first login.")}</span></header><AccountCreateForm departments={activeDepartments} feedbackAction={accountFeedbackAction}/><AccountTable language={language} departments={activeDepartments} saveAction={setupAccountAction} statusAction={setupAccountStatusAction} data={users.map((a) => ({ id: a.id, name: a.displayName, email: a.email, role: a.role, roleLabel: roleLabel[a.role], departmentId: a.memberships[0]?.departmentId ?? "", department: a.memberships[0]?.department.name ?? "—", kitchenRoute: a.kitchenRoute ?? "", kitchenScope: a.role === "KITCHEN" ? a.kitchenRoute === "SONDE" ? l("Bếp Sonde", "Tube kitchen") : l("Bếp ăn thường", "Oral kitchen") : "—", status: a.status, statusLabel: a.status === "ACTIVE" ? l("Đang hoạt động", "Active") : l("Đã vô hiệu", "Inactive") }))}/>{navigation(step)}</>}
      {step === 5 && <><header><p>{l("Bước 5", "Step 5")}</p><h2>{l("Đường nuôi", "Feeding routes")}</h2><span>{l("NORMAL luôn bật. Sonde có danh mục và lịch độc lập.", "NORMAL is always enabled. Sonde has an independent catalog and schedule.")}</span></header><form action={setupRouteAction} className="setup-route-form"><HiddenLanguage language={language}/><div className="setup-route is-required"><strong>✓ {l("Ăn thường (NORMAL)", "Oral feeding (NORMAL)")}</strong><span>{l("Luôn bật", "Always enabled")}</span></div><label className="setup-route"><input type="checkbox" name="sondeEnabled" defaultChecked={settings.sondeEnabled}/><span><strong>{l("Đường nuôi Sonde", "Tube feeding")}</strong><small>{l("Bật khi bệnh viện vận hành Sonde.", "Enable when the hospital provides tube feeding.")}</small></span></label><button className="primary-action">{l("Lưu và tiếp tục", "Save and continue")}</button></form></>}
      {step === 6 && <><header><p>{l("Bước 6", "Step 6")}</p><h2>{l("Mã chế độ ăn", "Diet codes")}</h2></header><form action={setupDietTypeAction} className="admin-grid diet-create"><HiddenLanguage language={language}/><label>{l("Mã", "Code")}<input name="code" pattern="[A-Za-z0-9_-]{2,20}" required/></label><label>{l("Tên chế độ", "Diet name")}<input name="name" required/></label><label>{l("Đường nuôi", "Feeding route")}<select name="feedingRoute"><option value="NORMAL">{l("Ăn thường", "Oral")}</option><option value="SONDE">Sonde</option></select></label><label>{l("Quy định", "Reference") }<select name="dietCodeRefId"><option value="">—</option>{dietCodes.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>{l("Thứ tự", "Order")}<input name="sortOrder" type="number" min="0" max="999" defaultValue="0" required/></label><button className="primary-action">{l("Thêm mã", "Add code")}</button></form><DietTypeTable dietCodes={dietCodes} saveAction={setupDietTypeAction} statusAction={setupDietTypeStatusAction} data={dietTypes.map((item) => ({ id: item.id, code: item.code, name: item.name, feedingRoute: item.feedingRoute, routeLabel: item.feedingRoute === "SONDE" ? "Sonde" : l("Ăn thường", "Oral"), dietCodeRefId: item.dietCodeRefId ?? "", dietCode: item.dietCodeRef?.code ?? "—", sortOrder: item.sortOrder, status: item.status, statusLabel: item.status === "ACTIVE" ? l("Đang dùng", "Active") : l("Đã vô hiệu", "Inactive") }))}/>{navigation(step)}</>}
      {step === 7 && <><header><p>{l("Bước 7", "Step 7")}</p><h2>{l("Bữa ăn và cữ ăn", "Meals and feeds")}</h2><span>{l("Không hard-code số bữa; mỗi bữa phải có giờ chốt trước giờ phục vụ.", "Meal count is configurable; each meal needs a cutoff before its service time.")}</span></header><form action={setupMealTypeAction} className="admin-grid"><HiddenLanguage language={language}/><label>{l("Đường nuôi", "Feeding route")}<select name="feedingRoute"><option value="NORMAL">{l("Ăn thường", "Oral")}</option><option value="SONDE">Sonde</option></select></label><label>{l("Mã", "Code")}<input name="code" pattern="[A-Za-z0-9_-]{2,20}" required/></label><label>{l("Tên bữa/cữ", "Meal/feed name")}<input name="name" required/></label><label>{l("Giờ chốt", "Cutoff time")}<input name="cutoffTime" type="time" required/></label><label>{l("Giờ phục vụ", "Service time")}<input name="serviceTime" type="time" required/></label><label>{l("Thứ tự", "Order")}<input name="sortOrder" type="number" min="0" max="999" defaultValue="0" required/></label><button className="primary-action">{l("Thêm bữa/cữ", "Add meal/feed")}</button></form><MealTypeTable saveAction={setupMealTypeAction} statusAction={setupMealTypeStatusAction} data={mealTypes.map((item) => ({ ...item, routeLabel: item.feedingRoute === "SONDE" ? l("Cữ Sonde", "Tube feed") : l("Ăn thường", "Oral"), statusLabel: item.status === "ACTIVE" ? l("Đang dùng", "Active") : l("Đã vô hiệu", "Inactive") }))}/>{navigation(step)}</>}
      {step === 8 && <><header><p>{l("Bước 8", "Step 8")}</p><h2>{l("Kiểm tra và hoàn tất", "Review and complete")}</h2></header><div className="setup-summary"><article><span>{l("Bệnh viện", "Hospital")}</span><strong>{branding.organizationName}</strong></article><article><span>{l("Khoa", "Departments")}</span><strong>{inventory.activeDepartments}</strong></article><article><span>{l("Điều dưỡng có khoa", "Nurses with departments")}</span><strong>{inventory.activeNursesWithDepartment}</strong></article><article><span>{l("Bếp NORMAL / Sonde", "NORMAL / Sonde kitchens")}</span><strong>{inventory.activeKitchenByRoute.NORMAL} / {inventory.activeKitchenByRoute.SONDE}</strong></article><article><span>{l("Mã ăn NORMAL / Sonde", "NORMAL / Sonde diet codes")}</span><strong>{inventory.activeDietTypesByRoute.NORMAL} / {inventory.activeDietTypesByRoute.SONDE}</strong></article><article><span>{l("Bữa NORMAL / Sonde", "NORMAL / Sonde meals")}</span><strong>{inventory.activeMealTypesByRoute.NORMAL} / {inventory.activeMealTypesByRoute.SONDE}</strong></article></div>{issues.length ? <div className="setup-checklist is-invalid"><strong>{l(`Cần hoàn thiện ${issues.length} mục`, `${issues.length} item${issues.length === 1 ? "" : "s"} need attention`)}</strong><ul>{issues.map((item) => <li key={item.code}>{en ? l("Cấu hình chưa đầy đủ.", "Configuration is incomplete.") : item.message}</li>)}</ul></div> : <div className="setup-checklist is-valid"><strong>✓ {l("Đủ điều kiện vận hành", "Ready for operation")}</strong><span>{l("Hệ thống sẽ tạo lịch hiện tại và tải file mật khẩu tạm một lần. Hãy lưu file ở nơi an toàn.", "The system will create the current schedule and download temporary passwords once. Store the file securely.")}</span></div>}<div className="setup-navigation"><a className="secondary-button" href={`/thiet-lap-ban-dau?step=7&lang=${language}`}>← {l("Quay lại", "Back")}</a><CompleteSetupButton disabled={issues.length > 0} language={language}/></div></>}
    </section>
  </main>;
}
