/* eslint-disable @next/next/no-img-element -- static DEMO bill assets are shown as fixed public thumbnails/previews */
import { Bot, FileText, PackageCheck, Plus, ReceiptText } from "lucide-react";
import { redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Separator } from "@/components/ui/separator";
import { getSessionUser } from "@/lib/auth";
import { readDemoSession } from "@/lib/demo-session";
import { getTranslations } from "@/lib/locale";
import { readLocale } from "@/lib/locale-server";
import { readRequestClock } from "@/lib/request-clock";
import { readWarehousePage } from "@/lib/warehouse";
import { saveInvoiceAction } from "./actions";

const localInput = (value: Date) => new Date(value.getTime() - value.getTimezoneOffset() * 60_000).toISOString().slice(0, 16);

export default async function WarehousePage({ searchParams }: { searchParams: Promise<{ updated?: string; storage?: string; demoNow?: string }> }) {
  const user = await getSessionUser();
  if (!user) redirect("/");
  if (!["ADMIN", "DIETITIAN", "KITCHEN"].includes(user.role)) redirect("/");
  const locale = await readLocale();
  const t = getTranslations(locale).management.warehousePage;
  const dateTime = new Intl.DateTimeFormat(locale === "en" ? "en-US" : "vi-VN", { timeZone: "Asia/Ho_Chi_Minh", dateStyle: "short", timeStyle: "short" });
  const currency = new Intl.NumberFormat(locale === "en" ? "en-US" : "vi-VN");
  const query = await searchParams;
  const clock = await readRequestClock(query.demoNow);
  const demo = await readDemoSession();
  const data = await readWarehousePage({ demoSessionId: demo?.id, date: clock.now, now: clock.now });
  const invoices = data.transactions.flatMap((transaction) => transaction.documents.filter((document) => document.kind === "INVOICE").map((document) => ({ id: document.id, occurredAt: transaction.occurredAt, warehouse: transaction.warehouse.name, creator: transaction.createdBy.displayName, note: document.note || transaction.note, active: transaction.status === "ACTIVE" })));
  const defaultWarehouse = data.warehouses[0] ?? null;
  const storageMessage = query.storage === "invalid" ? t.invalidStorage : query.storage === "unavailable" ? t.unavailableStorage : null;
  const upload = <Dialog><DialogTrigger asChild><button type="button" className="primary-action" disabled={!defaultWarehouse}><Plus/> {t.saveInvoice}</button></DialogTrigger><DialogContent className="max-h-[calc(100dvh-1rem)] max-w-xl overflow-y-auto sm:max-h-[92dvh]"><DialogHeader><DialogTitle>{t.dialogTitle}</DialogTitle><DialogDescription>{t.dialogDescription}</DialogDescription></DialogHeader>{defaultWarehouse ? <form action={saveInvoiceAction} className="invoice-save-form"><input type="hidden" name="warehouseId" value={defaultWarehouse.id}/><label>{t.invoiceDate}<input name="occurredAt" type="datetime-local" defaultValue={localInput(clock.now)} required/></label><label>{t.invoiceFile}<input name="file" type="file" accept="image/jpeg,image/jpg,image/png,image/webp,application/pdf" required/></label><label>{t.note}<input name="note" maxLength={500} placeholder={t.notePlaceholder}/></label><button className="primary-action"><ReceiptText/> {t.saveInvoice}</button></form> : <p className="storage-notice">{t.noWarehouse}</p>}</DialogContent></Dialog>;
  return <AppShell user={user} locale={locale} demoClock={clock.enabled ? { nowIso: clock.now.toISOString(), simulated: clock.simulated } : undefined}><main className="workspace warehouse-page invoice-archive"><Separator className="page-separator" aria-hidden="true"/><header className="invoice-toolbar"><div><p className="eyebrow">{t.eyebrow}</p><h1>{t.title}</h1><span>{t.subtitle}</span></div>{upload}</header>
    {query.updated === "invoice" ? <p className="success-banner" role="status">{t.invoiceSaved}</p> : null}
    {storageMessage ? <p className="storage-notice" role="alert">{storageMessage}</p> : null}
    {data.botEvents.length ? <section className="warehouse-bot-panel" aria-labelledby="warehouse-bot-title"><div className="section-heading"><div><p className="eyebrow">{t.warehouseBot.eyebrow}</p><h2 id="warehouse-bot-title"><Bot/> {t.warehouseBot.title}</h2></div><span>{t.warehouseBot.todayCount.replace("{count}", String(data.botEvents.length))}</span></div><div className="warehouse-bot-grid">{data.botEvents.map((event) => <article key={event.id} className={`warehouse-bot-card bot-${event.status.toLowerCase()}`}><img src={event.sample.imageUrl} alt={t.warehouseBot.invoiceAlt.replace("{invoice}", event.sample.invoiceNumber)} /><div><time dateTime={event.scheduledAt}>{dateTime.format(new Date(event.scheduledAt))}</time><strong>{event.sample.supplierName}</strong><span>{event.sample.invoiceNumber} · {event.lines.length} {t.warehouseBot.items}</span><b>{t.warehouseBot.status[event.status]}</b></div><Dialog><DialogTrigger asChild><button type="button" className="secondary-button">{t.warehouseBot.viewParsed}</button></DialogTrigger><DialogContent className="max-h-[92vh] max-w-6xl overflow-y-auto"><DialogHeader><DialogTitle>{event.sample.supplierName}</DialogTitle><DialogDescription>{event.sample.invoiceNumber} · {dateTime.format(new Date(event.scheduledAt))} · {t.warehouseBot.status[event.status]}</DialogDescription></DialogHeader><div className="warehouse-bot-detail"><img src={event.sample.imageUrl} alt={t.warehouseBot.invoiceAlt.replace("{invoice}", event.sample.invoiceNumber)} /><section><div className="warehouse-bot-summary"><span>{t.warehouseBot.invoiceDate}: {event.sample.invoiceDate}</span><span>{t.warehouseBot.total}: {currency.format(event.sample.total)}</span><span>{t.warehouseBot.processedAt}: {dateTime.format(new Date(event.processedAt))}</span></div><table><thead><tr><th>{t.warehouseBot.originalItem}</th><th>{t.warehouseBot.matchedItem}</th><th>{t.warehouseBot.quantity}</th><th>{t.warehouseBot.unitPrice}</th><th>{t.warehouseBot.lineTotal}</th></tr></thead><tbody>{event.lines.map((line) => <tr key={line.id}><td>{line.originalLabel}</td><td>{line.matchedFoodName ?? t.warehouseBot.unmatched}<small>{t.warehouseBot.matchSource[line.matchSource]}</small></td><td>{line.quantity} {line.unit}</td><td>{currency.format(line.unitPrice)}</td><td>{currency.format(line.total)}</td></tr>)}</tbody></table><div className="warehouse-bot-receipt"><PackageCheck/><div><strong>{event.stockReceipt ? t.warehouseBot.stockUpdated : t.warehouseBot.stockWaiting}</strong><span>{event.stockReceipt ? t.warehouseBot.receiptSummary.replace("{lines}", String(event.stockReceipt.lineCount)).replace("{quantity}", String(event.stockReceipt.totalQuantity)).replace("{value}", currency.format(event.stockReceipt.totalValue)) : t.warehouseBot.waitingHelp}</span></div></div></section></div></DialogContent></Dialog></article>)}</div></section> : null}
    {data.botStockBalances.length ? <section className="warehouse-bot-stock-panel" aria-labelledby="warehouse-bot-stock-title"><div className="section-heading"><div><p className="eyebrow">{t.warehouseBot.stockEyebrow}</p><h2 id="warehouse-bot-stock-title"><PackageCheck/> {t.warehouseBot.stockTitle}</h2></div><span>{t.warehouseBot.stockCount.replace("{count}", String(data.botStockBalances.length))}</span></div><div className="warehouse-bot-stock-grid">{data.botStockBalances.map((item) => <article key={`${item.foodId ?? item.itemName}-${item.unit}`}><strong>{item.itemName}</strong><span>{currency.format(item.quantity)} {item.unit}</span><small>{currency.format(item.value)}</small></article>)}</div></section> : null}
    <section className="invoice-list-panel"><div className="section-heading"><div><p className="eyebrow">{t.recent}</p><h2>{t.listTitle}</h2></div><span>{invoices.length ? t.invoiceCount.replace("{count}", String(invoices.length)) : "—"}</span></div>
      {invoices.length ? <div className="invoice-list" role="list">{invoices.map((invoice) => <article key={invoice.id} role="listitem"><FileText/><div><strong>{invoice.note || t.noInvoiceNote}</strong><span>{dateTime.format(invoice.occurredAt)} · {invoice.creator} · {invoice.warehouse}</span></div><a href={`/api/documents/${invoice.id}`} target="_blank" rel="noreferrer">{t.viewInvoice}</a></article>)}</div> : <div className="invoice-empty"><ReceiptText/><strong>{t.emptyTitle}</strong><span>{t.emptyDescription}</span></div>}
    </section>
  </main></AppShell>;
}
