import { redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { getSessionUser } from "@/lib/auth";
import { readWarehousePage } from "@/lib/warehouse";
import { cancelTransactionAction, updateTransactionAction, uploadDocumentAction } from "./actions";
import { QuickEntry } from "./quick-entry";

const number = new Intl.NumberFormat("vi-VN", { maximumFractionDigits: 3 });
const money = new Intl.NumberFormat("vi-VN", { maximumFractionDigits: 0 });
const dateTime = new Intl.DateTimeFormat("vi-VN", { timeZone: "Asia/Ho_Chi_Minh", dateStyle: "short", timeStyle: "short" });
const date = new Intl.DateTimeFormat("vi-VN", { timeZone: "Asia/Ho_Chi_Minh", day: "2-digit", month: "2-digit", year: "numeric" });
const typeLabel = { IN: "Nhập", OUT: "Xuất", ADJUST: "Điều chỉnh" } as const;
const documentLabel = { BILL: "Bill", INVOICE: "Hóa đơn", PHOTO: "Ảnh", OTHER: "Khác" } as const;
const localInput = (value: Date) => new Date(value.getTime() - value.getTimezoneOffset() * 60_000).toISOString().slice(0, 16);

export default async function WarehousePage({ searchParams }: { searchParams: Promise<{ updated?: string; storage?: string }> }) {
  const user = await getSessionUser();
  if (!user) redirect("/");
  if (!["ADMIN", "DIETITIAN", "KITCHEN"].includes(user.role)) redirect("/");
  const [data, query] = await Promise.all([readWarehousePage(), searchParams]);
  const comparisonMap = new Map(data.comparisons.map((item) => [item.transactionId, item]));
  const mealOptions = data.meals.map((meal) => ({ id: meal.id, feedingRoute: meal.feedingRoute, label: `${meal.mealEvent.mealType.name} ${date.format(meal.mealEvent.mealDate)} - ${meal.dietType.name}` }));
  const success = query.updated === "created" ? "Đã lưu giao dịch và nhật ký." : query.updated === "edited" ? "Đã cập nhật giao dịch và nhật ký." : query.updated === "cancelled" ? "Đã hủy giao dịch, dữ liệu lịch sử vẫn được giữ." : query.updated === "document" ? "Đã lưu chứng từ và nhật ký." : null;
  return <AppShell user={user}><main className="workspace warehouse-page">
    <header className="page-heading"><div><p className="eyebrow">Kho nguyên liệu</p><h1>Nhập, xuất và điều chỉnh</h1></div><p className="scope-note">Mode {data.mode}: {data.mode === "A" ? "một kho tổng" : "tách kho bếp và kho sonde theo đường nuôi"}</p></header>
    {success && <p className="success-banner" role="status">{success}</p>}
    {query.storage === "unavailable" && <p className="storage-notice" role="status">Chứng từ đang nằm im vì máy chủ chưa cấu hình nơi lưu. Giao dịch kho không bị thay đổi.</p>}
    {data.warehouses.length === 0 ? <section className="empty-state"><h2>—</h2><p>Chưa có kho hoạt động phù hợp với Mode {data.mode}. Cần cấu hình dữ liệu trước khi nhập.</p></section> : <section className="warehouse-entry" aria-labelledby="quick-entry-heading"><div className="section-heading"><div><p className="eyebrow">Nhập nhanh</p><h2 id="quick-entry-heading">Lưu trước, bổ sung sau</h2></div><span>AI đọc bill không bắt buộc</span></div><QuickEntry warehouses={data.warehouses} meals={mealOptions} defaultOccurredAt={localInput(new Date())}/></section>}
    <section className="warehouse-history" aria-labelledby="warehouse-history-heading"><div className="section-heading"><div><p className="eyebrow">Lịch sử</p><h2 id="warehouse-history-heading">Giao dịch gần đây</h2></div><span>{data.transactions.length ? `${data.transactions.length} giao dịch` : "—"}</span></div>
      {data.transactions.length === 0 ? <div className="panel-empty">—<span>Chưa có giao dịch kho.</span></div> : <div className="warehouse-transaction-list">{data.transactions.map((transaction) => { const comparison = comparisonMap.get(transaction.id); return <details key={transaction.id} className={`warehouse-transaction ${transaction.status === "CANCELLED" ? "cancelled" : ""}`}><summary><span className={`inventory-type inventory-${transaction.type.toLowerCase()}`}>{typeLabel[transaction.type]}</span><strong>{transaction.warehouse.name}</strong><span>{dateTime.format(transaction.occurredAt)}</span><span>{transaction.createdBy.displayName}</span><span className="tabular">{transaction.lines.length} dòng</span><span>{transaction.status === "CANCELLED" ? "Đã hủy" : "Đang hoạt động"}</span></summary><div className="transaction-detail">
          <form action={updateTransactionAction} className="transaction-edit"><input type="hidden" name="transactionId" value={transaction.id}/><div className="transaction-meta"><label>Thời điểm<input name="occurredAt" type="datetime-local" defaultValue={localInput(transaction.occurredAt)} required disabled={transaction.status !== "ACTIVE"}/></label><label>Ghi chú<input name="note" defaultValue={transaction.note ?? ""} maxLength={500} disabled={transaction.status !== "ACTIVE"}/></label></div><div className="warehouse-lines"><div className="warehouse-line warehouse-line-head"><span>Thực phẩm</span><span>Mã thực phẩm</span><span>Số lượng</span><span>Đơn vị</span><span>Đơn giá</span></div>{transaction.lines.map((line) => <div className="warehouse-line" key={line.id}><input type="hidden" name="lineId" value={line.id}/><input name="itemName" defaultValue={line.itemName} required disabled={transaction.status !== "ACTIVE"}/><input name="foodId" defaultValue={line.foodId ?? ""} disabled={transaction.status !== "ACTIVE"}/><input name="quantity" type="number" min="0.001" step="0.001" defaultValue={String(line.quantity)} required disabled={transaction.status !== "ACTIVE"}/><input name="unit" defaultValue={line.unit} required disabled={transaction.status !== "ACTIVE"}/><input name="unitPrice" type="number" min="0" step="0.01" defaultValue={line.unitPrice == null ? "" : String(line.unitPrice)} disabled={transaction.status !== "ACTIVE"}/></div>)}{transaction.status === "ACTIVE" && <div className="warehouse-line"><input type="hidden" name="lineId"/><input name="itemName" aria-label="Tên dòng bổ sung" placeholder="Thêm dòng nếu cần"/><input name="foodId" aria-label="Mã thực phẩm dòng bổ sung"/><input name="quantity" aria-label="Số lượng dòng bổ sung" type="number" min="0.001" step="0.001"/><input name="unit" aria-label="Đơn vị dòng bổ sung"/><input name="unitPrice" aria-label="Đơn giá dòng bổ sung" type="number" min="0" step="0.01"/></div>}</div>{transaction.status === "ACTIVE" && <button className="secondary-button">Lưu sửa đổi</button>}</form>
          {comparison && <section className="variance-panel" aria-label="Dự kiến và thực xuất"><h3>Dự kiến và thực xuất</h3><div className="variance-table"><div className="variance-head"><span>Thực phẩm</span><span>Dự kiến</span><span>Thực xuất</span><span>Chênh lệch</span></div>{comparison.lines.map((line) => <div key={line.id}><strong>{line.itemName}</strong><span>{line.expected == null ? "—" : `${number.format(line.expected)} g`}</span><span>{line.actual == null ? "—" : `${number.format(line.actual)} g`}</span><span className={line.variance == null ? "missing" : line.variance > 0 ? "variance-high" : line.variance < 0 ? "variance-low" : ""}>{line.variance == null ? "—" : `${line.variance > 0 ? "+" : ""}${number.format(line.variance)} g`}</span></div>)}</div>{comparison.warnings.length > 0 && <p className="data-warning" role="alert">Thiếu dữ liệu dự kiến: {comparison.warnings.join(" ")}</p>}</section>}
          <div className="transaction-support"><section><h3>Chứng từ</h3>{transaction.documents.length ? <p>{transaction.documents.map((document) => documentLabel[document.kind]).join(", ")}</p> : <p>—</p>}{transaction.status === "ACTIVE" && <form action={uploadDocumentAction} encType="multipart/form-data" className="document-form"><input type="hidden" name="transactionId" value={transaction.id}/><select name="kind" aria-label="Loại chứng từ"><option value="BILL">Bill</option><option value="INVOICE">Hóa đơn</option><option value="PHOTO">Ảnh</option><option value="OTHER">Khác</option></select><input name="file" type="file" accept="image/*" required/><input name="documentNote" maxLength={500} placeholder="Ghi chú"/><button className="secondary-button">Đính kèm</button></form>}</section>{transaction.status === "ACTIVE" && <section><h3>Hủy giao dịch</h3><form action={cancelTransactionAction} className="cancel-form"><input type="hidden" name="transactionId" value={transaction.id}/><input name="reason" minLength={3} maxLength={500} required placeholder="Lý do bắt buộc"/><button className="danger-button">Hủy, không xóa</button></form></section>}</div>
          {transaction.status === "CANCELLED" && <p className="cancel-reason">Lý do hủy: {transaction.voidedReason || "—"}</p>}
        </div></details>; })}</div>}
    </section>
  </main></AppShell>;
}
