"use client";
import type { ColumnDef } from "@tanstack/react-table";
import { DataTable } from "@/components/ui/data-table";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
type Action = (data: FormData) => Promise<void>;
type Line = { id: string; itemName: string; foodId: string; quantity: string; unit: string; unitPrice: string };
type Comparison = { lines: { id: string; itemName: string; expected: number | null; actual: number | null; variance: number | null }[]; warnings: string[] } | null;
export type WarehouseRow = { id: string; occurredAt: string; occurredAtInput: string; type: string; warehouse: string; creator: string; lineCount: number; status: "ACTIVE" | "CANCELLED"; statusLabel: string; note: string; lines: Line[]; documents: string[]; voidedReason: string; comparison: Comparison };
const dateTime = new Intl.DateTimeFormat("vi-VN", { timeZone: "Asia/Ho_Chi_Minh", dateStyle: "short", timeStyle: "short" });
const number = new Intl.NumberFormat("vi-VN", { maximumFractionDigits: 3 });
export function WarehouseTable({ data, updateAction, uploadAction, cancelAction }: { data: WarehouseRow[]; updateAction: Action; uploadAction: Action; cancelAction: Action }) {
 const columns: ColumnDef<WarehouseRow, unknown>[] = [
  { accessorKey: "occurredAt", header: "Thời điểm", cell: ({ row }) => <time dateTime={row.original.occurredAt} className="tabular-nums">{dateTime.format(new Date(row.original.occurredAt))}</time> }, { accessorKey: "type", header: "Loại" }, { accessorKey: "warehouse", header: "Kho" }, { accessorKey: "creator", header: "Người tạo" }, { accessorKey: "lineCount", header: "Số dòng", meta: { numeric: true } }, { accessorKey: "statusLabel", header: "Trạng thái" },
  { id: "actions", header: "Thao tác", enableSorting: false, cell: ({ row }) => { const transaction = row.original; const active = transaction.status === "ACTIVE"; return <Dialog><DialogTrigger asChild><button type="button" className="secondary-button">{active ? "Sửa" : "Xem"}</button></DialogTrigger><DialogContent className="max-h-[92vh] max-w-6xl overflow-y-auto"><DialogHeader><DialogTitle>{transaction.type} · {transaction.warehouse}</DialogTitle><DialogDescription>{dateTime.format(new Date(transaction.occurredAt))} · {transaction.creator} · {transaction.statusLabel}</DialogDescription></DialogHeader><div className="transaction-detail">
   <form action={updateAction} className="transaction-edit"><input type="hidden" name="transactionId" value={transaction.id}/><div className="transaction-meta"><label>Thời điểm<input name="occurredAt" type="datetime-local" defaultValue={transaction.occurredAtInput} required disabled={!active}/></label><label>Ghi chú<input name="note" defaultValue={transaction.note} maxLength={500} disabled={!active}/></label></div><div className="warehouse-lines"><div className="warehouse-line warehouse-line-head"><span>Thực phẩm</span><span>Mã thực phẩm</span><span>Số lượng</span><span>Đơn vị</span><span>Đơn giá</span></div>{transaction.lines.map((line) => <div className="warehouse-line" key={line.id}><input type="hidden" name="lineId" value={line.id}/><input name="itemName" defaultValue={line.itemName} required disabled={!active}/><input name="foodId" defaultValue={line.foodId} disabled={!active}/><input name="quantity" type="number" min="0.001" step="0.001" defaultValue={line.quantity} required disabled={!active}/><input name="unit" defaultValue={line.unit} required disabled={!active}/><input name="unitPrice" type="number" min="0" step="0.01" defaultValue={line.unitPrice} disabled={!active}/></div>)}{active && <div className="warehouse-line"><input type="hidden" name="lineId"/><input name="itemName" aria-label="Tên dòng bổ sung" placeholder="Thêm dòng nếu cần"/><input name="foodId" aria-label="Mã thực phẩm dòng bổ sung"/><input name="quantity" aria-label="Số lượng dòng bổ sung" type="number" min="0.001" step="0.001"/><input name="unit" aria-label="Đơn vị dòng bổ sung"/><input name="unitPrice" aria-label="Đơn giá dòng bổ sung" type="number" min="0" step="0.01"/></div>}</div>{active && <button className="secondary-button">Lưu sửa đổi</button>}</form>
   {transaction.comparison && <section className="variance-panel" aria-label="Dự kiến và thực xuất"><h3>Dự kiến và thực xuất</h3><div className="variance-table"><div className="variance-head"><span>Thực phẩm</span><span>Dự kiến</span><span>Thực xuất</span><span>Chênh lệch</span></div>{transaction.comparison.lines.map((line) => <div key={line.id}><strong>{line.itemName}</strong><span>{line.expected == null ? "—" : `${number.format(line.expected)} g`}</span><span>{line.actual == null ? "—" : `${number.format(line.actual)} g`}</span><span className={line.variance == null ? "missing" : line.variance > 0 ? "variance-high" : line.variance < 0 ? "variance-low" : ""}>{line.variance == null ? "—" : `${line.variance > 0 ? "+" : ""}${number.format(line.variance)} g`}</span></div>)}</div>{transaction.comparison.warnings.length > 0 && <p className="data-warning" role="alert">Thiếu dữ liệu dự kiến: {transaction.comparison.warnings.join(" ")}</p>}</section>}
   <div className="transaction-support"><section><h3>Chứng từ</h3><p>{transaction.documents.length ? transaction.documents.join(", ") : "—"}</p>{active && <form action={uploadAction} encType="multipart/form-data" className="document-form"><input type="hidden" name="transactionId" value={transaction.id}/><select name="kind" aria-label="Loại chứng từ"><option value="BILL">Bill</option><option value="INVOICE">Hóa đơn</option><option value="PHOTO">Ảnh</option><option value="OTHER">Khác</option></select><input name="file" type="file" accept="image/*" required/><input name="documentNote" maxLength={500} placeholder="Ghi chú"/><button className="secondary-button">Đính kèm</button></form>}</section>{active && <section><h3>Hủy giao dịch</h3><form action={cancelAction} className="cancel-form"><input type="hidden" name="transactionId" value={transaction.id}/><input name="reason" minLength={3} maxLength={500} required placeholder="Lý do bắt buộc"/><button className="danger-button">Hủy, không xóa</button></form></section>}</div>{!active && <p className="cancel-reason">Lý do hủy: {transaction.voidedReason || "—"}</p>}
  </div></DialogContent></Dialog>; } },
 ];
 return <DataTable columns={columns} data={data} getRowId={(row) => row.id} filterPlaceholder="Lọc kho, loại, người tạo…" emptyMessage="Chưa có giao dịch kho."/>;
}
