"use client";
import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { PanelLeft } from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent } from "@/components/ui/sheet";

type SidebarContextValue = { open: boolean; setOpen: (open: boolean) => void; openMobile: boolean; setOpenMobile: (open: boolean) => void; toggleSidebar: () => void };
const SidebarContext = React.createContext<SidebarContextValue | null>(null);
function useSidebar() { const context = React.useContext(SidebarContext); if (!context) throw new Error("useSidebar must be used within SidebarProvider"); return context; }
function SidebarProvider({ defaultOpen = true, open: openProp, onOpenChange, className, style, children, ...props }: React.ComponentProps<"div"> & { defaultOpen?: boolean; open?: boolean; onOpenChange?: (open: boolean) => void }) { const [_open, _setOpen] = React.useState(defaultOpen); const [openMobile, setOpenMobile] = React.useState(false); const open = openProp ?? _open; const setOpen = React.useCallback((value: boolean) => { onOpenChange?.(value); if (!onOpenChange) _setOpen(value); }, [onOpenChange]); const toggleSidebar = React.useCallback(() => setOpen(!open), [open, setOpen]); return <SidebarContext.Provider value={{ open, setOpen, openMobile, setOpenMobile, toggleSidebar }}><div style={{ "--sidebar-width": "16rem", ...style } as React.CSSProperties} className={cn("group/sidebar-wrapper flex min-h-svh w-full", className)} {...props}>{children}</div></SidebarContext.Provider>; }
function Sidebar({ side = "left", className, children, ...props }: React.ComponentProps<"div"> & { side?: "left" | "right" }) { const { open, openMobile, setOpenMobile } = useSidebar(); return <><Sheet open={openMobile} onOpenChange={setOpenMobile}><SheetContent side={side} className="w-[var(--sidebar-width)] bg-sidebar p-0 text-sidebar-foreground [&>button]:hidden">{children}</SheetContent></Sheet><div data-state={open ? "expanded" : "collapsed"} data-side={side} className={cn("hidden h-svh w-[var(--sidebar-width)] shrink-0 flex-col bg-sidebar text-sidebar-foreground transition-[width] lg:fixed lg:inset-y-0 lg:left-0 lg:z-30 lg:flex", !open && "w-0 overflow-hidden", className)} {...props}>{children}</div></>; }
function SidebarTrigger({ className, onClick, ...props }: React.ComponentProps<typeof Button>) { const { toggleSidebar } = useSidebar(); return <Button variant="ghost" size="icon" className={cn("size-9", className)} onClick={(event) => { onClick?.(event); toggleSidebar(); }} {...props}><PanelLeft /><span className="sr-only">Mở hoặc đóng thanh bên</span></Button>; }
function SidebarInset({ className, ...props }: React.ComponentProps<"main">) { return <main className={cn("relative flex min-w-0 flex-1 flex-col bg-background lg:ml-[var(--sidebar-width)]", className)} {...props} />; }
function SidebarHeader({ className, ...props }: React.ComponentProps<"div">) { return <div className={cn("flex flex-col gap-2 p-2", className)} {...props} />; }
function SidebarFooter({ className, ...props }: React.ComponentProps<"div">) { return <div className={cn("mt-auto flex flex-col gap-2 p-2", className)} {...props} />; }
function SidebarContent({ className, ...props }: React.ComponentProps<"div">) { return <div className={cn("flex min-h-0 flex-1 flex-col gap-2 overflow-auto", className)} {...props} />; }
function SidebarGroup({ className, ...props }: React.ComponentProps<"div">) { return <div className={cn("relative flex w-full flex-col p-2", className)} {...props} />; }
function SidebarGroupLabel({ className, asChild = false, ...props }: React.ComponentProps<"div"> & { asChild?: boolean }) { const Comp = asChild ? Slot : "div"; return <Comp className={cn("flex h-8 items-center px-2 text-xs font-semibold text-sidebar-foreground/70", className)} {...props} />; }
function SidebarGroupContent({ className, ...props }: React.ComponentProps<"div">) { return <div className={cn("w-full text-sm", className)} {...props} />; }
function SidebarMenu({ className, ...props }: React.ComponentProps<"ul">) { return <ul className={cn("flex w-full flex-col gap-1", className)} {...props} />; }
function SidebarMenuItem({ className, ...props }: React.ComponentProps<"li">) { return <li className={cn("group/menu-item relative", className)} {...props} />; }
function SidebarMenuButton({ asChild = false, isActive = false, className, ...props }: React.ComponentProps<"button"> & { asChild?: boolean; isActive?: boolean }) { const Comp = asChild ? Slot : "button"; return <Comp data-active={isActive} className={cn("flex min-h-10 w-full items-center gap-2 overflow-hidden rounded-md p-2 text-left text-sm outline-none hover:bg-sidebar-accent hover:text-sidebar-accent-foreground focus-visible:ring-2 focus-visible:ring-sidebar-ring data-[active=true]:bg-sidebar-primary data-[active=true]:text-sidebar-primary-foreground", className)} {...props} />; }
export { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger, useSidebar };
