/* eslint-disable @next/next/no-img-element -- evidence URL comes from the configured storage boundary */
import { ImageOff } from "lucide-react";
import { notFound } from "next/navigation";
import { DietName, EvaluationBadge, StatusBadge } from "@/components/presentation";
import { getTranslations } from "@/lib/locale";
import { readLocale } from "@/lib/locale-server";
import { readPublicDepartment } from "@/lib/patient-note";
import { submitPatientNoteAction } from "./actions";

const overallStatus = { OK: "OK", WARN: "LOW", FAIL: "HIGH", MISSING: "MISSING" } as const;

export default async function PatientPage({ params, searchParams }: { params: Promise<{ token: string }>; searchParams: Promise<{ note?: string; date?: string }> }) {
  const [{ token }, query, locale] = await Promise.all([params, searchParams, readLocale()]);
  const t = getTranslations(locale).publicPatient;
  const dateLabel = new Intl.DateTimeFormat(locale === "en" ? "en-US" : "vi-VN", { timeZone: "Asia/Ho_Chi_Minh", weekday: "long", day: "2-digit", month: "2-digit" });
  const data = await readPublicDepartment(token, query.date);
  if (!data) notFound();
  const action = submitPatientNoteAction.bind(null, token);
  const codeCount = (count: number) => count ? t.dietCodeCount.replace("{count}", String(count)) : t.noMenu;

  return <main className="patient-page" id="noi-dung-chinh"><header className="patient-header"><p className="eyebrow">{t.eyebrow}</p><h1 className="text-balance">{data.department.name}</h1><p>{t.departmentOnly}</p></header>
    <form method="get" className="patient-date-picker"><label htmlFor="patient-menu-date">{t.dateLabel}</label><div><input id="patient-menu-date" name="date" type="date" min={data.minDate} max={data.maxDate} defaultValue={data.selectedDate}/><button type="submit">{t.viewMenu}</button></div><small>{t.advanceWindow.replace("{days}", String(data.advanceEntryDays))}</small></form>
    <section className="patient-now-next" aria-label={t.timelineLabel}><article><span>{t.currentMeal}</span>{data.current ? <><strong>{data.current.mealType.name} · {data.current.mealType.serviceTime}</strong><small>{codeCount(data.current.dietMeals.length)}</small></> : <><strong>-</strong><small>{t.beforeFirstMeal}</small></>}</article><article><span>{t.nextMeal}</span>{data.next ? <><strong>{data.next.mealType.name} · {data.next.mealType.serviceTime}</strong><small>{dateLabel.format(data.next.mealDate)} · {codeCount(data.next.dietMeals.length)}</small></> : <><strong>-</strong><small>{t.noNextMeal}</small></>}</article></section>
    <section className="patient-section" aria-labelledby="selected-menu"><div className="patient-section-heading"><div><p className="eyebrow">{t.dayMenu}</p><h2 id="selected-menu">{dateLabel.format(new Date(`${data.selectedDate}T00:00:00.000Z`))}</h2></div></div>{!data.selectedEvents.length ? <div className="patient-empty" role="status"><strong>-</strong><p>{t.noConfirmedMenu}</p></div> : <div className="patient-day-meals">{data.selectedEvents.map((event) => <section className="patient-meal-block" key={event.id}><header><strong>{event.mealType.name}</strong><span>{event.mealType.serviceTime}</span></header><div className="public-diet-list">{event.dietMeals.map((meal) => <article className="public-diet" key={meal.id}>{data.showImages ? meal.evidence[0]?.publicUrl ? <img src={meal.evidence[0].publicUrl} alt={t.mealPhotoAlt.replace("{diet}", meal.dietType.name)} width={1200} height={900}/> : <div className="patient-photo-empty" role="img" aria-label={t.noMealPhotoAria.replace("{diet}", meal.dietType.name)}><ImageOff aria-hidden="true"/><strong>-</strong><span>{t.noMealPhoto}</span></div> : null}<div className="public-diet-body"><div className="public-diet-title"><h3><DietName name={meal.dietType.name} code={meal.dietType.code}/></h3><StatusBadge status={meal.status}/></div><div className="patient-menu"><span>{t.menu}</span><strong>{meal.menuItems.length ? meal.menuItems.join(" · ") : "-"}</strong>{meal.menuItems.length === 0 && <small>{t.noMenuData}</small>}</div><details className="patient-evaluation"><summary><span>{t.criteria}</span><EvaluationBadge status={overallStatus[meal.evaluation.overall]}/></summary>{meal.evaluation.criteria.length ? <ul>{meal.evaluation.criteria.map((criterion) => <li key={criterion.key}><span>{criterion.label}</span><EvaluationBadge status={criterion.status as "OK" | "LOW" | "HIGH" | "MISSING"}/></li>)}</ul> : <p>{t.noEvaluation}</p>}</details>{meal.patientVisibleNotes.length > 0 && <div className="patient-visible-note">{meal.patientVisibleNotes.map((note, index) => <section key={`${note.source}-${index}`}><span>{note.source === "DIETITIAN" ? t.dietitianNote : t.departmentNote}</span><p>{note.text}</p></section>)}</div>}</div></article>)}</div></section>)}</div>}</section>
    <section className="patient-note-form" id="gui-ghi-chu" aria-labelledby="note-heading"><p className="eyebrow">{t.sendToWard}</p><h2 id="note-heading">{t.feedbackTitle}</h2><p>{t.feedbackHelp}</p>{query.note === "sent" && <p className="patient-form-success" role="status" aria-live="polite">{t.noteSent}</p>}{query.note && query.note !== "sent" && <p className="patient-form-error" role="alert">{query.note === "limited" ? t.noteLimited : query.note === "invalid" ? t.noteInvalid : query.note === "invalidAttachment" ? t.invalidAttachment : t.noteUnavailable}</p>}<form action={action} encType="multipart/form-data"><label htmlFor="patient-note">{t.note} <span>{t.required}</span></label><textarea id="patient-note" name="note" minLength={3} maxLength={500} required placeholder={t.notePlaceholder}/><label htmlFor="contact-name">{t.contactName} <span>{t.optional}</span></label><input id="contact-name" name="contactName" maxLength={100} autoComplete="off"/><label htmlFor="patient-attachment">{t.attachment} <span>{t.optional}</span></label><input id="patient-attachment" name="attachment" type="file" accept="image/jpeg,image/png,image/webp"/><small>{t.attachmentHelp}</small><button type="submit">{t.submitNote}</button></form></section>
    <footer className="patient-footer">{t.footer}</footer>
  </main>;
}
