"use client";
import { startTransition, useState, useTransition } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm, useWatch } from "react-hook-form";
import { z } from "zod";
const lineSchema = z.object({ dietTypeId: z.string(), name: z.string(), code: z.string(), route: z.string(), quantity: z.string().regex(/^\d+$/, "Nhập số nguyên không âm."), internalNote: z.string().max(500, "Tối đa 500 ký tự."), patientVisibleNote: z.string().max(500, "Tối đa 500 ký tự."), totalLabel: z.string().optional() });
const schema = z.object({ lines: z.array(lineSchema) }); type Fields = z.infer<typeof schema>;
export function ServingForm({ mealEventId, editable, lines, action }: { mealEventId: string; editable: boolean; lines: Fields["lines"]; action: (data: FormData) => Promise<void> }) {
 const [pending, run] = useTransition(); const [selected, setSelected] = useState(0); const { register, handleSubmit, control, formState: { errors } } = useForm<Fields>({ resolver: zodResolver(schema), shouldFocusError: true, defaultValues: { lines } });
 const values = useWatch({ control, name: "lines" }); const active = values[selected] ?? values[0]; const total = values.reduce((sum, line) => sum + (Number.parseInt(line.quantity, 10) || 0), 0);
 const submit = handleSubmit((values) => { const data = new FormData(); data.set("mealEventId", mealEventId); values.lines.forEach((line) => { data.append("dietTypeId", line.dietTypeId); data.set(`quantity:${line.dietTypeId}`, line.quantity); data.set(`internalNote:${line.dietTypeId}`, line.internalNote); data.set(`patientVisibleNote:${line.dietTypeId}`, line.patientVisibleNote); }); startTransition(() => run(() => action(data))); });
 return <form onSubmit={submit} noValidate className="serving-editor"><div className="serving-editor-main"><div className="serving-table-scroll"><table className="serving-table"><thead><tr><th>Chế độ ăn</th><th>Số suất</th><th>Trạng thái</th></tr></thead><tbody>{lines.map((line, index) => <tr key={line.dietTypeId} className={selected === index ? "selected" : undefined} onClick={() => setSelected(index)}>
  <td><strong>{line.name}</strong><span>{line.code} · {line.route === "SONDE" ? "Sonde" : "Ăn thường"}</span></td>
  <td><label><span className="sr-only">Số suất {line.name}</span><input className="quantity-input tabular" type="number" min="0" step="1" inputMode="numeric" disabled={!editable} {...register(`lines.${index}.quantity`)} onFocus={() => setSelected(index)} aria-invalid={!!errors.lines?.[index]?.quantity} aria-describedby={errors.lines?.[index]?.quantity ? `quantity-${index}-error` : undefined} placeholder="—"/></label>{errors.lines?.[index]?.quantity && <span id={`quantity-${index}-error`} role="alert" className="field-error">{errors.lines[index]?.quantity?.message}</span>}</td>
  <td>{editable ? <span className={values[index]?.quantity ? "line-state ready" : "line-state missing"}>{values[index]?.quantity ? "Đã nhập" : "Chưa nhập"}</span> : <span className="serving-total">{line.totalLabel}</span>}</td>
 </tr>)}</tbody><tfoot><tr><th>Tổng</th><td className="tabular">{total || "—"}</td><td>{total ? `${total} suất` : "Chưa có số liệu"}</td></tr></tfoot></table></div></div><aside className="serving-detail" aria-live="polite"><div className="serving-detail-head"><span>Chi tiết chế độ</span><strong>{active?.name ?? "—"}</strong><small>{active ? `${active.code} · ${active.route === "SONDE" ? "Sonde" : "Ăn thường"}` : "—"}</small></div><div className="detail-total"><span>Số suất</span><strong className="tabular">{active?.quantity || "—"}</strong></div>{active && <div className="detail-notes"><label>Ghi chú nội bộ<span>Chỉ nhân viên nhìn thấy</span><textarea disabled={!editable} {...register(`lines.${selected}.internalNote`)} aria-invalid={!!errors.lines?.[selected]?.internalNote} placeholder="Ví dụ: chuyển suất tới phòng trực…"/></label><label>Thông tin bệnh nhân thấy<span>Có thể công khai qua QR khoa</span><textarea disabled={!editable} {...register(`lines.${selected}.patientVisibleNote`)} aria-invalid={!!errors.lines?.[selected]?.patientVisibleNote} placeholder="Ví dụ: bữa ăn phục vụ lúc 11:00…"/></label></div>}<footer className="serving-actions"><p>{editable ? "Có thể sửa trước giờ chốt. Mọi lần gửi đều được truy vết." : "Số suất gốc đã khóa. Phát sinh được báo bổ sung riêng."}</p><button className="primary-action" disabled={!editable || pending}>{pending ? "Đang gửi…" : "Gửi báo suất"}</button></footer></aside></form>;
}
