"use client";

import { startTransition, useMemo, useState, useTransition, type ReactNode } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowDown, ArrowRight, ArrowUp, Check, ClipboardCheck, Plus, Utensils } from "lucide-react";
import { useForm, useWatch } from "react-hook-form";
import { z } from "zod";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";

const lineSchema = z.object({ dietTypeId: z.string(), name: z.string(), code: z.string(), route: z.string(), quantity: z.string().regex(/^\d+$/, "Nhập số nguyên không âm."), internalNote: z.string().max(500), patientVisibleNote: z.string().max(500), previousQuantity: z.number().nullable(), menuItems: z.array(z.object({ dishName: z.string(), name: z.string(), grams: z.number().nullable() })), criteria: z.array(z.object({ label: z.string(), status: z.string(), actual: z.number().nullable(), target: z.string() })) });
const schema = z.object({ lines: z.array(lineSchema) });
type Fields = z.infer<typeof schema>;
const number = new Intl.NumberFormat("vi-VN", { maximumFractionDigits: 1 });

export function ServingForm({ mealEventId, departmentName, editable, lines, notesTrigger, lateAdditionTrigger, action }: { mealEventId: string; departmentName: string; editable: boolean; lines: Fields["lines"]; notesTrigger?: ReactNode; lateAdditionTrigger?: ReactNode; action: (data: FormData) => Promise<void> }) {
  const [pending, run] = useTransition();
  const [selected, setSelected] = useState(0);
  const [showAll, setShowAll] = useState(false);
  const { register, handleSubmit, control, formState: { errors } } = useForm<Fields>({ resolver: zodResolver(schema), shouldFocusError: true, defaultValues: { lines } });
  const values = useWatch({ control, name: "lines" });
  const active = values[selected] ?? values[0];
  const total = values.reduce((sum, line) => sum + (Number.parseInt(line.quantity, 10) || 0), 0);
  const changed = values.filter((line) => (Number.parseInt(line.quantity, 10) || 0) !== (line.previousQuantity ?? 0)).length;
  const visible = useMemo(() => showAll ? lines.map((_, index) => index) : lines.map((line, index) => ({ line, index })).filter(({ line }) => Number(line.quantity) > 0 || line.previousQuantity !== null).map(({ index }) => index), [lines, showAll]);
  const submit = handleSubmit((formValues, event) => { const form = event?.currentTarget; if (!(form instanceof HTMLFormElement)) return; const data = new FormData(form); data.set("mealEventId", mealEventId); formValues.lines.forEach((line) => { data.append("dietTypeId", line.dietTypeId); data.set(`quantity:${line.dietTypeId}`, line.quantity); data.set(`internalNote:${line.dietTypeId}`, line.internalNote); data.set(`patientVisibleNote:${line.dietTypeId}`, line.patientVisibleNote); }); startTransition(() => run(() => action(data))); });
  return <form id="nurse-serving-form" onSubmit={submit} noValidate className="nurse-serving-workspace">
    <section className="nurse-serving-master"><header className="nurse-serving-head"><div><span>Khoa phụ trách</span><strong>{departmentName}</strong></div><div className="nurse-head-actions">{notesTrigger}<span>{visible.length}/{lines.length} mã</span><b>{number.format(total)} suất</b></div></header>
      <div className="nurse-serving-table-scroll"><table className="nurse-serving-table"><thead><tr><th>Mã chế độ ăn</th><th>Bữa trước</th><th>Bữa hiện tại</th><th>Thay đổi</th><th><span className="sr-only">Chi tiết</span></th></tr></thead><tbody>{visible.map((index) => { const line = values[index]; const current = Number.parseInt(line.quantity, 10) || 0; const previous = line.previousQuantity; const delta = previous === null ? null : current - previous; return <tr key={line.dietTypeId} className={selected === index ? "selected" : ""} onClick={() => setSelected(index)}><th scope="row"><button type="button" onClick={() => setSelected(index)}><strong translate="no">{line.code}</strong><small>{line.name}</small></button></th><td className="numeric">{previous ?? "—"}</td><td><label><span className="sr-only">Số suất {line.name}</span><input type="number" min="0" step="1" inputMode="numeric" disabled={!editable} {...register(`lines.${index}.quantity`)} onFocus={() => setSelected(index)} aria-invalid={!!errors.lines?.[index]?.quantity}/></label></td><td>{delta === null ? <span className="trend neutral"><ArrowRight/>—</span> : delta > 0 ? <span className="trend up"><ArrowUp/>+{delta}</span> : delta < 0 ? <span className="trend down"><ArrowDown/>{delta}</span> : <span className="trend neutral"><ArrowRight/>0</span>}</td><td><button type="button" className="row-more" aria-label={`Xem chi tiết ${line.code}`} onClick={() => setSelected(index)}>•••</button></td></tr>; })}</tbody><tfoot><tr><th scope="row">Tổng suất</th><td>{lines.reduce((sum, line) => sum + (line.previousQuantity ?? 0), 0) || "—"}</td><td>{total || "—"}</td><td>{changed ? `${changed} mã đổi` : "Không đổi"}</td><td/></tr></tfoot></table></div>
      <footer className="nurse-serving-footer"><button type="button" className="secondary-button" onClick={() => setShowAll((value) => !value)}><Plus aria-hidden="true"/>{showAll ? "Ẩn mã chưa dùng" : "Thêm mã chế độ ăn"}</button>{editable ? <Dialog><DialogTrigger asChild><button type="button" className="primary-action" disabled={pending}><ClipboardCheck aria-hidden="true"/>Xác nhận báo suất</button></DialogTrigger><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>Xác nhận báo suất</DialogTitle><DialogDescription>Kiểm tra tổng số và nhập tên điều dưỡng trực tiếp báo để khoa đối chiếu.</DialogDescription></DialogHeader><div className="nurse-confirm-summary"><span>Tổng bữa hiện tại</span><strong>{number.format(total)} suất</strong><small>{changed ? `${changed} mã thay đổi so với bữa trước` : "Giữ nguyên như bữa trước"}</small></div><label className="nurse-reporter-name">Tên người trực tiếp báo<input form="nurse-serving-form" name="reportedByName" minLength={2} maxLength={100} autoComplete="name" required placeholder="Ví dụ: Nguyễn Thị Lan"/></label><button form="nurse-serving-form" type="submit" className="primary-action" disabled={pending}>{pending ? "Đang xác nhận…" : "Duyệt và gửi cho bếp"}</button></DialogContent></Dialog> : lateAdditionTrigger}</footer>
    </section>
    <aside className="nurse-serving-detail">{active ? <><header><span>Chi tiết mã</span><h2><span translate="no">{active.code}</span> · {active.name}</h2><strong>{active.quantity || "—"} suất</strong></header><section className="floating-block"><h3><Utensils aria-hidden="true"/>Thực đơn</h3>{active.menuItems.length ? <table><thead><tr><th>Món</th><th>Thực phẩm</th><th>Định lượng</th></tr></thead><tbody>{active.menuItems.map((item, index) => <tr key={`${item.name}-${index}`}><td>{item.dishName}</td><td>{item.name}</td><td>{item.grams === null ? "—" : `${number.format(item.grams)} g`}</td></tr>)}</tbody></table> : <p>— · Chưa có thực đơn được duyệt.</p>}</section><section className="floating-block"><h3><Check aria-hidden="true"/>Đánh giá thực đơn</h3>{active.criteria.length ? <table><thead><tr><th>Chỉ tiêu</th><th>Kết quả</th><th>Đối chiếu</th></tr></thead><tbody>{active.criteria.map((item, index) => <tr key={`${item.label}-${index}`}><td>{item.label}</td><td>{item.actual === null ? "—" : number.format(item.actual)}</td><td>{item.status === "MISSING" ? "—" : `${item.status} · ${item.target}`}</td></tr>)}</tbody></table> : <p>— · Chưa đủ dữ liệu đánh giá.</p>}</section><section className="floating-block nurse-code-notes"><h3>Ghi chú cho bếp</h3><label>Ghi chú nội bộ<textarea disabled={!editable} {...register(`lines.${selected}.internalNote`)} placeholder="Thông tin nghiệp vụ cho nhân viên…"/></label><label>Ghi chú chuyển bếp<textarea disabled={!editable} {...register(`lines.${selected}.patientVisibleNote`)} placeholder="Ghi chú đã duyệt sẽ chuyển đến bếp…"/></label></section></> : <div className="nurse-detail-empty"><Utensils/><h2>Chọn một mã chế độ ăn</h2><p>Chi tiết số suất, thực đơn và đánh giá sẽ hiện tại đây.</p></div>}</aside>
  </form>;
}
