"use client";

/* eslint-disable @next/next/no-img-element -- ảnh bằng chứng dùng URL từ lớp lưu trữ cấu hình */
import Link from "next/link";
import { CalendarDays, Check, ChevronRight, ClipboardPlus, Image as ImageIcon, LayoutList, Utensils } from "lucide-react";
import { useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { MealLifecycleStrip } from "@/components/meal-lifecycle-strip";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import type { ManagementDay, ManagementDiet, ManagementMeal } from "@/lib/management";
import { hospitalDayKey, mealTimePhase } from "@/lib/meal-events";
import { createAdminAdditionAction } from "./actions";

const number = new Intl.NumberFormat("vi-VN");
const dateTime = new Intl.DateTimeFormat("vi-VN", { timeZone: "Asia/Ho_Chi_Minh", hour: "2-digit", minute: "2-digit", day: "2-digit", month: "2-digit" });
const ACK = { PENDING: "Chờ bếp", RECEIVED: "Đã nhận", INSUFFICIENT: "Không đủ", SUBSTITUTE: "Thay thế" } as const;
type ViewMode = "department" | "diet";

function AddIncident({ meal }: { meal: ManagementMeal }) {
  return <Dialog><DialogTrigger asChild><button type="button" className="admin-add-incident"><ClipboardPlus/> Bổ sung phát sinh</button></DialogTrigger><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>Bổ sung phát sinh thay khoa</DialogTitle><DialogDescription>Nội dung được ghi AuditLog và chuyển tới bếp ở trạng thái chờ xác nhận.</DialogDescription></DialogHeader><form action={createAdminAdditionAction} className="admin-incident-form"><input type="hidden" name="mealEventId" value={meal.id}/><label>Khoa<select name="departmentId" required>{meal.departments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Mã chế độ ăn<select name="dietMealId" required>{meal.diets.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>Số suất<input type="number" name="quantity" min="1" step="1" required/></label><label>Lý do<textarea name="reason" minLength={3} maxLength={500} required/></label><button className="primary-action">Lưu và chuyển bếp xác nhận</button></form></DialogContent></Dialog>;
}

function DepartmentDetail({ meal, id }: { meal: ManagementMeal; id: string }) {
  const department = meal.departments.find((item) => item.id === id); if (!department) return null;
  const additions = meal.additions.filter((item) => item.departmentId === id);
  return <aside className="admin-serving-detail"><header><div><span>Chi tiết khoa</span><h2>{department.name}</h2></div><b>{department.reportId ? "Đã chốt" : "Chưa chốt"}</b></header><div className="admin-detail-scroll"><dl><div><dt>Người báo</dt><dd>{department.submittedBy ?? "—"}</dd></div><div><dt>Thời gian</dt><dd>{department.submittedAt ? dateTime.format(new Date(department.submittedAt)) : "—"}</dd></div></dl><section><h3>Cơ cấu suất ăn</h3><table><thead><tr><th>Mã chế độ ăn</th><th>Suất</th></tr></thead><tbody>{department.lines.length ? department.lines.map((line) => <tr key={line.dietCode}><th>{line.dietCode} · {line.dietName}</th><td>{number.format(line.quantity)}</td></tr>) : <tr><td colSpan={2}>— · Chưa có dữ liệu.</td></tr>}</tbody><tfoot><tr><th>Tổng</th><td>{department.totalServings === null ? "—" : number.format(department.totalServings)}</td></tr></tfoot></table></section><section><h3>Phát sinh</h3>{additions.length ? additions.map((item) => <article key={item.id}><strong>+{item.quantity} suất · {item.dietCode}</strong><p>{item.reason}</p><small>{ACK[item.ackStatus]} · {item.submittedBy}</small></article>) : <p>— · Không có phát sinh.</p>}</section></div></aside>;
}

function DietDetail({ meal, diet }: { meal: ManagementMeal; diet: ManagementDiet }) {
  const departments = meal.departments.flatMap((department) => { const line = department.lines.find((item) => item.dietCode === diet.code); return line ? [{ id: department.id, name: department.name, quantity: line.quantity }] : []; });
  return <aside className="admin-serving-detail"><header><div><span>Chi tiết mã chế độ ăn</span><h2>{diet.code} · {diet.name}</h2></div><b>{diet.status === "PLANNED" ? "Chưa chốt" : "Đã chốt"}</b></header><div className="admin-detail-scroll"><section><h3>Số lượng theo khoa</h3><table><thead><tr><th>Khoa</th><th>Suất</th></tr></thead><tbody>{departments.length ? departments.map((item) => <tr key={item.id}><th>{item.name}</th><td>{item.quantity}</td></tr>) : <tr><td colSpan={2}>— · Chưa có khoa báo mã này.</td></tr>}</tbody></table></section><section><h3>Hình ảnh và bằng chứng bếp</h3>{diet.evidence.length ? <div className="admin-evidence-grid">{diet.evidence.map((item) => <article key={item.id}>{item.publicUrl ? <img src={item.publicUrl} alt={`Bằng chứng ${diet.code}`}/> : <span><ImageIcon/>—</span>}<strong>{item.kind === "FOOD_SAMPLE" ? "Ảnh lưu mẫu" : "Ảnh bữa ăn"}</strong><small>{item.uploadedBy} · {dateTime.format(new Date(item.uploadedAt))}</small></article>)}</div> : <p>— · Bếp chưa gửi bằng chứng.</p>}</section></div></aside>;
}

function ReviewSchedule({ dates, meals, serviceCompletionMinutes }: { dates: Array<{ value: string; label: string; active: boolean }>; meals: ManagementMeal[]; serviceCompletionMinutes: number }) {
  const searchParams = useSearchParams();
  const activeDate = dates.find((date) => date.active);
  const now = new Date();
  const selectedMeal = meals.find((meal) => meal.serviceTime === searchParams.get("meal")) ?? meals.find((meal) => meal.serviceAt && new Date(meal.serviceAt).getTime() >= now.getTime()) ?? meals.at(-1);
  const selectedMealTime = selectedMeal?.serviceTime ?? "";
  const today = hospitalDayKey(now);
  return <Dialog><DialogTrigger asChild><button type="button" className="admin-review-trigger"><CalendarDays/><span><strong>Xem lại ngày/bữa</strong><small>{activeDate?.label ?? "—"} · {selectedMeal?.name ?? "—"}</small></span></button></DialogTrigger><DialogContent className="max-w-5xl"><DialogHeader><DialogTitle>Đang xem: {activeDate?.label ?? "—"} · {selectedMeal?.name ?? "—"}</DialogTitle><DialogDescription>Chọn trực tiếp một ô ngày và bữa. Xám là đã qua, xanh là đang diễn ra, nền sáng là tương lai.</DialogDescription></DialogHeader><div className="admin-review-legend"><span className="past">Đã qua</span><span className="current">Hiện tại</span><span className="future">Tương lai</span></div><div className="admin-review-calendar"><table><thead><tr><th>Bữa</th>{dates.map((date) => { const dayTone = date.value < today ? "past" : date.value === today ? "current" : "future"; return <th className={`${dayTone} ${date.active ? "selected" : ""}`} key={date.value}>{date.label}{date.active ? <small>Đang xem</small> : null}</th>; })}</tr></thead><tbody>{meals.map((meal) => <tr key={meal.serviceTime}><th><strong>{meal.name}</strong><small>{meal.serviceTime}</small></th>{dates.map((date) => { const phase = mealTimePhase(new Date(`${date.value}T00:00:00.000Z`), meal.cutoffTime, meal.serviceTime, now, serviceCompletionMinutes); const tone = phase === "PASSED" ? "past" : phase === "PREPARING" || phase === "SERVING" ? "current" : "future"; const selected = date.active && meal.serviceTime === selectedMealTime; return <td key={date.value}><Link className={`${tone} ${selected ? "selected" : ""}`} aria-current={selected ? "true" : undefined} href={`?date=${date.value}&meal=${encodeURIComponent(meal.serviceTime)}`}><Utensils/><span>{meal.name}</span>{tone === "current" ? <small>Hiện tại</small> : null}</Link></td>; })}</tr>)}</tbody></table></div></DialogContent></Dialog>;
}

export function ManagementBoard({ data, dates, initialMealTime }: { data: ManagementDay; dates: Array<{ value: string; label: string; active: boolean }>; initialMealTime?: string }) {
  const [mealId, setMealId] = useState(data.meals.find((meal) => meal.serviceTime === initialMealTime)?.id ?? data.meals.find((meal) => meal.serviceAt && new Date(meal.serviceAt).getTime() >= new Date(data.generatedAt).getTime())?.id ?? data.meals.at(-1)?.id ?? "");
  const [mode, setMode] = useState<ViewMode>("department"); const meal = data.meals.find((item) => item.id === mealId) ?? data.meals[0];
  const firstId = mode === "department" ? meal?.departments[0]?.id : meal?.diets[0]?.id; const [selectedId, setSelectedId] = useState(""); const activeId = selectedId || firstId || "";
  const totals = useMemo(() => ({ servings: meal?.reportedServings ?? null, additions: meal?.additions.reduce((sum, item) => sum + item.quantity, 0) ?? 0 }), [meal]);
  if (!meal) return <p>— · Chưa có bữa ăn trong ngày này.</p>;
  return <section className="admin-serving-board"><div className="admin-serving-top"><MealLifecycleStrip data={data} role="ADMIN" selectedMealId={meal.id}/><ReviewSchedule dates={dates} meals={data.meals} serviceCompletionMinutes={data.serviceCompletionMinutes}/></div><div className="admin-serving-grid"><section className="admin-serving-master"><header><div><span>Điều hành toàn viện</span><h1>Quản lý suất ăn</h1></div><div className="admin-view-switch"><button className={mode === "department" ? "active" : ""} onClick={() => { setMode("department"); setSelectedId(""); }}><LayoutList/>Theo khoa</button><button className={mode === "diet" ? "active" : ""} onClick={() => { setMode("diet"); setSelectedId(""); }}><Utensils/>Theo mã chế độ ăn</button></div><AddIncident meal={meal}/></header><div className="admin-serving-table"><table><thead><tr><th>{mode === "department" ? "Khoa" : "Mã chế độ ăn"}</th><th>Trạng thái</th><th>Số suất</th><th>Phát sinh</th><th/></tr></thead><tbody>{mode === "department" ? meal.departments.map((item) => { const additions = meal.additions.filter((addition) => addition.departmentId === item.id); return <tr className={activeId === item.id ? "selected" : ""} onClick={() => setSelectedId(item.id)} key={item.id}><th>{item.name}<small>{item.code}</small></th><td>{item.reportId ? <span className="ok"><Check/>Đã chốt</span> : <span>Chưa chốt</span>}</td><td>{item.totalServings ?? "—"}</td><td>{additions.reduce((sum, value) => sum + value.quantity, 0) || "—"}</td><td><ChevronRight/></td></tr>; }) : meal.diets.map((item) => { const additions = meal.additions.filter((addition) => addition.dietCode === item.code); return <tr className={activeId === item.id ? "selected" : ""} onClick={() => setSelectedId(item.id)} key={item.id}><th>{item.code}<small>{item.name}</small></th><td>{item.status === "PLANNED" ? "Chưa chốt" : <span className="ok"><Check/>Đã chốt</span>}</td><td>{item.servings ?? "—"}</td><td>{additions.reduce((sum, value) => sum + value.quantity, 0) || "—"}</td><td><ChevronRight/></td></tr>; })}</tbody><tfoot><tr><th>Tổng cộng</th><td>{mode === "department" ? `${meal.reportedDepartmentCount}/${meal.totalDepartmentCount}` : `${meal.diets.length} mã`}</td><td>{totals.servings ?? "—"}</td><td>{totals.additions || "—"}</td><td/></tr></tfoot></table></div></section>{mode === "department" ? <DepartmentDetail meal={meal} id={activeId}/> : <DietDetail meal={meal} diet={meal.diets.find((item) => item.id === activeId) ?? meal.diets[0]}/>}</div></section>;
}
