"use client";

import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import type { ManagementDay, ManagementDepartment, ManagementDiet, ManagementMeal, ManagementStatus } from "@/lib/management";

const numberFormat = new Intl.NumberFormat("vi-VN");
const timeFormat = new Intl.DateTimeFormat("vi-VN", { timeZone: "Asia/Ho_Chi_Minh", hour: "2-digit", minute: "2-digit", hour12: false });
const MANAGEMENT_STATUSES: ManagementStatus[] = ["PLANNED", "LOCKED", "PREPARING", "PREPARED", "SERVED"];
const STATUS_LABEL = { PLANNED: "Dự kiến", LOCKED: "Đã chốt", PREPARING: "Đang chuẩn bị", PREPARED: "Đã chuẩn bị", SERVED: "Đã phục vụ" } as const;
const STATUS_CLASS = { PLANNED: "status-planned", LOCKED: "status-locked", PREPARING: "status-preparing", PREPARED: "status-prepared", SERVED: "status-served" } as const;

function DietDialog({ diet }: { diet: ManagementDiet }) {
  return <Dialog><DialogTrigger asChild><button type="button" className="management-row-button"><span className="font-medium text-foreground">{diet.code} · {diet.name}</span><span className={`status-badge ${STATUS_CLASS[diet.status]}`}>{STATUS_LABEL[diet.status]}</span><span className="text-right tabular-nums">{numberFormat.format(diet.servings)} suất</span></button></DialogTrigger><DialogContent className="max-w-xl gap-3 p-4"><DialogHeader className="pr-8"><DialogTitle>{diet.code} · {diet.name}</DialogTitle><DialogDescription>Chi tiết tiến độ chế độ ăn. Dữ liệu chỉ đọc.</DialogDescription></DialogHeader><dl className="management-detail-grid"><div><dt>Trạng thái bếp</dt><dd><span className={`status-badge ${STATUS_CLASS[diet.status]}`}>{STATUS_LABEL[diet.status]}</span></dd></div><div><dt>Số suất toàn viện</dt><dd className="tabular-nums">{numberFormat.format(diet.servings)} suất</dd></div></dl></DialogContent></Dialog>;
}

function DepartmentDialog({ department, mealName }: { department: ManagementDepartment; mealName: string }) {
  return <Dialog><DialogTrigger asChild><button type="button" className="management-row-button"><span className="font-medium text-foreground">{department.code} · {department.name}</span><span className={department.reportId ? "report-ok" : "report-missing"}>{department.reportId ? "Đã báo" : "Chưa báo"}</span><span className="text-right tabular-nums">{department.totalServings === null ? "—" : `${numberFormat.format(department.totalServings)} suất`}</span></button></DialogTrigger><DialogContent className="max-h-[85vh] max-w-2xl gap-3 overflow-y-auto overscroll-contain p-4"><DialogHeader className="pr-8"><DialogTitle>{department.code} · {department.name}</DialogTitle><DialogDescription>{mealName} · {department.reportId ? `Đã gửi lúc ${department.submittedAt ? timeFormat.format(new Date(department.submittedAt)) : "—"}` : "Chưa có báo suất đã gửi"}.</DialogDescription></DialogHeader>{department.lines.length === 0 ? <p className="management-empty">— · Chưa có chi tiết chế độ ăn.</p> : <table className="management-dialog-table"><thead><tr><th>Chế độ ăn</th><th>Số suất</th></tr></thead><tbody>{department.lines.map((line) => <tr key={line.dietCode}><td>{line.dietCode} · {line.dietName}</td><td>{numberFormat.format(line.quantity)}</td></tr>)}</tbody><tfoot><tr><th>Tổng đã báo</th><th>{department.totalServings === null ? "—" : numberFormat.format(department.totalServings)}</th></tr></tfoot></table>}</DialogContent></Dialog>;
}

function MealSection({ meal }: { meal: ManagementMeal }) {
  return <section className="management-meal" aria-labelledby={`meal-${meal.id}`}><header><div><div className="flex items-center gap-2"><h3 id={`meal-${meal.id}`}>{meal.name}</h3>{meal.focus !== "OTHER" ? <span className="meal-focus">{meal.focus === "CURRENT" ? "Đang phục vụ" : "Sắp phục vụ"}</span> : null}</div><p>Phục vụ {meal.serviceTime || "—"} · {meal.totalDiets > 0 ? `${meal.totalDiets} chế độ ăn` : "— chế độ ăn"}</p></div><div className="status-summary" aria-label="Tổng hợp trạng thái bếp">{MANAGEMENT_STATUSES.map((status) => <span key={status} className={STATUS_CLASS[status]}><b>{meal.statusCounts[status]}</b> {STATUS_LABEL[status]}</span>)}</div></header><div className="management-columns"><div className="management-pane"><div className="pane-heading"><div><h4>Bếp tới đâu</h4><p>Tiến độ theo chế độ ăn</p></div><strong>{meal.totalDiets > 0 ? meal.totalDiets : "—"}</strong></div><div className="management-list">{meal.diets.length === 0 ? <p className="management-empty">— · Chưa có chế độ ăn hợp lệ.</p> : meal.diets.map((diet) => <DietDialog key={diet.id} diet={diet} />)}</div></div><div className="management-pane"><div className="pane-heading"><div><h4>Khoa đã báo suất</h4><p>Hiện tất cả khoa, gồm khoa chưa báo</p></div><strong className="tabular-nums">{meal.totalDepartmentCount > 0 ? `${meal.reportedDepartmentCount}/${meal.totalDepartmentCount}` : "—"}</strong></div><div className="management-list">{meal.departments.length === 0 ? <p className="management-empty">— · Chưa có danh mục khoa hoạt động.</p> : meal.departments.map((department) => <DepartmentDialog key={department.id} department={department} mealName={meal.name} />)}</div><footer><span>Tổng từ báo suất đã gửi</span><strong className="tabular-nums">{meal.reportedServings === null ? "—" : `${numberFormat.format(meal.reportedServings)} suất`}</strong></footer></div></div></section>;
}

export function ManagementBoard({ data }: { data: ManagementDay }) {
  return <section className="management-board" aria-labelledby="operations-heading"><div className="management-section-heading"><div><p className="eyebrow">Điều hành toàn viện</p><h2 id="operations-heading">Xử lý tiếp theo & hiện tại</h2></div><p>Chọn từng dòng để xem chi tiết. Không chỉnh sửa dữ liệu tại đây.</p></div>{data.meals.length === 0 ? <div className="management-empty management-empty-day">— · Chưa có bữa ăn trong lịch ngày đã chọn.</div> : data.meals.map((meal) => <MealSection key={meal.id} meal={meal} />)}</section>;
}
