"use client";

import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import type { ManagementSchedule, ManagementScheduleDiet, ManagementScheduleRoute, ManagementStatus } from "@/lib/management";

const numberFormat = new Intl.NumberFormat("vi-VN");
const dateTimeFormat = new Intl.DateTimeFormat("vi-VN", { timeZone: "Asia/Ho_Chi_Minh", day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false });
const STATUS_LABEL: Record<ManagementStatus, string> = { PLANNED: "Chưa báo bếp", LOCKED: "Đã báo · Chưa làm", PREPARING: "Đang làm", PREPARED: "Bếp đã xong", SERVED: "Đã phục vụ" };
const NOTE_LABEL = { MENU: "Thực đơn", SERVING: "Báo suất", PATIENT: "Người bệnh" } as const;
const PHASE_LABEL = { SERVED: "Đã phục vụ", PREPARING: "Đang chuẩn bị", SERVING: "Đang phục vụ" } as const;
const ROUTES: Array<{ id: ManagementScheduleRoute; title: string; subtitle: string; warehouseLabel: string }> = [
  { id: "NORMAL", title: "Ăn đường miệng", subtitle: "Chế độ ăn theo đường nuôi NORMAL", warehouseLabel: "Kho bếp" },
  { id: "SONDE", title: "Ăn qua sonde", subtitle: "Chế độ ăn theo đường nuôi SONDE", warehouseLabel: "Kho khoa / sonde" },
];

function DietDetail({ diet, serviceLabel }: { diet: ManagementScheduleDiet; serviceLabel: string }) {
  return <Dialog><DialogTrigger asChild><button type="button" className="schedule-diet-button" aria-label={`Xem ${diet.code}, ${diet.servings === null ? "chưa có số suất" : `${diet.servings} suất`}`}><span className="schedule-diet-code" translate="no">{diet.code}{diet.notes.length > 0 ? <span className="note-marker" title="Có ghi chú" aria-label="Có ghi chú" /> : null}</span><span className="schedule-diet-count">{diet.servings === null ? "—" : numberFormat.format(diet.servings)}</span><span className={`kitchen-state kitchen-${diet.status.toLowerCase()}`}>{STATUS_LABEL[diet.status]}</span></button></DialogTrigger><DialogContent className="schedule-dialog max-h-[88vh] max-w-3xl overflow-y-auto overscroll-contain p-4"><DialogHeader className="pr-8"><DialogTitle><span translate="no">{diet.code}</span> · {diet.name}</DialogTitle><DialogDescription>{serviceLabel} · Chi tiết chỉ đọc.</DialogDescription></DialogHeader><dl className="schedule-dialog-summary"><div><dt>Số suất toàn viện</dt><dd>{diet.servings === null ? "—" : `${numberFormat.format(diet.servings)} suất`}</dd></div><div><dt>Trạng thái bếp</dt><dd><span className={`kitchen-state kitchen-${diet.status.toLowerCase()}`}>{STATUS_LABEL[diet.status]}</span></dd></div></dl><section aria-labelledby={`menu-${diet.id}`}><h3 id={`menu-${diet.id}`}>Món trong snapshot</h3>{diet.menuItems.length > 0 ? <ul className="schedule-compact-list">{diet.menuItems.map((item, index) => <li key={`${item}-${index}`}>{item}</li>)}</ul> : <p className="schedule-missing">— · Chưa có snapshot thực đơn.</p>}</section><section aria-labelledby={`departments-${diet.id}`}><h3 id={`departments-${diet.id}`}>Số suất theo khoa</h3>{diet.departments.length > 0 ? <table className="schedule-detail-table"><thead><tr><th scope="col">Khoa</th><th scope="col">Số suất</th></tr></thead><tbody>{diet.departments.map((department) => <tr key={department.id}><td><span translate="no">{department.code}</span> · {department.name}</td><td>{numberFormat.format(department.quantity)}</td></tr>)}</tbody></table> : <p className="schedule-missing">— · Chưa có báo suất đã gửi cho mã này.</p>}</section><section aria-labelledby={`notes-${diet.id}`}><h3 id={`notes-${diet.id}`}>Ghi chú liên quan</h3>{diet.notes.length > 0 ? <ul className="schedule-note-list">{diet.notes.map((note, index) => <li key={`${note.source}-${index}`}><span>{NOTE_LABEL[note.source]}</span><div>{note.department ? <b>{note.department} · </b> : null}{note.text}</div></li>)}</ul> : <p className="schedule-missing">— · Không có ghi chú.</p>}</section></DialogContent></Dialog>;
}

export function ScheduleBoard({ data }: { data: ManagementSchedule }) {
  return <section className="schedule-board" aria-labelledby="schedule-heading"><div className="schedule-heading"><div><p className="eyebrow">3 ngày từ hôm nay · Chỉ xem</p><h2 id="schedule-heading">Lịch xuất ăn</h2></div><div className="schedule-legend" aria-label="Chú giải màu thời gian">{Object.entries(PHASE_LABEL).map(([phase, label]) => <span key={phase} className={`phase-key phase-${phase.toLowerCase()}`}><i aria-hidden="true" />{label}</span>)}</div></div>{ROUTES.map((route) => { const warehouse = data.routes[route.id].warehouse; return <section className={`schedule-route route-${route.id.toLowerCase()}`} key={route.id} aria-labelledby={`route-${route.id}`}><header className="schedule-route-header"><div><h3 id={`route-${route.id}`}>{route.title}</h3><p>{route.subtitle}</p></div><div className="warehouse-highlight"><span>{route.warehouseLabel} · Nhập gần nhất</span>{warehouse ? <strong>{warehouse.name} · {dateTimeFormat.format(new Date(warehouse.occurredAt))} · {warehouse.lineCount} dòng</strong> : <strong>— · Chưa có lần nhập phù hợp</strong>}</div></header><div className="schedule-grid-wrap"><table className="schedule-grid"><thead><tr><th scope="col" className="meal-column">Bữa / giờ</th>{data.days.map((day) => <th scope="col" key={day.date}><span>{day.label}</span>{day.isToday ? <small>Hôm nay</small> : null}</th>)}</tr></thead><tbody>{data.mealTypes.map((mealType) => <tr key={mealType.id}><th scope="row"><strong>{mealType.name}</strong><span>{mealType.serviceTime || "—"}</span></th>{data.days.map((day) => { const cell = day.cells[mealType.id]; const diets = cell?.diets.filter((diet) => diet.feedingRoute === route.id) ?? []; return <td key={day.date} className={`schedule-cell ${cell ? `phase-${cell.phase.toLowerCase()}` : "phase-preparing"}`}><div className="cell-phase"><span>{cell ? PHASE_LABEL[cell.phase] : "Đang chuẩn bị"}</span><small>{cell?.serviceTime || mealType.serviceTime || "—"}</small></div>{diets.length > 0 ? <div className="schedule-diets">{diets.map((diet) => <DietDetail key={diet.id} diet={diet} serviceLabel={`${day.label} · ${mealType.name} ${cell?.serviceTime || "—"}`} />)}</div> : <p className="schedule-cell-empty">—</p>}</td>; })}</tr>)}</tbody></table></div></section>; })}</section>;
}
