/* eslint-disable @next/next/no-img-element -- evidence URLs may use a deployment-specific storage backend */
import { redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { getSessionUser } from "@/lib/auth";
import { KITCHEN_STATUS_LABEL, nextKitchenStatus, readNextKitchenMeal } from "@/lib/kitchen";
import { transitionMealAction, uploadEvidenceAction } from "./actions";

const dateLabel = new Intl.DateTimeFormat("vi-VN", { timeZone: "Asia/Ho_Chi_Minh", weekday: "long", day: "2-digit", month: "2-digit", year: "numeric" });
const evidenceLabel = { MEAL_PHOTO: "Ảnh bữa ăn", FOOD_SAMPLE: "Ảnh lưu mẫu", STOCK_IN: "Ảnh nhập kho", INVOICE: "Hóa đơn / bill" } as const;
const actionLabel = { PREPARING: "Nhận suất & bắt đầu chuẩn bị", PREPARED: "Đã chuẩn bị", SERVED: "Đã phục vụ" } as const;
const grams = new Intl.NumberFormat("vi-VN", { maximumFractionDigits: 1 });

export default async function KitchenPage({ searchParams }: { searchParams: Promise<{ updated?: string; storage?: string }> }) {
  const user = await getSessionUser(); if (!user) redirect("/"); if (user.role !== "KITCHEN") redirect("/");
  const [meal, query] = await Promise.all([readNextKitchenMeal(), searchParams]);
  return <AppShell user={user}><main className="workspace kitchen-page">
    <header className="page-heading"><div><p className="eyebrow">Bữa tiếp theo</p><h1>{meal ? `${meal.mealType.name} · ${dateLabel.format(meal.mealDate)}` : "Chưa có bữa cần xử lý"}</h1></div>{meal && <p className="scope-note">Phục vụ lúc {meal.mealType.serviceTime} · <span className="tabular">{meal.dietMeals.reduce((sum, item) => sum + item.servingsPlanned, 0)} suất đã báo</span></p>}</header>
    {query.updated && <p className="success-banner" role="status">{query.updated === "status" ? "Đã cập nhật trạng thái và ghi nhật ký." : "Đã lưu bằng chứng và ghi nhật ký."}</p>}
    {query.storage === "unavailable" && <p className="storage-notice" role="status">Ảnh đang tạm nằm im vì máy chủ chưa cấu hình nơi lưu. Trạng thái bữa ăn không bị ảnh hưởng.</p>}
    {!meal ? <section className="empty-state"><h2>Không có dữ liệu bữa tiếp theo</h2><p>Hệ thống không tự tạo bữa hoặc đoán số suất.</p></section> : <>
      <section className="kitchen-meals" aria-labelledby="meal-lines"><div className="section-heading"><div><p className="eyebrow">Tiến độ theo chế độ</p><h2 id="meal-lines">Thực đơn và số suất</h2></div><span>Mỗi chế độ tiến độc lập</span></div><div className="kitchen-meal-list">{meal.dietMeals.map((item) => { const next = nextKitchenStatus(item.status); const snapshot = item.menuSnapshotJson as { items?: Array<{ itemName?: string }> } | null; return <article className="kitchen-meal-row" key={item.id}><div><strong>{item.dietType.name}</strong><span>{item.dietType.code} · {item.feedingRoute === "SONDE" ? "Sonde" : "Ăn thường"}</span></div><div className="meal-menu"><span>Thực đơn</span><strong>{snapshot?.items?.map((food) => food.itemName).filter(Boolean).join(", ") || "—"}</strong></div><div className="meal-count"><span>Số suất</span><strong className="tabular">{item.servingsPlanned > 0 ? item.servingsPlanned : "—"}</strong></div><span className={`status status-${item.status.toLowerCase()}`}>{KITCHEN_STATUS_LABEL[item.status]}</span>{next ? <form action={transitionMealAction}><input type="hidden" name="dietMealId" value={item.id}/><input type="hidden" name="target" value={next}/><button className="primary-action">{actionLabel[next as keyof typeof actionLabel]}</button></form> : <span className="workflow-done">Đã hoàn tất</span>}</article>; })}</div></section>
      <div className="kitchen-grid"><section className="shopping-panel"><div className="section-heading"><div><p className="eyebrow">Xuất dự kiến</p><h2>Danh sách đi chợ</h2></div><span>Thực đơn × suất</span></div>{meal.shopping.items.length ? <table className="shopping-table"><thead><tr><th>Thực phẩm</th><th>Khối lượng ăn được</th><th>Cần mua</th></tr></thead><tbody>{meal.shopping.items.map((item) => <tr key={item.foodId}><td>{item.foodName}</td><td className="tabular">{grams.format(item.edibleGrams)} g</td><td className="tabular"><strong>{item.rawGrams === null ? "—" : `${grams.format(item.rawGrams)} g`}</strong></td></tr>)}</tbody></table> : <div className="panel-empty">—<span>Chưa đủ dữ liệu để tính danh sách mua.</span></div>}{meal.shopping.incomplete.length > 0 && <div className="data-warnings" role="alert"><strong>Cần bổ sung dữ liệu</strong><ul>{meal.shopping.incomplete.map((warning, index) => <li key={`${warning.reason}-${index}`}>{warning.reason}</li>)}</ul></div>}</section>
        <section className="evidence-panel"><div className="section-heading"><div><p className="eyebrow">Bằng chứng</p><h2>Ảnh và chứng từ</h2></div><span>Không đổi trạng thái</span></div><form className="evidence-form" action={uploadEvidenceAction} encType="multipart/form-data"><label>Chế độ ăn<select name="dietMealId" required>{meal.dietMeals.map((item) => <option key={item.id} value={item.id}>{item.dietType.name}</option>)}</select></label><label>Loại bằng chứng<select name="kind" required>{Object.entries(evidenceLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Ảnh<input name="file" type="file" accept="image/*" required/></label><label>Ghi chú<input name="note" maxLength={500} placeholder="Không bắt buộc"/></label><button className="secondary-button">Đính kèm ảnh</button></form><div className="evidence-list">{meal.evidence.length === 0 ? <p>Chưa có bằng chứng đã lưu.</p> : meal.evidence.map((item) => <article key={item.id}>{item.publicUrl ? <img src={item.publicUrl} alt={`${evidenceLabel[item.kind]} · ${item.dietName}`}/> : <div className="evidence-unavailable">Ảnh chưa có URL hiển thị</div>}<div><strong>{evidenceLabel[item.kind]}</strong><span>{item.dietName}{item.note ? ` · ${item.note}` : ""}</span></div></article>)}</div></section>
      </div></>}
  </main></AppShell>;
}
