import type { Language } from "@/lib/i18n";

export const SUBMISSION_TEXT = {
  vi: {
    types: {
      FEEDBACK: "Phản ánh",
      KITCHEN_NOTE: "Ghi chú Bếp",
    },
    statuses: {
      RECEIVED: "Chưa xử lý",
      APPROVED: "Đã xử lý/chuyển Bếp",
      REJECTED: "Từ chối",
    },
    eyebrow: "Công khai",
    title: "Phản ánh & Ghi chú Bếp",
    pending: (count: number) => `${count} nội dung chưa xử lý`,
    nonePending: "Không có nội dung chờ xử lý",
    type: "Loại",
    status: "Trạng thái",
    all: "Tất cả",
    filter: "Lọc",
    department: "Khoa",
    content: "Nội dung",
    contact: "Liên hệ",
    attachment: "Đính kèm",
    time: "Thời gian",
    handling: "Xử lý",
    viewImage: "Xem ảnh",
    reviewPlaceholder: "Ghi chú xử lý",
    forwardKitchen: "Chuyển Bếp",
    handled: "Đã xử lý",
    reject: "Từ chối",
    invalidStatus: "Trạng thái xử lý không hợp lệ.",
  },
  en: {
    types: {
      FEEDBACK: "Feedback",
      KITCHEN_NOTE: "Kitchen Note",
    },
    statuses: {
      RECEIVED: "Pending",
      APPROVED: "Handled/forwarded to Kitchen",
      REJECTED: "Rejected",
    },
    eyebrow: "Public submissions",
    title: "Feedback & Kitchen Notes",
    pending: (count: number) =>
      `${count} pending submission${count === 1 ? "" : "s"}`,
    nonePending: "No submissions are waiting for review",
    type: "Type",
    status: "Status",
    all: "All",
    filter: "Filter",
    department: "Department",
    content: "Content",
    contact: "Contact",
    attachment: "Attachment",
    time: "Time",
    handling: "Action",
    viewImage: "View image",
    reviewPlaceholder: "Review note",
    forwardKitchen: "Forward to Kitchen",
    handled: "Mark handled",
    reject: "Reject",
    invalidStatus: "Invalid review status.",
  },
} as const satisfies Record<Language, object>;
